import { FACTS, CHECKED, SRC } from './facts'
import { callout, h2, h3, p, plansTable, table, ul, type SeoPage } from './types'

const { free, starter } = FACTS
const acct = `${FACTS.accounts.free} on Free, ${FACTS.accounts.starter} on Starter, ${FACTS.accounts.pro} on Pro, ${FACTS.accounts.business} on Business`
const NOTE = 'Competitor details are from each vendor\'s own pricing page, read on 6 October 2026, unless a source below says otherwise. Plans change often, so confirm on their site before you buy.'

export const alternativePages: SeoPage[] = [
  // ───────────────────────────────────────── PinBoostr
  {
    path: 'pinboostr-alternative',
    kind: 'comparison',
    label: 'PinBoostr alternative',
    title: 'PinBoostr alternative for Pinterest scheduling',
    description: `GoPinKaro vs PinBoostr: prices, pin limits, accounts and how each makes pins, using PinBoostr's own pricing page. See where each one is the better fit.`,
    h1: 'A PinBoostr alternative for Pinterest scheduling',
    intro: `PinBoostr generates pins from your website with AI images and a "Growth Brain" queue you approve. GoPinKaro schedules the pins you review, with a template designer, video and carousel support, and plans that cover up to ${FACTS.accounts.business} Pinterest accounts. Free plans: ${free.pins} pins a month here against 5 pins a month there.`,
    updated: CHECKED,
    cta: { label: 'Try the Free plan on your own account', redirect: '/dashboard/accounts' },
    blocks: [
      h2('short', 'The short version'),
      ul(
        '**Choose GoPinKaro** if you want to review every pin before it publishes, run several Pinterest accounts, pay less at small volumes, or schedule video and carousel pins.',
        '**Choose PinBoostr** if you want pins created for you from your site with AI images, plus built-in keyword research, and you are happy to approve a queue rather than build it.',
      ),
      h2('numbers', 'The numbers side by side'),
      table(['', 'GoPinKaro', 'PinBoostr'], [
        ['Free plan', `${free.pins} pins a month, ${free.ai} AI writing generations`, '5 pins a month, 5 AI images, 5 AI-written pins; no keyword research'],
        ['Entry paid plan', `Starter $${starter.price} a month ($${starter.yearly} a year): ${starter.pins} pins`, 'Starter $19.99 a month ($199 a year): 15 pins a day, 150 AI pin images'],
        ['Next plan', `Pro $${FACTS.pro.price} a month: ${FACTS.pro.pins} pins`, 'Growth $39.99 a month ($399 a year): 30 pins a day, 350 AI pin images'],
        ['Pinterest accounts', acct, '1 on Starter, up to 2 on Growth'],
        ['Keyword research', 'Pinterest Trends growth data (not search volume)', '35 queries a month on Starter, 100 on Growth'],
        ['Creating pins', `You review drafted text; template designer (${FACTS.designer.templates} layouts); optional AI background`, 'Growth Brain generates pins from your site for you to approve; AI images'],
        ['Video and carousel pins', 'Yes', 'Not listed on the pricing page'],
        ['Publishing method', 'Official Pinterest API', 'Official Pinterest API'],
        ['Refunds', 'Cancel any time; keep access to the end of the period', '14-day refund guarantee'],
      ], NOTE),
      h2('how-pins-are-made', 'The real difference: who creates the pins'),
      p('PinBoostr leans on AI image generation: its plans count AI pin images by the month. That is the fastest way to fill a queue, and it suits sites with plenty of pages and little design time. The trade-off is that Pinterest now labels AI-modified images and lets people see fewer of them (see our [guide to Pinterest and AI-generated content](/guides/pinterest-ai-generated-content-rules)), so an all-AI feed carries a visibility risk that a feed of your own photos does not.'),
      p(`GoPinKaro starts from images you already have: the photos on your pages, files you upload, or pins you design from [templates](/pinterest-pin-maker). AI is used for titles, descriptions and, optionally, a background picture. If you want pins designed for you in bulk, the [website import](/website-to-pinterest-pins) can turn each imported page into a finished pin, using the page photo and title.`),
      h2('reviewer-notes', 'What a reviewer reported about PinBoostr'),
      p('A review on AppSumo (one review, so treat it as a single data point) praised the automation but wanted preview before credits are spent, a way to exclude tag and category pages from generation, a media library and manual pin creation. These are the kind of controls GoPinKaro is built around: nothing is scheduled until you confirm it, and each page import shows the pins first.'),
      h2('who-for', 'Who should pick which'),
      h3('Pick PinBoostr when'),
      ul('You have a large site and want pins generated with minimal involvement.', 'You value built-in keyword research queries.', 'You run one or two Pinterest accounts.'),
      h3('Pick GoPinKaro when'),
      ul(
        `You manage several accounts: ${acct}, all from one dashboard.`,
        'You want to approve every pin, or design pins from your own photos.',
        'You post video or carousel pins.',
        `You want a free plan big enough to test properly (${free.pins} pins a month).`,
      ),
      h2('plans', 'GoPinKaro plans'),
      plansTable(),
    ],
    faqs: [
      { q: 'Is GoPinKaro a PinBoostr alternative?', a: 'Yes, with a different approach. PinBoostr generates pins and a queue you approve; GoPinKaro schedules pins you review, offers a template designer and optional AI backgrounds, and supports several Pinterest accounts.' },
      { q: 'Which is cheaper, GoPinKaro or PinBoostr?', a: `At the entry level GoPinKaro Starter is $${starter.price} a month against $19.99 for PinBoostr Starter, and it includes ${starter.pins} pins a month. PinBoostr's plans are priced by pins a day and AI image allowances, so compare against the volume you really need.` },
      { q: 'Does GoPinKaro generate pins with AI?', a: 'Not automatically. It can draft titles and descriptions, design pins from templates, and create an AI background picture on request. Pins are scheduled only after you confirm them.' },
      { q: 'Can I switch from PinBoostr to GoPinKaro?', a: 'There is no automatic import. Connect your Pinterest account, import your site or upload your images, and schedule a first batch before you cancel the old plan.' },
    ],
    related: ['pinterest-scheduler-pricing', 'blogtopin-alternative', 'tailwind-alternative', 'safest-pinterest-scheduler'],
    sources: [SRC.pinboostrPricing, SRC.pinboostrReviews, SRC.pinterestAiLabels],
  },

  // ───────────────────────────────────────── Pin Generator
  {
    path: 'pin-generator-alternative',
    kind: 'comparison',
    label: 'Pin Generator alternative',
    title: 'Pin Generator alternative with review-first scheduling',
    description: 'GoPinKaro vs Pin Generator: bulk pin creation compared with a review-first scheduler, using what verified reviewers say about each approach.',
    h1: 'A Pin Generator alternative for bulk Pinterest scheduling',
    intro: 'Pin Generator is built for creating large batches of pins from templates and publishing them. GoPinKaro is built around scheduling pins you have reviewed, with a pacing check, several Pinterest accounts and video or carousel support. They overlap on bulk work and differ on how much you stay in the loop.',
    updated: CHECKED,
    cta: { label: 'Try bulk scheduling on the Free plan', redirect: '/dashboard/bulk' },
    blocks: [
      h2('short', 'The short version'),
      ul(
        '**Choose Pin Generator** if your main bottleneck is producing many pin designs quickly from templates and you accept some manual tweaking.',
        '**Choose GoPinKaro** if you already have images (or want to design a few from templates), and want a calm review step, a pacing warning and an assistant on top of the scheduling.',
      ),
      h2('reviews', 'What reviewers say about Pin Generator'),
      p('On AppSumo, Pin Generator holds 4.3 out of 5 across 93 reviews. Reviewers praise how quickly it produces batches and the template flexibility; one long-term user reported that pins made two years earlier still send meaningful traffic. The recurring complaints are the quality of AI title rewrites (weak or duplicated), pins that look less polished than Canva designs, a workflow that is not truly hands-off, unclear queue management, and difficulty tracking which URLs have already been used on big sites.'),
      callout('We do not quote Pin Generator\'s prices here because the figures we found disagreed between sources. Check its own pricing page before comparing costs.', 'A note on prices'),
      h2('where-we-differ', 'Where GoPinKaro differs'),
      ul(
        '**Duplicate protection.** Importing a page warns you if you already have pins linking to it, and a vector search flags near-duplicate titles and descriptions before you schedule.',
        `**Pacing check.** After a batch is scheduled you are told if a day goes above ${FACTS.dailySoftMax} pins or an image repeats within 7 days, because Pinterest discourages repeating the same pin.`,
        '**Review first.** Imported pages show their images and drafted copy for you to edit; nothing is scheduled until you confirm.',
        `**Accounts.** ${acct}.`,
        '**Formats.** Image, video and carousel pins from the same form.',
      ),
      h2('design', 'On design quality'),
      p(`If the main complaint about template pins is that they look generic, the honest answer is that GoPinKaro's [pin designer](/pinterest-pin-maker) is template-based too: ${FACTS.designer.templates} layouts and ${FACTS.designer.palettes} color sets. It is quick for text-led pins, not a replacement for a design tool. Many users design their best pins in Canva and bulk upload them, using GoPinKaro for the scheduling, pacing and analytics.`),
      h2('plans', 'GoPinKaro plans'),
      plansTable(),
    ],
    faqs: [
      { q: 'Is GoPinKaro a Pin Generator alternative?', a: 'It overlaps on bulk scheduling and importing from a website, but it puts more weight on reviewing pins and pacing them than on mass-producing designs.' },
      { q: 'Does GoPinKaro create pin designs in bulk?', a: `Yes, in a basic way. When you import a web page it can design each pin from the page photo and title using ${FACTS.designer.templates} template layouts. For custom artwork, design elsewhere and bulk upload.` },
      { q: 'Will GoPinKaro stop me posting duplicates?', a: 'It warns rather than blocks: you see a notice when a page is already pinned, when a draft is close to an existing pin, and after scheduling if a day is crowded or an image repeats.' },
    ],
    related: ['pinboostr-alternative', 'blogtopin-alternative', 'website-to-pinterest-pins', 'pinterest-bulk-scheduler'],
    sources: [SRC.pinGeneratorReviews],
  },

  // ───────────────────────────────────────── Buffer
  {
    path: 'buffer-alternative-for-pinterest',
    kind: 'comparison',
    label: 'Buffer alternative',
    title: 'Buffer alternative for Pinterest',
    description: `Buffer vs GoPinKaro for Pinterest: Buffer's $5 per channel pricing against flat Pinterest-only plans, with bulk scheduling, pacing and multi-account costs worked out.`,
    h1: 'A Buffer alternative for Pinterest scheduling',
    intro: `Buffer is a simple multi-network scheduler that publishes to Pinterest. At one account it is cheaper than GoPinKaro ($5 a month against $${starter.price}); at three or more Pinterest accounts, or when you want bulk scheduling, website import and Pinterest-specific checks, a Pinterest-only plan is the better value.`,
    updated: CHECKED,
    cta: { label: 'See how it handles several accounts', redirect: '/dashboard/accounts' },
    blocks: [
      h2('prices', 'What Buffer costs, from its own pricing page'),
      table(['Plan', 'Price', 'What it includes'], [
        ['Free', '$0', 'Up to 3 channels, 10 scheduled posts per channel, 100 ideas, 30-day analytics'],
        ['Essentials', '$5 per channel a month ($60 a year)', 'Unlimited scheduled posts, 14-day free trial'],
        ['Team', '$10 per channel a month ($120 a year)', 'Unlimited scheduled posts and users'],
      ], NOTE),
      p('Buffer supports both Pinterest business and personal accounts with automatic publishing. Per its pricing page, business accounts get basic analytics but not advanced analytics or community features. Channels above ten are discounted.'),
      h2('cost', 'What it costs as you add Pinterest accounts'),
      table(['Pinterest accounts', 'Buffer Essentials', 'GoPinKaro'], [
        ['1', '$5 a month', `$${starter.price} a month (Starter), or Free for ${free.pins} pins`],
        ['3', '$15 a month', `$${starter.price} a month (Starter includes ${FACTS.accounts.starter} accounts)`],
        ['10', '$50 a month', `$${FACTS.pro.price} a month (Pro includes ${FACTS.accounts.pro} accounts)`],
        ['50', 'Up to $250 a month before Buffer\'s volume discount past 10 channels', `$${FACTS.business.price} a month (Business includes ${FACTS.accounts.business} accounts)`],
      ], 'Buffer figures are Essentials at the standard per-channel rate. GoPinKaro plans also cap pins per month, shared across accounts: Starter 300, Pro 1,500, Business 6,000.'),
      h2('pinterest-features', 'Pinterest-specific differences'),
      p('Buffer is deliberately general: one composer for every network. In one independent test of Pinterest schedulers, reviewers noted that Buffer could not schedule a single pin to several boards in one go and that its browser extension did not keep a page\'s metadata; Buffer\'s own page lists basic Pinterest analytics, so check the current state on your account. GoPinKaro is Pinterest-only, which is why it can offer:'),
      ul(
        `Bulk scheduling of up to ${FACTS.bulkMax} pins from images or a CSV, and import from a page or a whole sitemap.`,
        'Titles and descriptions drafted by AI and checked against Pinterest\'s 100 and 800 character limits.',
        'A pacing check, duplicate warnings and best-time slots that start general and learn from an account\'s own results.',
        'Video and carousel pins, and a pin designer.',
      ),
      h2('choose', 'When Buffer is the right choice'),
      ul('You schedule to Pinterest and several other networks from one tool and Pinterest is a small part of it.', 'You post a handful of pins a month from one account.', 'You want the simplest possible interface.'),
      h2('plans', 'GoPinKaro plans'),
      plansTable(),
    ],
    faqs: [
      { q: 'Does Buffer support Pinterest?', a: 'Yes. Buffer supports Pinterest business and personal accounts with automatic publishing, and each Pinterest account counts as one channel for pricing.' },
      { q: 'Is Buffer cheaper than GoPinKaro for Pinterest?', a: `For one account, yes: Buffer Essentials is $5 a month per channel against $${starter.price} for GoPinKaro Starter. From three Pinterest accounts GoPinKaro Starter is cheaper, and at ten accounts Pro ($${FACTS.pro.price}) costs well under Buffer's $50.` },
      { q: 'Can Buffer bulk schedule Pinterest pins?', a: 'Buffer offers unlimited scheduled posts on paid plans; check its current bulk upload and Pinterest board options. GoPinKaro is built around bulk scheduling from images, CSV, pages and sitemaps.' },
      { q: 'Can I use both?', a: 'Yes. Some people keep Buffer for other networks and use a Pinterest-only tool for Pinterest, but do not schedule the same pins in both.' },
    ],
    related: ['pinterest-scheduler-pricing', 'cheapest-pinterest-scheduler', 'publer-alternative-for-pinterest', 'manage-multiple-pinterest-accounts'],
    sources: [SRC.bufferPricing, SRC.schedulerTests],
  },

  // ───────────────────────────────────────── Later
  {
    path: 'later-alternative-for-pinterest',
    kind: 'comparison',
    label: 'Later alternative',
    title: 'Later alternative for Pinterest scheduling',
    description: `Later vs GoPinKaro for Pinterest: Later's plan limits (30 posts per profile on Starter) against ${starter.pins} Pinterest pins a month from $${starter.price}, with the trade-offs.`,
    h1: 'A Later alternative for Pinterest scheduling',
    intro: `Later is a visual planner for several networks, strongest on Instagram. Its Starter plan includes 30 posts per profile each month; GoPinKaro Starter includes ${starter.pins} Pinterest pins a month for $${starter.price}. If Pinterest is your main channel, a Pinterest-only tool gives you far more pins per dollar.`,
    updated: CHECKED,
    cta: { label: 'Schedule a batch on the Free plan', redirect: '/dashboard/bulk' },
    blocks: [
      h2('prices', 'What Later offers, from its pricing page'),
      table(['Plan', 'Price (billed yearly)', 'Social sets and profiles', 'Posts per month'], [
        ['Starter', '$225 a year ($18.75 a month)', '1 social set (8 profiles)', '30 per profile'],
        ['Growth', '$450 a year ($37.50 a month)', '2 social sets (16 profiles)', '180 per profile'],
        ['Scale', '$990 a year ($82.50 a month)', '6 social sets (48 profiles)', 'Unlimited'],
      ], NOTE),
      p('All plans support Pinterest alongside Instagram, Facebook, Threads, TikTok, LinkedIn, YouTube and Snapchat. Starter includes 5 AI credits a month and 3 months of analytics; Growth adds multi-profile best times, trend forecasting and collaboration tools; Scale adds custom analytics and competitive benchmarking.'),
      h2('volume', 'Pins per dollar for a Pinterest-first account'),
      table(['', 'Later Starter', `GoPinKaro Starter`, `GoPinKaro Pro`], [
        ['Price a month', '$18.75 (billed yearly)', `$${starter.price} ($${(starter.yearly / 12).toFixed(2)} billed yearly)`, `$${FACTS.pro.price} ($${(FACTS.pro.yearly / 12).toFixed(2)} billed yearly)`],
        ['Pinterest pins a month', '30 per profile', `${starter.pins}`, `${FACTS.pro.pins}`],
        ['Pinterest accounts', 'Within 8 profiles', `${FACTS.accounts.starter}`, `${FACTS.accounts.pro}`],
        ['Bulk and CSV', 'Check Later for current options', `Up to ${FACTS.bulkMax} per batch`, `Up to ${FACTS.bulkMax} per batch`],
      ], 'Later and GoPinKaro count differently (posts per profile against pins per login), so these are indicative. One independent test also reported that Later could not schedule a single pin to several boards at once.'),
      h2('visual', 'Where Later is stronger'),
      ul('A polished visual calendar and media library across networks.', 'Instagram grid planning and link-in-bio tools.', 'Collaboration, social inbox and competitive benchmarking on higher plans.'),
      h2('where-us', 'Where GoPinKaro is stronger for Pinterest'),
      ul(
        `Volume: ${starter.pins} pins a month on a $${starter.price} plan, with ${FACTS.pro.pins} on Pro.`,
        'Import a page or a whole sitemap and get drafted pins to review.',
        'A pacing check and duplicate warnings that are specific to how Pinterest treats repeated pins.',
        'Per-account queues, calendars and analytics for up to 100 Pinterest accounts.',
      ),
      h2('plans', 'GoPinKaro plans'),
      plansTable(),
    ],
    faqs: [
      { q: 'Does Later support Pinterest?', a: 'Yes. Pinterest is supported on all Later plans, alongside Instagram, Facebook, Threads, TikTok, LinkedIn, YouTube and Snapchat.' },
      { q: 'How many posts does Later allow?', a: 'The Starter plan allows 30 posts per profile each month, Growth 180 per profile, and Scale is unlimited, according to its pricing page.' },
      { q: 'Is GoPinKaro better than Later for Pinterest?', a: 'If Pinterest is your main channel and you publish many pins, GoPinKaro gives you more pins per dollar and Pinterest-specific checks. If you mainly plan Instagram and add a few pins, Later may suit you better.' },
    ],
    related: ['buffer-alternative-for-pinterest', 'planoly-alternative-for-pinterest', 'cheapest-pinterest-scheduler', 'pinterest-scheduler-pricing'],
    sources: [SRC.laterPricing, SRC.schedulerTests],
  },

  // ───────────────────────────────────────── Publer
  {
    path: 'publer-alternative-for-pinterest',
    kind: 'comparison',
    label: 'Publer alternative',
    title: 'Publer alternative for Pinterest',
    description: `Publer vs GoPinKaro for Pinterest: per-account pricing against flat plans for 1, 3 and 10 accounts, plus bulk scheduling, pacing and the trade-offs.`,
    h1: 'A Publer alternative for Pinterest scheduling',
    intro: `Publer is a low-cost multi-network scheduler that charges per social account. For a single Pinterest account it is cheaper than GoPinKaro; as you add accounts, flat Pinterest-only plans overtake it, and GoPinKaro adds website import, a pacing check and video or carousel pins.`,
    updated: CHECKED,
    cta: { label: 'Compare with a Free plan trial', redirect: '/dashboard/accounts' },
    blocks: [
      h2('prices', 'What Publer costs'),
      p('Publer\'s own pricing page could not be read by our automated check, so these figures come from published roundups and may have changed: the Professional plan is about $5 a month ($4 billed yearly) per social account, and Business about $10 a month ($8 billed yearly) per account, both with unlimited scheduling. Confirm on publer.com before deciding.'),
      table(['Pinterest accounts', 'Publer Professional (about $4 to $5 each)', 'GoPinKaro'], [
        ['1', '$4 to $5 a month', `$${starter.price} a month, or Free (${free.pins} pins)`],
        ['3', '$12 to $15 a month', `$${starter.price} a month (Starter)`],
        ['10', '$40 to $50 a month', `$${FACTS.pro.price} a month (Pro)`],
        ['100', '$400 to $500 a month', `$${FACTS.business.price} a month (Business)`],
      ], 'Publer figures are estimates from roundups. GoPinKaro plans cap pins per month, shared across accounts.'),
      h2('features', 'Feature comparison'),
      table(['', 'GoPinKaro', 'Publer'], [
        ['Networks', 'Pinterest only', 'Several networks'],
        ['Bulk scheduling', `Images or CSV, up to ${FACTS.bulkMax} per batch`, 'Bulk upload and CSV import, per roundups'],
        ['Website to pins', 'Page or whole sitemap, with review', 'Not listed'],
        ['Pinterest pacing check', `Warns above ${FACTS.dailySoftMax} a day and on repeated images`, 'Check its current features'],
        ['Multi-account pricing', 'Flat plans by pin volume', 'Per account'],
      ]),
      h2('choose', 'Who should pick which'),
      ul(
        '**Publer** if you want one low-cost tool for several networks, or you run one or two Pinterest accounts and mostly need basic scheduling.',
        `**GoPinKaro** if you run three or more Pinterest accounts, want Pinterest-specific tooling, or want to turn pages and sitemaps into drafted pins.`,
      ),
      h2('plans', 'GoPinKaro plans'),
      plansTable(),
    ],
    faqs: [
      { q: 'Is Publer good for Pinterest?', a: 'Publer supports Pinterest alongside other networks and is inexpensive per account. It is a general scheduler, so Pinterest-specific tools such as website import and a Pinterest pacing check are not its focus.' },
      { q: 'Is GoPinKaro cheaper than Publer?', a: `Not for a single account, where Publer is roughly $4 to $5 a month. From about three Pinterest accounts upward, a flat GoPinKaro plan costs less in total.` },
      { q: 'Where do these Publer prices come from?', a: 'Third-party roundups, because Publer\'s own pricing page could not be read automatically. They can be out of date, so check publer.com.' },
    ],
    related: ['buffer-alternative-for-pinterest', 'cheapest-pinterest-scheduler', 'manage-multiple-pinterest-accounts', 'pinterest-scheduler-pricing'],
    sources: [SRC.publerRoundup, SRC.publerRoundup2],
  },

  // ───────────────────────────────────────── Planoly
  {
    path: 'planoly-alternative-for-pinterest',
    kind: 'comparison',
    label: 'Planoly alternative',
    title: 'Planoly alternative for Pinterest',
    description: `Planoly vs GoPinKaro for Pinterest: Planoly's $14 to $47 social-set plans against Pinterest-only plans from $${starter.price}, with bulk, pacing and account limits compared.`,
    h1: 'A Planoly alternative for Pinterest scheduling',
    intro: `Planoly is a visual planner built around Instagram grids that also schedules to Pinterest. If you plan feeds visually across networks it fits well; if you want to publish many Pinterest pins with checks for pacing and duplicates, GoPinKaro is built for that, from $${starter.price} a month.`,
    updated: CHECKED,
    cta: { label: 'Try a Pinterest-first workflow', redirect: '/dashboard/schedule' },
    blocks: [
      h2('prices', 'What Planoly costs, from its pricing page'),
      table(['Plan', 'Monthly price', 'Social sets', 'Users'], [
        ['Starter', '$14', '1', '1'],
        ['Growth', '$24', '2', '2'],
        ['Pro', '$47', '6', '6'],
      ], `${NOTE} Planoly says annual billing saves up to 15%; extra social sets cost $10 a month on Growth and $8 on Pro, extra users $5 and $3. There is a free mobile plan with 10 uploads a month and a 14-day trial.`),
      p('Every plan includes unlimited uploads, a visual calendar across Instagram, TikTok, LinkedIn, Facebook, YouTube, Threads and Pinterest, grid planning, a media library, auto-post scheduling and AI content ideas.'),
      h2('compare', 'Planoly and GoPinKaro for Pinterest'),
      table(['', 'GoPinKaro', 'Planoly'], [
        ['Focus', 'Pinterest only', 'Visual planning across networks, Instagram first'],
        ['Entry paid plan', `$${starter.price} a month`, '$14 a month'],
        ['Pins or uploads', `${starter.pins} Pinterest pins a month on Starter`, 'Unlimited uploads'],
        ['Pinterest accounts', acct, 'Within a social set; extra sets cost extra'],
        ['Website or sitemap import', 'Yes', 'Not listed'],
        ['Bulk scheduling', `Up to ${FACTS.bulkMax} per batch`, 'Check Planoly for current options'],
        ['Pinterest pacing and duplicate checks', 'Yes', 'Not listed'],
      ], 'One independent test noted that Planoly expects you to bring finished graphics and described its Pinterest analytics as limited.'),
      h2('choose', 'Choose Planoly if'),
      ul('You plan a visual feed across Instagram and Pinterest together.', 'You want link-in-bio and a storefront in the same tool.', 'You make your pins elsewhere and mostly need a calendar.'),
      h2('choose-us', 'Choose GoPinKaro if'),
      ul(
        'Pinterest is your main traffic source and you publish pins in volume.',
        'You want pages and sitemaps turned into drafted pins, with duplicate checks.',
        `You manage more than a few Pinterest accounts (${acct}).`,
      ),
      h2('plans', 'GoPinKaro plans'),
      plansTable(),
    ],
    faqs: [
      { q: 'Does Planoly work with Pinterest?', a: 'Yes. Planoly supports Pinterest alongside Instagram, TikTok, LinkedIn, Facebook, YouTube and Threads in its calendar.' },
      { q: 'Is there a free Planoly plan?', a: 'Planoly lists a free mobile plan with 10 uploads a month and a 14-day trial for paid plans.' },
      { q: 'Is GoPinKaro a good Planoly alternative?', a: 'For Pinterest-heavy work, yes. For Instagram grid planning and link-in-bio, Planoly is the more suitable tool.' },
    ],
    related: ['later-alternative-for-pinterest', 'buffer-alternative-for-pinterest', 'cheapest-pinterest-scheduler', 'pinterest-bulk-scheduler'],
    sources: [SRC.planolyPricing, SRC.schedulerTests],
  },

  // ───────────────────────────────────────── Hootsuite
  {
    path: 'hootsuite-alternative-for-pinterest',
    kind: 'comparison',
    label: 'Hootsuite alternative',
    title: 'Hootsuite alternative for Pinterest',
    description: `Hootsuite from $99 a month vs GoPinKaro from $${starter.price}: what you give up and gain when Pinterest is your main channel, with prices from Hootsuite's own plans page.`,
    h1: 'A Hootsuite alternative for Pinterest scheduling',
    intro: `Hootsuite is an enterprise social suite starting at $99 a month. For teams that need approvals, a unified inbox and brand monitoring it is a serious option. If your goal is to publish Pinterest pins steadily, a Pinterest-only plan costs a fraction of that, from $${starter.price} a month.`,
    updated: CHECKED,
    cta: { label: 'Start with a Pinterest-only plan', redirect: '/dashboard' },
    blocks: [
      h2('prices', 'What Hootsuite costs, from its plans page'),
      table(['Plan', 'Price (annual billing)', 'Social accounts', 'Notable features'], [
        ['Standard', '$99 a month', 'Up to 10', 'Unlimited scheduling, AI content, unified inbox, brand monitoring, competitive benchmarking'],
        ['Professional', '$199 a month', 'Unlimited', 'Inbox automations, trend forecasting, custom reports, link tracking'],
        ['Advanced', '$399 a month', 'Unlimited', 'Approval workflows, message assignment, team productivity tracking'],
        ['Enterprise', 'Custom', 'Custom', 'SSO, 13-month listening history, Salesforce integration'],
      ], `${NOTE} The plans page does not mention Pinterest specifically, and trial accounts have post limits and no bulk scheduling.`),
      h2('pinterest', 'Hootsuite for Pinterest in practice'),
      p('In one independent test of Pinterest schedulers, Hootsuite scored 2.1 out of 5: reviewers found it clunky for Pinterest, without a field for pin titles or Pinterest analytics, and the most expensive tool tested. That is one reviewer\'s experience at one point in time, so try the current product before deciding.'),
      h2('compare', 'Side by side'),
      table(['', 'GoPinKaro', 'Hootsuite'], [
        ['Price to start', `$${starter.price} a month (Free plan available)`, '$99 a month'],
        ['Focus', 'Pinterest only', 'Every major network, plus listening and inbox'],
        ['Pinterest titles, descriptions, alt text', 'Built in, with limits checked and AI drafts', 'Check current Pinterest options'],
        ['Bulk Pinterest scheduling', `Up to ${FACTS.bulkMax} per batch, plus CSV and sitemap import`, 'Bulk scheduling (not available during its trial)'],
        ['Approval workflows and team seats', 'Not available', 'Advanced plan'],
        ['Pinterest accounts', acct, 'Up to 10 on Standard'],
      ]),
      h2('choose', 'When to stay with or choose Hootsuite'),
      ul('Your team needs approval workflows, assignment or SSO.', 'You manage reputation, inbox and listening across many networks.', 'Pinterest is one channel among many and the budget exists.'),
      callout('GoPinKaro has no team seats or approval workflow today. If you need several people with different permissions, Hootsuite or Metricool\'s Advanced plan fits better.', 'An honest limit'),
      h2('plans', 'GoPinKaro plans'),
      plansTable(),
    ],
    faqs: [
      { q: 'Does Hootsuite support Pinterest?', a: 'Hootsuite supports Pinterest, but its plans page does not list Pinterest features, and one independent test found its Pinterest support weak. Check the current product.' },
      { q: 'How much does Hootsuite cost?', a: 'According to its plans page: Standard $99 a month, Professional $199, Advanced $399, with Enterprise on request, all with annual billing.' },
      { q: 'What is a cheaper alternative to Hootsuite for Pinterest?', a: `A Pinterest-only scheduler. GoPinKaro is free for ${free.pins} pins a month and $${starter.price} a month for ${starter.pins}.` },
    ],
    related: ['metricool-alternative-for-pinterest', 'buffer-alternative-for-pinterest', 'pinterest-scheduler-pricing', 'use-cases/agencies'],
    sources: [SRC.hootsuitePlans, SRC.schedulerTests],
  },

  // ───────────────────────────────────────── Metricool
  {
    path: 'metricool-alternative-for-pinterest',
    kind: 'comparison',
    label: 'Metricool alternative',
    title: 'Metricool alternative for Pinterest',
    description: `Metricool's free plan (1 brand, 20 posts) and paid tiers against GoPinKaro for Pinterest, with official limits, multi-brand costs and where Metricool is stronger.`,
    h1: 'A Metricool alternative for Pinterest scheduling',
    intro: `Metricool pairs scheduling with analytics and competitor tracking across networks, with a free plan of one brand and 20 posts a month. GoPinKaro is Pinterest-only with a free plan of ${free.pins} pins a month. They suit different jobs: Metricool for broad analytics and reporting, GoPinKaro for publishing pins in volume.`,
    updated: CHECKED,
    cta: { label: 'Try the Free plan alongside Metricool', redirect: '/dashboard' },
    blocks: [
      h2('prices', 'What Metricool offers, from its pricing page'),
      table(['Plan', 'Monthly price', 'Brands', 'Scheduled posts', 'Highlights'], [
        ['Free', '$0', '1', '20 a month', 'Pinterest supported, 30-day analytics, AI assistant, 5 competitor profiles'],
        ['Starter', 'About $20 to $36 (tiered)', '5 to 10', 'Unlimited*', '100 competitor profiles, reports, multiple link-in-bio'],
        ['Advanced', 'About $53 to $210 (tiered)', '15 to 50', 'Unlimited*', 'Team management, approvals, report templates, Data Studio connector, API'],
        ['Custom', 'On request', 'Custom', 'Unlimited*', 'White label, dedicated account manager'],
      ], `${NOTE} *Subject to Metricool's fair use policy.`),
      h2('compare', 'Metricool and GoPinKaro for Pinterest'),
      table(['', 'GoPinKaro', 'Metricool'], [
        ['Free plan', `${free.pins} pins a month, 1 account`, '20 posts a month, 1 brand'],
        ['Paid pricing model', 'Flat plans by pins a month and accounts', 'Tiered by number of brands'],
        ['Analytics', 'Account and pin metrics from Pinterest, 7 to 90 days of history by plan', 'Cross-network analytics, competitor analysis, reports'],
        ['Team approvals and white label', 'Not available', 'Advanced and Custom plans'],
        ['Website or sitemap to pins', 'Yes', 'Not listed'],
        ['Pinterest pacing and duplicate checks', 'Yes', 'Not listed'],
        ['Pin designer and video or carousel', 'Yes', 'Check Metricool'],
      ]),
      h2('choose', 'Pick Metricool when'),
      ul('You need analytics and competitor tracking across several networks.', 'You produce reports for clients or need white labelling.', 'You need team members with approvals.'),
      h2('choose-us', 'Pick GoPinKaro when'),
      ul(
        `You publish ${starter.pins}+ pins a month and want bulk, CSV, page and sitemap import.`,
        'You want Pinterest-specific pacing, duplicate and best-time tools.',
        `You manage many Pinterest accounts on one flat plan (${acct}).`,
      ),
      p('They also work together: some agencies report with Metricool and publish Pinterest with a Pinterest-only tool, as long as the same pins are not scheduled twice.'),
      h2('plans', 'GoPinKaro plans'),
      plansTable(),
    ],
    faqs: [
      { q: 'Does Metricool have a free plan for Pinterest?', a: 'Yes. Metricool\'s free plan includes 1 brand and 20 scheduled posts a month, and Pinterest is supported.' },
      { q: 'Is GoPinKaro a Metricool alternative?', a: 'For Pinterest publishing, yes. For multi-network analytics, competitor tracking and white-label reports, Metricool offers more.' },
      { q: 'Which is better for agencies?', a: 'It depends on the job. Metricool\'s Advanced plan adds team management and approvals; GoPinKaro handles up to 100 Pinterest accounts with per-account queues but has no team seats today.' },
    ],
    related: ['hootsuite-alternative-for-pinterest', 'use-cases/agencies', 'manage-multiple-pinterest-accounts', 'cheapest-pinterest-scheduler'],
    sources: [SRC.metricoolPricing, SRC.metricoolMulti],
  },

  // ───────────────────────────────────────── cheapest
  {
    path: 'cheapest-pinterest-scheduler',
    kind: 'comparison',
    label: 'Cheapest Pinterest scheduler',
    title: 'Cheapest Pinterest scheduler (2026 prices)',
    description: 'The cheapest way to schedule Pinterest pins in 2026, worked out for 1, 3 and 10 accounts from official prices: free options, per-channel tools and flat plans.',
    h1: 'The cheapest Pinterest scheduler, worked out for your setup',
    intro: `The cheapest option depends on how many Pinterest accounts you run. For one account with a few pins a week it is free (Pinterest's own scheduler, or GoPinKaro, Metricool and Buffer free plans). For one account at volume, per-channel tools such as Buffer are cheapest. From three accounts upward, a flat plan like GoPinKaro Starter ($${starter.price}) or Pro ($${FACTS.pro.price}) costs less.`,
    updated: CHECKED,
    cta: { label: 'Start on the free plan', redirect: '/dashboard' },
    blocks: [
      h2('free', 'Free options'),
      table(['Tool', 'What the free option gives you', 'Main limit'], [
        ["Pinterest's own scheduler", 'Schedule pins from Pinterest itself', 'One at a time, up to 30 days ahead, 10 scheduled at once'],
        ['GoPinKaro Free', `${free.pins} pins a month, website import, AI drafts, pin designer`, `1 account; up to ${FACTS.freeBatchMax} pins per batch`],
        ['Metricool Free', '20 scheduled posts a month, Pinterest supported', '1 brand'],
        ['Buffer Free', '3 channels, 10 scheduled posts each', '10 posts per channel'],
        ['Planoly (mobile)', 'Free mobile plan', '10 uploads a month'],
      ], 'Limits from each vendor\'s own pages and the sources below, October 2026.'),
      h2('paid', 'Paid plans, cheapest first'),
      table(['Tool and plan', 'Price a month', 'What the price covers'], [
        ['Publer Professional', 'About $4 to $5 per account', 'Unlimited scheduling per account (roundups)'],
        ['Buffer Essentials', '$5 per channel ($60 a year)', 'Unlimited scheduled posts per channel'],
        [`GoPinKaro Starter`, `$${(starter.yearly / 12).toFixed(2)} billed yearly ($${starter.price} monthly)`, `${starter.pins} pins a month across ${FACTS.accounts.starter} accounts`],
        ['Planoly Starter', '$14 (annual saves up to 15%)', '1 social set, 1 user'],
        [`GoPinKaro Pro`, `$${(FACTS.pro.yearly / 12).toFixed(2)} billed yearly ($${FACTS.pro.price} monthly)`, `${FACTS.pro.pins} pins a month across ${FACTS.accounts.pro} accounts`],
        ['PinBoostr Starter', '$16.58 billed yearly ($19.99 monthly)', '15 pins a day, 1 Pinterest account'],
        ['Tailwind (scheduling and creation)', '$17.99 billed yearly ($29.99 monthly)', '300 credits a month, per Pinterest account'],
        ['Later Starter', '$18.75 billed yearly', '30 posts per profile, 1 social set'],
        ['BlogToPin Starter', '$24.92 billed yearly ($25 monthly)', '1,000 pins a month, unlimited accounts'],
        ['Hootsuite Standard', '$99 billed yearly', 'Up to 10 social accounts'],
      ], 'Ordered by the lowest price each vendor lists (usually billed yearly). Per-account tools (Publer, Buffer) are shown per account. GoPinKaro plans cap pins per month, shared across accounts. Sources below; confirm before buying.'),
      h2('scenarios', 'What it costs for common setups'),
      table(['Setup', 'Cheapest', 'Then'], [
        ['1 account, about 20 pins a month', 'Free: GoPinKaro Free or Pinterest\'s scheduler', 'Metricool Free, Buffer Free'],
        ['1 account, about 100 pins a month', 'Buffer Essentials or Publer at about $5', `GoPinKaro Starter at $${starter.price}, which adds bulk, import and Pinterest checks`],
        ['3 accounts, about 300 pins a month', `GoPinKaro Starter at $${starter.price} (about $15 on Buffer or Publer)`, 'Later and Planoly price by social set, so check how many sets three accounts need'],
        ['10 accounts, about 1,000 pins a month', `GoPinKaro Pro at $${FACTS.pro.price} (about $40 to $50 on Buffer or Publer)`, 'BlogToPin at $25 for 1,000 pins'],
      ], 'Totals are the plan prices multiplied by accounts. They do not include optional add-ons.'),
      h2('traps', 'Cost traps to check before you pay'),
      ul(
        '**Credit pools.** Tailwind\'s plans include a monthly credit allowance shared by AI and creation features; extra credits cost $10 per 100.',
        '**Per account.** Tailwind, Buffer and Publer price each Pinterest account separately, so multiply.',
        '**Posts per profile.** Later\'s Starter allows 30 posts per profile a month.',
        '**Annual versus monthly.** Tailwind is $17.99 billed yearly but $29.99 billed monthly.',
        '**Refunds.** PinBoostr offers a 14-day refund guarantee; check the policy of any tool that spends AI credits.',
      ),
      h2('plans', 'GoPinKaro plans'),
      plansTable(),
    ],
    faqs: [
      { q: 'What is the cheapest Pinterest scheduler?', a: `Pinterest's built-in scheduler is free but limited to one pin at a time, 10 scheduled at once. Beyond that, free plans from GoPinKaro (${free.pins} pins a month), Metricool (20) and Buffer (10 per channel) cover light use, and Buffer or Publer cost about $5 a month for one account.` },
      { q: 'What is the cheapest for several Pinterest accounts?', a: `A flat plan: GoPinKaro Starter is $${starter.price} for up to ${FACTS.accounts.starter} accounts and Pro is $${FACTS.pro.price} for up to ${FACTS.accounts.pro}, against roughly $5 per account on Buffer or Publer.` },
      { q: 'Is a free Pinterest scheduler safe?', a: 'Safe depends on how it publishes, not its price. Use tools that connect through Pinterest\'s official sign-in and never ask for your Pinterest password. See our guide to safe Pinterest schedulers.' },
      { q: 'Are these prices current?', a: 'They were read from vendor pages on 6 October 2026; Publer figures come from roundups. Vendors change prices often.' },
    ],
    related: ['pinterest-scheduler-pricing', 'free-pinterest-scheduler', 'safest-pinterest-scheduler', 'buffer-alternative-for-pinterest'],
    sources: [SRC.tailwindPricing, SRC.blogtopinPricing, SRC.bufferPricing, SRC.laterPricing, SRC.planolyPricing, SRC.hootsuitePlans, SRC.metricoolPricing, SRC.pinboostrPricing, SRC.publerRoundup, SRC.nativeLimits],
  },

  // ───────────────────────────────────────── safest
  {
    path: 'safest-pinterest-scheduler',
    kind: 'comparison',
    label: 'Safest Pinterest scheduler',
    title: 'How to choose a safe Pinterest scheduler',
    description: 'A checklist for picking a Pinterest scheduler that will not endanger your account: official API sign-in, no password sharing, sensible pacing, and what to avoid.',
    h1: 'The safest Pinterest scheduler: what to check before you connect',
    intro: 'A Pinterest scheduler is safe when it publishes through Pinterest\'s official API after you approve it on Pinterest, never asks for your password, and helps you avoid repeating pins. The price does not make a tool safe or unsafe. Use this checklist on any tool, including ours.',
    updated: CHECKED,
    cta: { label: 'See how GoPinKaro connects', redirect: '/dashboard/accounts' },
    blocks: [
      h2('checklist', 'The checklist'),
      table(['Check', 'Safe', 'Walk away if'], [
        ['How it signs in', 'Sends you to Pinterest to approve access (OAuth)', 'Asks for your Pinterest email and password, or a session cookie'],
        ['How it publishes', 'Uses the official Pinterest API', 'Uses a browser bot that clicks as you'],
        ['What it asks for', 'Boards, pins and basic profile access', 'Wants to follow, save or comment for you'],
        ['Pace', 'Spreads pins out and warns about crowded days', 'Promotes posting dozens of pins a day or mass-saving'],
        ['Duplicates', 'Warns about repeated pins and images', 'Encourages posting the same pin to many boards at once'],
        ['Revoking', 'You can remove access from Pinterest settings at any time', 'No clear way to disconnect or delete your data'],
        ['Tokens', 'Stored encrypted, never shown in the browser', 'Vague about how access is stored'],
      ]),
      h2('history', 'Why the sign-in method matters: Board Booster'),
      p('Board Booster, a popular scheduler, shut down in June 2018 after four years. It asked users for their Pinterest username and password rather than using Pinterest\'s own authorization, operated outside the official API, and used automation behavior Pinterest called spammy. Pinterest then named Tailwind as an approved alternative. The lesson is simple: if a tool logs in as you, your account is at risk when it is shut down.'),
      h2('spam', 'What Pinterest treats as spam'),
      p('Publishing on a schedule is not prohibited; Pinterest maintains an API so tools can do it. What gets accounts into trouble is bulk, inauthentic activity: mass-saving, automated following, scripted engagement, and repeating the same or similar pins. Commonly repeated guidance is to keep to roughly 5 to 15 new pins a day and to space identical images several days apart across boards. These numbers are community guidance, not a published Pinterest limit.'),
      h2('how-we-do', 'How GoPinKaro measures up'),
      ul(
        'Sign-in is Pinterest\'s own OAuth page. GoPinKaro never sees your Pinterest password.',
        'Pins are published through the official Pinterest API; there is no browser automation.',
        'Access tokens are stored encrypted and are never sent to your browser.',
        `After you schedule, a pacing check flags any day above ${FACTS.dailySoftMax} pins and any image reused within 7 days. It warns rather than blocks, so the decision stays yours.`,
        'Disconnect an account from the Accounts page, or revoke access in your Pinterest settings.',
        'GoPinKaro cannot follow, save or comment on your behalf.',
      ),
      callout('No scheduler can guarantee that Pinterest will never limit an account. Pinterest decides what counts as spam. Publish original, varied pins at a steady pace, whatever tool you use.', 'An honest limit'),
      h2('after', 'If you are already using a risky tool'),
      riskyToolSteps(),
    ],
    faqs: [
      { q: 'Is it safe to use a Pinterest scheduler?', a: 'Yes, when the tool connects through Pinterest\'s official sign-in and API and you keep a steady, varied pace. Tools that ask for your password or automate a browser put your account at risk.' },
      { q: 'Does GoPinKaro ask for my Pinterest password?', a: 'No. You approve access on Pinterest\'s own page, and GoPinKaro receives a token that you can revoke at any time in your Pinterest settings.' },
      { q: 'Can scheduling pins get my account banned?', a: 'Scheduling alone does not. Repeating the same pins, posting at an unnatural pace or using bots that mass-save or follow can. GoPinKaro warns when a day is crowded or an image repeats.' },
      { q: 'How many pins a day is safe?', a: 'Pinterest publishes no official number. Commonly repeated guidance is about 5 to 15 new pins a day, and spacing identical images several days apart.' },
    ],
    related: ['guides/is-pinterest-scheduling-safe', 'cheapest-pinterest-scheduler', 'guides/how-often-to-pin-on-pinterest', 'pinterest-automation-tool'],
    sources: [SRC.boardBooster, SRC.automationGuide, SRC.nativeLimits],
  },
]

/** Steps for someone already on a risky tool (a function so the list reads clearly above). */
function riskyToolSteps() {
  return ul(
    'Disconnect the tool and remove its access in your Pinterest account settings.',
    'Change your Pinterest password if you ever gave the tool your credentials.',
    'Pause scheduling for a week, then resume at a slower pace with fresh pins rather than repeats.',
  )
}
