import { PLANS } from '@shared/plans'
import { FACTS, CHECKED, SRC } from './facts'
import { callout, h2, h3, p, plansTable, table, ul, type SeoPage } from './types'

const { free, starter } = FACTS

/** BlogToPin's published tiers (blogtopin.com/pricing, checked October 2026). */
const BLOGTOPIN = [
  { name: 'Starter', price: 25, yearly: 299, pins: 1000 },
  { name: 'Agency', price: 50, yearly: 599, pins: 10000 },
  { name: 'Enterprise', price: 125, yearly: 1499, pins: 30000 },
]
const perPin = (price: number, pins: number) => `$${(price / pins).toFixed(price / pins < 0.01 ? 4 : 3)}`

export const comparePages: SeoPage[] = [
  // ───────────────────────────────────────────────── /best-pinterest-tools
  {
    path: 'best-pinterest-tools',
    kind: 'comparison',
    label: 'Best Pinterest tools',
    title: "Best Pinterest tools by job (2026)",
    description: 'The Pinterest tools worth knowing, grouped by job: scheduling, design, keyword research and free options, with honest notes on where each one fits.',
    h1: 'The best Pinterest tools, by what you need to get done',
    intro: 'No single Pinterest tool does everything well. Most accounts end up with one scheduler, one design tool and one source of keyword data. This guide groups the tools people actually use by job, says what each is good at, and is clear about where GoPinKaro fits and where it does not.',
    updated: CHECKED,
    blocks: [
      h2('how-to-choose', 'How to choose'),
      p('Start from the job, not the brand. If your bottleneck is getting pins published on a steady schedule, you need a scheduler. If it is making attractive images, you need a design tool. If you are unsure what to pin about, you need keyword research. Many tools overlap, so start with the free tier of the one that matches your biggest bottleneck.'),
      table(['Job', 'Tools to look at'], [
        ['Scheduling and automation', 'GoPinKaro, Tailwind, Pinterest built-in scheduler, BlogToPin, Metricool'],
        ['Designing pins', 'GoPinKaro pin designer, Canva, Adobe Express'],
        ['Keyword research', 'Pinterest Trends, PinClicks, Pin Inspector, GoPinKaro keyword tool'],
        ['Free options', "Pinterest's scheduler, Pinterest Trends, GoPinKaro Free, Canva Free"],
      ]),
      h2('scheduling', 'Scheduling and automation'),
      h3('GoPinKaro'),
      p(`A Pinterest-only scheduler focused on bulk work. You can bulk schedule up to ${FACTS.bulkMax} pins from images or a CSV, turn web pages or a sitemap into drafted pins, publish at best-time slots in your timezone, and run it all from an AI assistant that confirms before it changes anything. Free plan: ${free.pins} pins a month. Paid plans from $${starter.price} a month. **Limits:** Pinterest only (no Instagram or Facebook), up to ${FACTS.accounts.business} Pinterest accounts per login, and a template-based pin designer rather than a full design studio.`),
      h3('Tailwind'),
      p('A long-established scheduler built around Pinterest, with a smart schedule feature, bulk creation tools, AI writing and pin design features, and it also covers other networks such as Instagram. It is a good choice if you want design and scheduling in one product. It is typically priced by plan tier with a set number of accounts, so compare it with GoPinKaro on its current pricing page.'),
      h3("Pinterest's built-in scheduler"),
      p("Free and built into Pinterest. You can schedule a pin up to 30 days ahead, one pin at a time, with up to 10 pins scheduled at once. Ideal for a light posting rhythm, and a sensible first step before paying for anything."),
      h3('BlogToPin and other website-to-pin tools'),
      p('Some tools focus on turning a website into pins automatically, including generating images. GoPinKaro takes a similar website-to-pins approach but uses the images already on your pages and keeps a review step before anything is scheduled.'),
      h3('Metricool'),
      p('A multi-network social planner with a free tier that can schedule Pinterest pins and show basic analytics. Useful if Pinterest is one channel among several.'),
      h2('design', 'Designing pins'),
      h3('GoPinKaro pin designer'),
      p(`A simple template designer inside GoPinKaro: ${FACTS.designer.templates} layouts, ${FACTS.designer.palettes} color sets, an optional photo, and a ${FACTS.designer.width} x ${FACTS.designer.height} image you can download or schedule in one click. It is quick for text-led pins; it is not a full design studio.`),
      h3('Canva'),
      p('The most widely used design tool for pins, with vertical templates and batch features. It does not replace a scheduler, but it pairs well with one: design in Canva, export images, then bulk upload them to GoPinKaro.'),
      h2('research', 'Keyword research'),
      h3('Pinterest Trends'),
      p('Free and first-party. Shows what is rising on Pinterest. GoPinKaro surfaces the same trend data inside its keyword tool.'),
      h3('PinClicks and Pin Inspector'),
      p('Dedicated research tools. PinClicks lets you explore Pinterest keywords with search volume data and pin scores for evaluating competitors, and Pin Inspector helps you see which pins and keywords perform. They are paid, and they go deeper on research than a scheduler does.'),
      h2('where-us', 'Where GoPinKaro is the right choice'),
      ul(
        'You publish new pages or products regularly and want pins to follow automatically.',
        'You want to bulk schedule from a spreadsheet or a folder of images.',
        `You want Pinterest-only pricing for one account or for many (up to ${FACTS.accounts.business}).`,
        'You want to run the work from a chat assistant with confirmation before changes.',
      ),
      h2('where-not', 'Where it is not'),
      ul(
        `You need more than ${FACTS.accounts.business} Pinterest accounts.`,
        'You also publish to Instagram, Facebook or other networks from the same tool.',
        `You want pin images generated for you automatically. The pin designer is template-based and you write the text.`,
        'You need deep competitor and keyword volume research.',
      ),
      h2('pricing', 'GoPinKaro plans'),
      plansTable(),
      callout('Facts about other tools are summarised from their public descriptions and press as of October 2026 and may change. Check each product\'s own site for current features and prices.', 'About this comparison'),
    ],
    faqs: [
      { q: 'What is the best Pinterest tool?', a: 'It depends on the job. For scheduling and automation, consider GoPinKaro, Tailwind or Pinterest\'s own scheduler. For design, Canva. For keyword research, Pinterest Trends, PinClicks or Pin Inspector.' },
      { q: 'What is the best Pinterest tool for free?', a: `Pinterest's built-in scheduler and Pinterest Trends are free. GoPinKaro's free plan includes ${free.pins} pins a month, and Canva has a free tier for design.` },
      { q: 'What is the best Pinterest tool for business?', a: 'Businesses that publish many pages or products usually need bulk scheduling and a repeatable workflow. GoPinKaro, Tailwind and similar schedulers are built for that, plus a design tool for images.' },
      { q: 'Do I need more than one Pinterest tool?', a: 'Usually yes. One scheduler plus one design tool covers most needs, and Pinterest Trends gives you free keyword ideas.' },
    ],
    related: ['tailwind-alternative', 'free-pinterest-scheduler', 'pinterest-keyword-tool', 'pinterest-automation-tool'],
    sources: [SRC.nativeLimits, SRC.pinterestCommunity],
  },

  // ───────────────────────────────────────────────── /tailwind-alternative
  {
    path: 'tailwind-alternative',
    kind: 'comparison',
    label: 'Tailwind alternative',
    title: "Tailwind alternative for Pinterest",
    description: 'Looking for a Tailwind alternative? See where GoPinKaro differs (Pinterest-only, bulk, website-to-pins, free plan) and where Tailwind fits better.',
    h1: 'A Tailwind alternative for Pinterest scheduling',
    intro: `Tailwind is a well-known Pinterest scheduler. GoPinKaro is a lighter, Pinterest-only alternative focused on bulk scheduling and turning web pages into pins, with a free plan (${free.pins} pins a month) and paid plans from $${starter.price} a month. This page explains who each suits, including where Tailwind is the better pick.`,
    updated: CHECKED,
    blocks: [
      h2('summary', 'The short version'),
      ul(
        '**Choose GoPinKaro** if you only need Pinterest, want to bulk schedule from images, a CSV or a sitemap, and want a free plan and straightforward Pinterest-only plans.',
        '**Choose Tailwind** if you want pin design tools in the same product, need Instagram or Facebook alongside Pinterest, or rely on its community and established workflows.',
      ),
      h2('differences', 'Side by side'),
      table(['', 'GoPinKaro', 'Tailwind'], [
        ['Networks', 'Pinterest only', 'Pinterest, plus other networks such as Instagram'],
        ['Pinterest accounts', `One login manages ${FACTS.accounts.free} to ${FACTS.accounts.business} depending on plan`, 'Priced per Pinterest account'],
        ['Bulk scheduling', `Images or CSV, up to ${FACTS.bulkMax} per batch (paid)`, 'Bulk creation and scheduling tools'],
        ['Website to pins', 'Single page, plus whole sitemap on Pro and above', 'Check their current feature list'],
        ['Pin design', `Template designer: ${FACTS.designer.templates} layouts, ${FACTS.designer.palettes} color sets, your own photo. Use Canva for custom artwork`, 'Includes design and AI design features'],
        ['AI writing', `${free.ai} generations a month free, more on paid plans`, 'AI copy features, check how usage is counted on your plan'],
        ['Chat assistant that operates the app', 'Yes, with confirmation before changes', 'No equivalent that we know of'],
        ['Free plan', `Yes, ${free.pins} pins a month`, 'Check their current free plan'],
        ['Pricing', `From $${starter.price} a month, $${starter.yearly} a year`, "See Tailwind's own pricing page"],
      ], 'Comparison reflects public information as of October 2026. Confirm current Tailwind features and prices on tailwindapp.com.'),
      h2('why-switch', 'Why people look for an alternative'),
      p('Common reasons are cost, paying for networks they do not use, wanting a simpler tool, or wanting to bulk schedule a large content library without a lot of setup. If none of those apply, there is little reason to switch.'),
      h2('strengths', 'Where GoPinKaro is strong'),
      ul(
        '**Bulk from anything.** Upload a folder of images, import a CSV, or paste a page or sitemap.',
        '**Review-first automation.** AI drafts titles, descriptions and alt text, and you approve before anything is scheduled.',
        '**Assistant.** Ask in plain language to schedule, reschedule, retry or report. It asks for confirmation before changing anything.',
        '**Live queue.** Statuses update in real time, and failed pins show the reason with one-click retry.',
        '**Simple pricing.** Plans differ by volume and features, with no credit pool to track.',
      ),
      h2('limits-us', 'Where GoPinKaro is limited'),
      ul(
        'It publishes only to Pinterest.',
        `A login manages up to ${FACTS.accounts.business} Pinterest accounts on Business (${FACTS.accounts.pro} on Pro).`,
        `Its pin designer is template-based (${FACTS.designer.templates} layouts), not a full design studio like Canva.`,
        'It is newer than long-standing tools, so it has less history and fewer third-party tutorials.',
      ),
      h2('switching', 'Switching without losing your queue'),
      p('There is no automatic import from Tailwind. To move over, export or list the pins you want to keep, add them with the bulk scheduler (images or CSV), and cancel your old plan when the new queue is running. Do not cancel the old queue until your first pins have published from GoPinKaro.'),
      h2('plans', 'GoPinKaro plans'),
      plansTable(),
    ],
    faqs: [
      { q: 'What is the best Tailwind alternative?', a: 'It depends on what you want to change. For a Pinterest-only scheduler with bulk scheduling, website import and a free plan, GoPinKaro is one option. If you want multi-network scheduling, look at tools that cover several networks.' },
      { q: 'Is GoPinKaro cheaper than Tailwind?', a: `GoPinKaro's plans start at $${starter.price} a month and include a free plan. We do not publish Tailwind's prices because they change; compare against the current plan on tailwindapp.com for the features you need.` },
      { q: 'Does GoPinKaro have a design tool like Tailwind?', a: `Partly. GoPinKaro has a template-based pin designer (${FACTS.designer.templates} layouts, ${FACTS.designer.palettes} color sets, optional photo) that saves a ${FACTS.designer.width} x ${FACTS.designer.height} image, but it is not a full design studio and has no AI image generation. For custom artwork, design in Canva and upload it.` },
      { q: 'Can I manage multiple Pinterest accounts?', a: `Yes. One GoPinKaro login manages ${FACTS.accounts.free} account on Free, ${FACTS.accounts.starter} on Starter, ${FACTS.accounts.pro} on Pro and ${FACTS.accounts.business} on Business, all from one dashboard. Tailwind prices per Pinterest account.` },
      { q: 'Does GoPinKaro use the official Pinterest API?', a: 'Yes. You connect with Pinterest sign-in and approve the permissions, and pins are published through the official API.' },
    ],
    related: ['best-pinterest-tools', 'pinterest-scheduler', 'pinterest-bulk-scheduler', 'free-pinterest-scheduler'],
  },

  // ───────────────────────────────────────────────── /pinterest-scheduler-pricing
  {
    path: 'pinterest-scheduler-pricing',
    kind: 'comparison',
    label: 'Pinterest scheduler pricing',
    title: 'Pinterest scheduler pricing compared (2026)',
    description: "What Pinterest schedulers really cost in 2026: Tailwind, BlogToPin, Later, Buffer, Publer and more, with entry prices, per-pin cost and the credit and per-account charges that change the bill.",
    h1: 'Pinterest scheduler pricing compared: what you really pay in 2026',
    intro: `Pinterest's own scheduler is free. Pinterest-focused paid tools mostly cost between about $18 and $30 a month, general social media tools run from a few dollars per channel to $99 a month, and the number on the pricing page is rarely the whole story: credit pools, per-account pricing and annual billing all change it. GoPinKaro is free for ${free.pins} pins a month and paid plans start at $${starter.price}.`,
    updated: CHECKED,
    blocks: [
      h2('table', 'Entry prices side by side'),
      table(['Tool', 'Entry price (USD)', 'Free option', 'What to know'], [
        ["Pinterest's built-in scheduler", 'Free', 'Yes', 'One pin at a time, up to 30 days ahead, up to 10 scheduled at once.'],
        ['GoPinKaro', `From $${starter.price} a month ($${starter.yearly} a year)`, `Yes, ${free.pins} pins a month`, 'Pinterest only. Plans are priced by pins a month, with no credits to track.'],
        ['Tailwind', 'From $17.99 a month billed annually, or $29.99 billed monthly', 'Yes, limited', 'The scheduling and creation plan includes 300 credits a month. Extra credits cost $10 per 100. Priced per Pinterest account; SEO and Engagement are separate add-ons.'],
        ['BlogToPin', `From $${BLOGTOPIN[0].price} a month ($${BLOGTOPIN[0].yearly} a year)`, 'Check their site', 'Creates pins from your website automatically. First tier allows 1,000 pins a month; unlimited Pinterest accounts.'],
        ['PinBoostr', 'About $19.99 a month (as reported)', 'Free plan reported', 'Creates and schedules pins. Price comes from third-party roundups.'],
        ['Later', 'About $25 a month', 'Limited free tier', 'Multi-network and Instagram-first.'],
        ['Buffer', 'About $5 to $6 per channel a month', 'Yes', 'Pinterest counts as one channel. Simple and multi-network.'],
        ['Publer', 'From about $12 a month', 'Yes', 'Bulk upload and CSV import across several networks.'],
        ['Planoly', 'About $13 to $16 a month', 'Free mobile tier reported', 'Visual planner across several networks.'],
        ['Metricool', 'About $20 to $22 a month', 'Yes, 20 posts a month', 'Analytics-led, multi-network.'],
        ['SocialPilot', 'About $30 a month', '14-day trial', 'Agency-oriented, with bulk and CSV scheduling.'],
        ['Hootsuite', 'About $99 a month', 'Trial only', 'Enterprise suite with approval workflows.'],
        ['Social Champ', 'About $2 to $4 per account a month on annual billing', 'Limited', 'The cheapest multi-network option in the roundups.'],
      ], 'Tailwind and BlogToPin prices are from their own pricing pages; the rest are as listed in third-party roundups. Checked October 2026, in US dollars. Vendors change prices and billing periods often, so confirm on the vendor\'s page before you buy.'),
      h2('per-pin', 'What a pin costs'),
      p('Where a plan states how many pins it includes, you can work out the price per pin. Tailwind sells credits rather than pins, so it cannot be compared this way.'),
      table(['Plan', 'Price a month', 'Pins a month', 'Per pin'], [
        ...(['starter', 'pro', 'growth'] as const).map((id) => [`GoPinKaro ${PLANS[id].name}`, `$${PLANS[id].price_monthly_usd}`, PLANS[id].pins_per_month.toLocaleString('en-US'), perPin(PLANS[id].price_monthly_usd, PLANS[id].pins_per_month)]),
        ...BLOGTOPIN.map((t) => [`BlogToPin ${t.name}`, `$${t.price}`, t.pins.toLocaleString('en-US'), perPin(t.price, t.pins)]),
      ], 'Monthly prices, not annual. BlogToPin figures are from its pricing page; its daily limits are 35, 350 and 1,000 pins by tier.'),
      p(`GoPinKaro Starter costs less in total ($${starter.price} against $${BLOGTOPIN[0].price}) but slightly more per pin than BlogToPin's first tier. GoPinKaro Pro and Business are cheaper per pin than BlogToPin's first tier, while BlogToPin's Agency and Enterprise tiers are cheaper per pin than any GoPinKaro plan and come with unlimited Pinterest accounts. Both are caps, not targets: many Pinterest guides recommend staying around 5 to 15 pins a day whatever a tool allows, and GoPinKaro warns you above ${FACTS.dailySoftMax} a day.`),
      h2('real-price', 'What changes the real price'),
      ul(
        '**Credit pools.** Tailwind\'s plans include a monthly credit allowance used for its AI and creation features, and extra credits are sold separately at $10 per 100. Heavy AI use can cost more than the plan price suggests.',
        '**Per account or per channel.** Tailwind is priced per Pinterest account, Buffer per channel and Social Champ per account. If you run several accounts, multiply.',
        '**Annual versus monthly.** Tailwind\'s scheduling plan is $17.99 a month billed annually but $29.99 billed monthly, a 40% difference for the same product.',
        '**Features behind higher tiers.** Bulk upload, best-time scheduling and sitemap import are on paid tiers in most tools, GoPinKaro included.',
        '**Volume limits.** Check whether the cap is in pins, posts or credits, and whether it is per day or per month.',
      ),
      h2('which', 'Which pricing model suits you'),
      ul(
        'You post a few pins a week: use Pinterest\'s free scheduler, or the GoPinKaro Free plan if you want to schedule further ahead or import pages.',
        'You run one or a few Pinterest accounts and want predictable bills: a flat pins-per-month plan, shared across accounts, is the easiest to budget.',
        'You manage many Pinterest accounts: look at tools that price by volume rather than per account, such as BlogToPin.',
        'Pinterest is one channel of several: a multi-network tool such as Buffer, Publer or Metricool may cost less overall.',
      ),
      h2('our-plans', 'GoPinKaro plans'),
      plansTable(),
      h2('method', 'How this page was checked'),
      p('Tailwind and BlogToPin figures were read from their pricing pages on 6 October 2026. The other prices come from comparison articles listed below, and where two sources disagreed (for example Buffer at $5 or $6, Planoly at $13 or $16) we show the range. Some tools were left out of the table because the sources conflicted too much to state a price. Pricing changes often; this page is reviewed on the date shown above.'),
    ],
    faqs: [
      { q: 'What is the cheapest way to schedule Pinterest pins?', a: `Pinterest's built-in scheduler is free but limited to one pin at a time, up to 30 days ahead, with 10 pins scheduled at once. Beyond that, GoPinKaro's free plan allows ${free.pins} pins a month, and some multi-network tools such as Social Champ or Buffer start at a few dollars per account or channel.` },
      { q: 'How much does Tailwind cost?', a: "On Tailwind's pricing page the Pin Scheduling and Creation plan is $17.99 a month billed annually or $29.99 billed monthly, with 300 credits a month. Pinterest SEO and Pinterest Engagement are $11.99 a month annual or $14.99 monthly each, and a bundle of all three is $29.98 annual or $41.97 monthly. Extra credits are $10 per 100, and plans are per Pinterest account." },
      { q: 'How much does BlogToPin cost?', a: `BlogToPin lists three plans: $${BLOGTOPIN[0].price} a month (1,000 pins), $${BLOGTOPIN[1].price} a month (10,000 pins) and $${BLOGTOPIN[2].price} a month (30,000 pins), with unlimited Pinterest accounts. Yearly billing is $${BLOGTOPIN[0].yearly}, $${BLOGTOPIN[1].yearly} and $${BLOGTOPIN[2].yearly}.` },
      { q: 'Is a Pinterest scheduler worth paying for?', a: 'It depends on volume. If you publish a few pins a week, Pinterest\'s free scheduler may be enough. A paid tool earns its price when you schedule dozens of pins, want bulk upload, or want pins to follow new content automatically.' },
      { q: 'Why do prices differ between websites?', a: 'Vendors change prices and billing periods, roundup articles lag behind, and many quote annual billing as a monthly figure. Always confirm on the vendor\'s own page.' },
    ],
    related: ['tailwind-alternative', 'blogtopin-alternative', 'free-pinterest-scheduler', 'best-pinterest-tools'],
    sources: [SRC.tailwindPricing, SRC.blogtopinPricing, SRC.schedulerRoundup, SRC.pinboostrRoundup, SRC.gainRoundup, SRC.nativeLimits],
  },

  // ───────────────────────────────────────────────── /blogtopin-alternative
  {
    path: 'blogtopin-alternative',
    kind: 'comparison',
    label: 'BlogToPin alternative',
    title: 'BlogToPin alternative for Pinterest scheduling',
    description: 'GoPinKaro compared with BlogToPin: price, pin volume, accounts, daily limits and how each creates pins, with where BlogToPin is the better fit.',
    h1: 'A BlogToPin alternative for Pinterest scheduling',
    intro: `BlogToPin scans your website and generates pins automatically. GoPinKaro is a Pinterest scheduler where you stay in the loop: it drafts titles and descriptions, lets you design from templates or use your own images, and schedules after you review. It has a free plan (${free.pins} pins a month) and paid plans from $${starter.price} a month, against BlogToPin's $${BLOGTOPIN[0].price}.`,
    updated: CHECKED,
    blocks: [
      h2('summary', 'The short version'),
      ul(
        '**Choose GoPinKaro** if you want to review each pin, pay less for a smaller volume, start on a free plan, or use a chat assistant to run the schedule.',
        '**Choose BlogToPin** if you want pins generated for you from your site with as little involvement as possible, need unlimited Pinterest accounts, or publish at very high volume.',
      ),
      h2('differences', 'Side by side'),
      table(['', 'GoPinKaro', 'BlogToPin'], [
        ['How pins are made', `You review drafted text; images come from your pages, your uploads or the template designer (${FACTS.designer.templates} layouts)`, 'Generated automatically from your website, with a template library'],
        ['Pinterest accounts', `${FACTS.accounts.free} on Free, ${FACTS.accounts.starter} on Starter, ${FACTS.accounts.pro} on Pro, ${FACTS.accounts.business} on Business`, 'Unlimited on every plan'],
        ['Pins a month', `${starter.pins} at $${starter.price}, ${FACTS.pro.pins} at $${FACTS.pro.price}, ${FACTS.business.pins} at $${FACTS.business.price}`, `1,000 at $${BLOGTOPIN[0].price}, 10,000 at $${BLOGTOPIN[1].price}, 30,000 at $${BLOGTOPIN[2].price}`],
        ['Daily pace', `You choose; you are warned above ${FACTS.dailySoftMax} a day`, 'Plan limits of 35, 350 and 1,000 pins a day'],
        ['Free plan', `Yes, ${free.pins} pins a month`, 'None on the pricing page; check for a trial'],
        ['AI text', `${free.ai} generations a month free, more on paid plans`, 'AI credits per plan (200, 400, 500) with unlimited regenerations stated'],
        ['Chat assistant', 'Yes, with confirmation before changes', 'Not listed on the pricing page'],
        ['Starting price', `$${starter.price} a month, $${starter.yearly} a year`, `$${BLOGTOPIN[0].price} a month, $${BLOGTOPIN[0].yearly} a year`],
      ], "BlogToPin details are from its pricing page, checked October 2026. Confirm current features and prices on blogtopin.com."),
      h2('why-switch', 'Why people compare them'),
      p(`Usual reasons are price, wanting to see every pin before it publishes, and wanting a free plan to test with. BlogToPin's daily limits are ceilings rather than targets: many Pinterest guides recommend staying around 5 to 15 pins a day whatever a tool allows, so check the pace you will really run before paying for volume you will not use.`),
      h2('strengths', 'Where GoPinKaro is strong'),
      ul(
        '**Review first.** You approve titles, descriptions and images before anything is scheduled.',
        '**Lower entry price and a free plan.** Start free, then pay from $' + starter.price + ' a month.',
        '**Pacing check.** After you schedule, it flags crowded days and repeated images.',
        '**Assistant.** Ask for a week of pins, a retry or a report in plain language; it asks before changing anything.',
      ),
      h2('limits-us', 'Where GoPinKaro is limited'),
      ul(
        'It does not generate pin images automatically. The designer fills templates with text you write.',
        `Business tops out at ${FACTS.accounts.business} Pinterest accounts and 6,000 pins a month; BlogToPin lists unlimited accounts.`,
        'It tops out at 6,000 pins a month on the Business plan.',
        'It is newer, so it has a shorter track record.',
      ),
      h2('plans', 'GoPinKaro plans'),
      plansTable(),
    ],
    faqs: [
      { q: 'Is GoPinKaro a BlogToPin alternative?', a: 'Yes, with a different approach. BlogToPin generates pins automatically from your site; GoPinKaro drafts text and schedules pins you review, and offers a template designer for images.' },
      { q: 'Is GoPinKaro cheaper than BlogToPin?', a: `The entry price is lower: $${starter.price} a month for ${starter.pins} pins against $${BLOGTOPIN[0].price} for 1,000, though per pin BlogToPin's first tier is slightly cheaper. At high volume BlogToPin is clearly cheaper per pin, for example $${BLOGTOPIN[1].price} for 10,000 pins.` },
      { q: 'Can GoPinKaro create pin images automatically?', a: `Not automatically. The pin designer has ${FACTS.designer.templates} templates and ${FACTS.designer.palettes} color sets; you write the headline and can add your own photo. Website import uses the images already on your pages.` },
      { q: 'Does GoPinKaro support several Pinterest accounts?', a: `Yes, up to ${FACTS.accounts.business} on the Business plan (${FACTS.accounts.pro} on Pro, ${FACTS.accounts.starter} on Starter, ${FACTS.accounts.free} on Free), switched from one dashboard. BlogToPin lists unlimited accounts on every plan.` },
    ],
    related: ['pinterest-scheduler-pricing', 'tailwind-alternative', 'website-to-pinterest-pins', 'best-pinterest-tools'],
    sources: [SRC.blogtopinPricing, SRC.automationGuide],
  },
]
