import { FACTS, CHECKED, SRC } from './facts'
import { callout, h2, h3, p, plansTable, table, ul, type SeoPage } from './types'

const { free, starter } = FACTS

export const comparePages: SeoPage[] = [
  // ───────────────────────────────────────────────── /best-pinterest-tools
  {
    path: 'best-pinterest-tools',
    kind: 'comparison',
    label: 'Best Pinterest tools',
    title: "Best Pinterest tools by job (2026)",
    description: 'The Pinterest tools worth knowing, grouped by job: scheduling, design, keyword research and free options, with honest notes on where each one fits.',
    h1: 'The best Pinterest tools, by what you need to get done',
    intro: 'No single Pinterest tool does everything well. Most accounts end up with one scheduler, one design tool and one source of keyword data. This guide groups the tools people actually use by job, says what each is good at, and is clear about where GoPinKaro fits and where it does not.',
    updated: CHECKED,
    blocks: [
      h2('how-to-choose', 'How to choose'),
      p('Start from the job, not the brand. If your bottleneck is getting pins published on a steady schedule, you need a scheduler. If it is making attractive images, you need a design tool. If you are unsure what to pin about, you need keyword research. Many tools overlap, so start with the free tier of the one that matches your biggest bottleneck.'),
      table(['Job', 'Tools to look at'], [
        ['Scheduling and automation', 'GoPinKaro, Tailwind, Pinterest built-in scheduler, BlogToPin, Metricool'],
        ['Designing pins', 'Canva, Adobe Express'],
        ['Keyword research', 'Pinterest Trends, PinClicks, Pin Inspector, GoPinKaro keyword tool'],
        ['Free options', "Pinterest's scheduler, Pinterest Trends, GoPinKaro Free, Canva Free"],
      ]),
      h2('scheduling', 'Scheduling and automation'),
      h3('GoPinKaro'),
      p(`A Pinterest-only scheduler focused on bulk work. You can bulk schedule up to ${FACTS.bulkMax} pins from images or a CSV, turn web pages or a sitemap into drafted pins, publish at best-time slots in your timezone, and run it all from an AI assistant that confirms before it changes anything. Free plan: ${free.pins} pins a month. Paid plans from $${starter.price} a month. **Limits:** one Pinterest account per login (up to ${FACTS.businessAccounts} on Business), no Instagram or Facebook, and no image design tools.`),
      h3('Tailwind'),
      p('A long-established scheduler built around Pinterest, with a smart schedule feature, bulk creation tools, AI writing and pin design features, and it also covers other networks such as Instagram. It is a good choice if you want design and scheduling in one product. It is typically priced by plan tier with a set number of accounts, so compare it with GoPinKaro on its current pricing page.'),
      h3("Pinterest's built-in scheduler"),
      p("Free and built into Pinterest. You can schedule a pin up to 30 days ahead, one pin at a time, with up to 10 pins scheduled at once. Ideal for a light posting rhythm, and a sensible first step before paying for anything."),
      h3('BlogToPin and other website-to-pin tools'),
      p('Some tools focus on turning a website into pins automatically, including generating images. GoPinKaro takes a similar website-to-pins approach but uses the images already on your pages and keeps a review step before anything is scheduled.'),
      h3('Metricool'),
      p('A multi-network social planner with a free tier that can schedule Pinterest pins and show basic analytics. Useful if Pinterest is one channel among several.'),
      h2('design', 'Designing pins'),
      h3('Canva'),
      p('The most widely used design tool for pins, with vertical templates and batch features. It does not replace a scheduler, but it pairs well with one: design in Canva, export images, then bulk upload them to GoPinKaro.'),
      h2('research', 'Keyword research'),
      h3('Pinterest Trends'),
      p('Free and first-party. Shows what is rising on Pinterest. GoPinKaro surfaces the same trend data inside its keyword tool.'),
      h3('PinClicks and Pin Inspector'),
      p('Dedicated research tools. PinClicks lets you explore Pinterest keywords with search volume data and pin scores for evaluating competitors, and Pin Inspector helps you see which pins and keywords perform. They are paid, and they go deeper on research than a scheduler does.'),
      h2('where-us', 'Where GoPinKaro is the right choice'),
      ul(
        'You publish new pages or products regularly and want pins to follow automatically.',
        'You want to bulk schedule from a spreadsheet or a folder of images.',
        'You want Pinterest-only pricing and one to three Pinterest accounts.',
        'You want to run the work from a chat assistant with confirmation before changes.',
      ),
      h2('where-not', 'Where it is not'),
      ul(
        'You need to manage several Pinterest accounts from one login.',
        'You also publish to Instagram, Facebook or other networks from the same tool.',
        'You want a built-in pin design studio.',
        'You need deep competitor and keyword volume research.',
      ),
      h2('pricing', 'GoPinKaro plans'),
      plansTable(),
      callout('Facts about other tools are summarised from their public descriptions and press as of October 2026 and may change. Check each product\'s own site for current features and prices.', 'About this comparison'),
    ],
    faqs: [
      { q: 'What is the best Pinterest tool?', a: 'It depends on the job. For scheduling and automation, consider GoPinKaro, Tailwind or Pinterest\'s own scheduler. For design, Canva. For keyword research, Pinterest Trends, PinClicks or Pin Inspector.' },
      { q: 'What is the best Pinterest tool for free?', a: `Pinterest's built-in scheduler and Pinterest Trends are free. GoPinKaro's free plan includes ${free.pins} pins a month, and Canva has a free tier for design.` },
      { q: 'What is the best Pinterest tool for business?', a: 'Businesses that publish many pages or products usually need bulk scheduling and a repeatable workflow. GoPinKaro, Tailwind and similar schedulers are built for that, plus a design tool for images.' },
      { q: 'Do I need more than one Pinterest tool?', a: 'Usually yes. One scheduler plus one design tool covers most needs, and Pinterest Trends gives you free keyword ideas.' },
    ],
    related: ['tailwind-alternative', 'free-pinterest-scheduler', 'pinterest-keyword-tool', 'pinterest-automation-tool'],
    sources: [SRC.nativeLimits, SRC.pinterestCommunity],
  },

  // ───────────────────────────────────────────────── /tailwind-alternative
  {
    path: 'tailwind-alternative',
    kind: 'comparison',
    label: 'Tailwind alternative',
    title: "Tailwind alternative for Pinterest",
    description: 'Looking for a Tailwind alternative? See where GoPinKaro differs (Pinterest-only, bulk, website-to-pins, free plan) and where Tailwind fits better.',
    h1: 'A Tailwind alternative for Pinterest scheduling',
    intro: `Tailwind is a well-known Pinterest scheduler. GoPinKaro is a lighter, Pinterest-only alternative focused on bulk scheduling and turning web pages into pins, with a free plan (${free.pins} pins a month) and paid plans from $${starter.price} a month. This page explains who each suits, including where Tailwind is the better pick.`,
    updated: CHECKED,
    blocks: [
      h2('summary', 'The short version'),
      ul(
        '**Choose GoPinKaro** if you only need Pinterest, want to bulk schedule from images, a CSV or a sitemap, and want a free plan and straightforward Pinterest-only plans.',
        '**Choose Tailwind** if you want pin design tools in the same product, need Instagram or Facebook alongside Pinterest, or rely on its community and established workflows.',
      ),
      h2('differences', 'Side by side'),
      table(['', 'GoPinKaro', 'Tailwind'], [
        ['Networks', 'Pinterest only', 'Pinterest, plus other networks such as Instagram'],
        ['Pinterest accounts', 'One per login', 'Depends on plan tier'],
        ['Bulk scheduling', `Images or CSV, up to ${FACTS.bulkMax} per batch (paid)`, 'Bulk creation and scheduling tools'],
        ['Website to pins', 'Single page, plus whole sitemap on Pro and above', 'Check their current feature list'],
        ['Pin design', 'None. Use Canva or similar', 'Includes design and AI design features'],
        ['AI writing', `${free.ai} generations a month free, more on paid plans`, 'AI copy features, check how usage is counted on your plan'],
        ['Chat assistant that operates the app', 'Yes, with confirmation before changes', 'No equivalent that we know of'],
        ['Free plan', `Yes, ${free.pins} pins a month`, 'Check their current free plan'],
        ['Pricing', `From $${starter.price} a month, $${starter.yearly} a year`, "See Tailwind's own pricing page"],
      ], 'Comparison reflects public information as of October 2026. Confirm current Tailwind features and prices on tailwindapp.com.'),
      h2('why-switch', 'Why people look for an alternative'),
      p('Common reasons are cost, paying for networks they do not use, wanting a simpler tool, or wanting to bulk schedule a large content library without a lot of setup. If none of those apply, there is little reason to switch.'),
      h2('strengths', 'Where GoPinKaro is strong'),
      ul(
        '**Bulk from anything.** Upload a folder of images, import a CSV, or paste a page or sitemap.',
        '**Review-first automation.** AI drafts titles, descriptions and alt text, and you approve before anything is scheduled.',
        '**Assistant.** Ask in plain language to schedule, reschedule, retry or report. It asks for confirmation before changing anything.',
        '**Live queue.** Statuses update in real time, and failed pins show the reason with one-click retry.',
        '**Simple pricing.** Plans differ by volume and features, with no credit pool to track.',
      ),
      h2('limits-us', 'Where GoPinKaro is limited'),
      ul(
        'It publishes only to Pinterest.',
        `Each login connects one Pinterest account (up to ${FACTS.businessAccounts} on Business).`,
        'It has no pin design studio.',
        'It is newer than long-standing tools, so it has less history and fewer third-party tutorials.',
      ),
      h2('switching', 'Switching without losing your queue'),
      p('There is no automatic import from Tailwind. To move over, export or list the pins you want to keep, add them with the bulk scheduler (images or CSV), and cancel your old plan when the new queue is running. Do not cancel the old queue until your first pins have published from GoPinKaro.'),
      h2('plans', 'GoPinKaro plans'),
      plansTable(),
    ],
    faqs: [
      { q: 'What is the best Tailwind alternative?', a: 'It depends on what you want to change. For a Pinterest-only scheduler with bulk scheduling, website import and a free plan, GoPinKaro is one option. If you want multi-network scheduling, look at tools that cover several networks.' },
      { q: 'Is GoPinKaro cheaper than Tailwind?', a: `GoPinKaro's plans start at $${starter.price} a month and include a free plan. We do not publish Tailwind's prices because they change; compare against the current plan on tailwindapp.com for the features you need.` },
      { q: 'Does GoPinKaro have a design tool like Tailwind?', a: 'No. GoPinKaro does not design images. Create pins in Canva or another design tool and upload them with the bulk scheduler.' },
      { q: 'Can I manage multiple Pinterest accounts?', a: `Only on the Business plan, which connects up to ${FACTS.businessAccounts} accounts under one login. Other plans connect one account per login.` },
      { q: 'Does GoPinKaro use the official Pinterest API?', a: 'Yes. You connect with Pinterest sign-in and approve the permissions, and pins are published through the official API.' },
    ],
    related: ['best-pinterest-tools', 'pinterest-scheduler', 'pinterest-bulk-scheduler', 'free-pinterest-scheduler'],
  },
]
