import { FACTS, CHECKED, SRC } from './facts'
import { callout, h2, h3, ol, p, table, ul, type SeoPage } from './types'


export const guidePages2: SeoPage[] = [
  // ───────────────────────────────────────── best time
  {
    path: 'guides/best-time-to-post-on-pinterest',
    kind: 'guide',
    label: 'Best time to post on Pinterest',
    title: 'Best time to post on Pinterest: what the data says',
    description: 'Studies disagree on the best time to post on Pinterest, and one large study found timing did not predict success. What to do instead, and how to test your own audience.',
    h1: 'The best time to post on Pinterest: what the evidence says',
    intro: 'There is no single best time to post on Pinterest. Studies point to different windows, and the largest benchmark we found reported that timing did not predict success; consistency and fresh content mattered more. The practical answer is to publish steadily at sensible hours, then let your own results refine it.',
    updated: CHECKED,
    published: CHECKED,
    cta: { label: 'Schedule at best-time slots', redirect: '/dashboard/schedule' },
    blocks: [
      h2('studies', 'What the studies report'),
      table(['Source', 'Finding'], [
        ['Tailwind benchmark study (1.2 million pins, 17,000+ accounts, as reported)', 'No universal best time. Timing did not predict success; consistency, fresh content and alt text on every pin did.'],
        ['Social Champ analysis of 200,000+ posts', 'Best between 8 PM and 11 PM, especially on weekends.'],
        ['Other 2026 analyses', 'Activity peaks around midday and early afternoon, roughly 10 AM to 4 PM on weekdays.'],
      ], 'Findings as reported by the sources below, October 2026. They use different data, regions and methods, which is why they differ.'),
      p('The disagreement is the finding. Audiences differ by niche, country and season, and Pinterest content has a long life: a pin can be found weeks or months after it is published, so the hour it went live matters far less than it does on a feed that moves on within hours.'),
      h2('what-matters', 'What matters more than the hour'),
      ul(
        '**Consistency.** A steady daily rhythm beats occasional bursts.',
        '**Fresh, original images.** Pinterest discourages repeating the same pin.',
        '**Good titles, descriptions and alt text** that match what people search for. See [how to find Pinterest keywords](/guides/how-to-find-pinterest-keywords).',
        '**Pace.** Very high daily volumes risk looking like spam; see [how often to pin](/guides/how-often-to-pin-on-pinterest).',
      ),
      h2('default', 'A sensible starting point'),
      p('If you have no data yet, start with the evening and afternoon hours in your own timezone, and add some variety rather than posting every pin at the same minute. That is what GoPinKaro\'s best-time slots do by default: evening and afternoon hours, with small minute offsets so pins do not land exactly on the hour.'),
      h2('own-data', 'Using your own results'),
      p(`Once an account has about ${FACTS.personalTimingPins} published pins with results, GoPinKaro ranks the hours by how that account's own pins performed, with safeguards: an hour needs several pins and enough impressions before it counts, and each hour's result is pulled toward the account average so one lucky pin cannot decide the schedule. Pinterest only reports daily totals, so this is a cautious nudge rather than hourly audience data. The schedule form tells you which method is in use.`),
      h2('test', 'How to test it yourself'),
      ol('Publish at two or three different windows for a few weeks, keeping content quality similar.', 'Compare saves and outbound clicks per impression, not raw impressions, since older pins have had longer to gather views.', 'Keep what works, but change one thing at a time.'),
      callout('Treat any list of "best times" as a starting hypothesis. Your own analytics are the only data that describes your audience.', 'The takeaway'),
    ],
    faqs: [
      { q: 'What is the best time to post on Pinterest?', a: 'There is no universal best time. One large study found timing did not predict success, while others suggest evenings (8 to 11 PM) or midday to early afternoon. Start with evenings and afternoons in your timezone and refine from your own analytics.' },
      { q: 'Does posting time matter on Pinterest?', a: 'Less than on feeds that move quickly, because pins stay discoverable for a long time. Consistency, fresh images and good search copy matter more.' },
      { q: 'How does GoPinKaro choose posting times?', a: `By default it uses evening and afternoon hours in your timezone. After about ${FACTS.personalTimingPins} published pins with results, it ranks hours using that account's own results, cautiously.` },
      { q: 'Should I post at the same time every day?', a: 'Pick a steady rhythm, but vary the minutes so pins do not all land exactly on the hour.' },
    ],
    related: ['guides/how-often-to-pin-on-pinterest', 'guides/how-to-schedule-pinterest-pins', 'pinterest-scheduler', 'guides/pinterest-analytics-metrics-explained'],
    sources: [SRC.bestTimeTailwind, SRC.bestTimeStudy],
  },

  // ───────────────────────────────────────── keywords
  {
    path: 'guides/how-to-find-pinterest-keywords',
    kind: 'guide',
    label: 'How to find Pinterest keywords',
    title: 'How to find Pinterest keywords',
    description: 'Find the words people search on Pinterest using the search bar, guided search and Pinterest Trends, then place them in titles, descriptions, alt text and board names.',
    h1: 'How to find Pinterest keywords (and where to use them)',
    intro: 'Pinterest works like a visual search engine, so the words in your titles, descriptions and board names decide whether your pins are found. You can find those words for free with Pinterest\'s search bar, its guided search suggestions and Pinterest Trends.',
    updated: CHECKED,
    published: CHECKED,
    cta: { label: 'Open the keyword tool', redirect: '/dashboard/keywords' },
    blocks: [
      h2('search-bar', 'Start with the search bar'),
      p('Type a broad topic into Pinterest\'s search bar and watch the suggestions that appear as you type. They are based on what people actually search for, which makes them the fastest source of real phrases. Write down the ones that match your content, then add a word and see how the suggestions change.'),
      h2('guided', 'Use guided search'),
      p('After you search, Pinterest shows coloured buttons under the search bar with related phrases. They show how people narrow a topic, such as "small kitchen storage ideas" becoming "small kitchen storage ideas on a budget". These longer phrases are called long-tail keywords. They usually have fewer searches, but the people using them know what they want.'),
      h2('trends', 'Check Pinterest Trends'),
      p('Pinterest Trends shows which searches are rising or falling over time, which helps you publish ahead of a season. GoPinKaro\'s keyword tool surfaces the same trend data inside the dashboard, with weekly, monthly and yearly growth for up to 50 trending keywords in 14 regions, which you can filter by a word.'),
      callout('Growth is not volume. A keyword up 300% could still be small, and a very large keyword can be flat. Use trend data to choose timing and topics, and the search bar to confirm that real people use the phrase.', 'Read the numbers carefully'),
      h2('where', 'Where to use your keywords'),
      table(['Place', 'How to use it'], [
        ['Pin title', `Put the main phrase first, naturally, within ${FACTS.titleMax} characters.`],
        ['Pin description', `Use the phrase and related ones in readable sentences, up to ${FACTS.descriptionMax} characters. Avoid stuffing.`],
        ['Alt text', 'Describe what the image shows, using the phrase if it fits.'],
        ['Board names and descriptions', 'Name boards with the phrases people search for, so the whole board is found.'],
        ['Destination page', 'Keep the page\'s heading and text consistent with the pin.'],
      ]),
      h2('process', 'A simple weekly process'),
      ol(
        'Pick one topic you publish about.',
        'Collect 10 to 20 phrases from the search bar and guided search.',
        'Check the main ones in Pinterest Trends for timing.',
        'Write titles and descriptions around the best phrases, one phrase per pin.',
        'Review which pins earn saves and outbound clicks, and write more like them.',
      ),
      h2('limits', 'What GoPinKaro does and does not do'),
      p(`The [keyword tool](/pinterest-keyword-tool) shows Pinterest's trend growth data. It does not show search volume, competition or where your pins rank for a keyword; dedicated tools such as PinClicks or Tailwind's SEO add-on cover those. The AI writer drafts titles and descriptions around a topic, and you stay in control of the final wording. See [Pinterest SEO basics](/guides/pinterest-seo-basics).`),
    ],
    faqs: [
      { q: 'How do I find keywords for Pinterest?', a: 'Use the search bar suggestions, the guided search buttons and Pinterest Trends, then place the phrases in your titles, descriptions, alt text and board names.' },
      { q: 'Are Pinterest keywords the same as Google keywords?', a: 'Not exactly. Pinterest searches are often visual and planning-oriented ("small bathroom ideas"), so research on Pinterest itself is more reliable than assuming Google terms carry over.' },
      { q: 'Does GoPinKaro show keyword search volume?', a: 'No. It shows Pinterest\'s trend growth figures. For volume and competition use a dedicated research tool alongside it.' },
      { q: 'Should I use hashtags?', a: 'Keywords written in natural sentences matter most. Some people add a few relevant hashtags at the end of descriptions; keep them few and relevant.' },
    ],
    related: ['pinterest-keyword-tool', 'guides/pinterest-seo-basics', 'guides/pinterest-title-and-description-examples', 'use-cases/bloggers'],
    sources: [SRC.keywordResearch, SRC.charLimits],
  },

  // ───────────────────────────────────────── video specs
  {
    path: 'guides/pinterest-video-pin-specs',
    kind: 'guide',
    label: 'Pinterest video pin specs',
    title: 'Pinterest video pin specs and sizes (2026)',
    description: 'Pinterest video pin requirements: file types, length from 4 seconds to 15 minutes, aspect ratio limits, recommended shapes, file size and encoding, in one table.',
    h1: 'Pinterest video pin specs: formats, length, size and shape',
    intro: 'Pinterest video pins can be MP4, MOV or M4V files from 4 seconds to 15 minutes long, up to 2 GB, with a width-to-height ratio between 1:2 and 1.91:1. Pinterest recommends square, 2:3, 4:5 or 9:16 vertical video for standard pins.',
    updated: CHECKED,
    published: CHECKED,
    cta: { label: 'Schedule a video pin', redirect: '/dashboard/schedule' },
    blocks: [
      h2('table', 'The specs at a glance'),
      table(['Item', 'Requirement'], [
        ['File types', '.mp4, .mov or .m4v'],
        ['Length', '4 seconds to 15 minutes'],
        ['File size', 'Up to 2 GB'],
        ['Aspect ratio (required)', 'Taller than 1.91:1 and shorter than 1:2'],
        ['Aspect ratio (recommended)', 'Square (1:1), 2:3, 4:5 or vertical 9:16'],
        ['Encoding', 'H.264 or H.265'],
        ['Title', 'Up to 100 characters'],
        ['Description', 'Pinterest help cites up to 500 characters; the API accepts up to 800'],
      ], 'From Pinterest\'s help pages, October 2026. Check them for any later change.'),
      h2('shape', 'Choosing a shape'),
      p('Vertical video takes up more of the screen on a phone, which is where most Pinterest browsing happens, so 9:16 or 2:3 usually works best for how-to and recipe clips. Square is a safe middle ground. Very wide video fits the allowed range but appears small.'),
      h2('cover', 'The cover image'),
      p('A video pin needs a cover: the still people see before it plays. Choose a frame that shows the subject clearly rather than a black first frame, and make sure any text on it is readable at thumbnail size.'),
      h2('length', 'How long should a video pin be?'),
      p('Pinterest allows up to 15 minutes, but most video pins are short. A clip that shows the result or the key step in the first few seconds tends to suit a browsing audience, then you can add detail afterwards.'),
      h2('gopinkaro', 'Scheduling video pins with GoPinKaro'),
      p(`GoPinKaro checks the type, length and shape in your browser before uploading, and currently accepts files up to ${FACTS.videoMaxMb} MB (lower than Pinterest's 2 GB because files are stored before upload). It uploads to Pinterest at the scheduled time and publishes once Pinterest has processed the file. See [video pin scheduling](/pinterest-video-pin-scheduler).`),
      h2('compress', 'Getting a file under the limit'),
      ul('Export at 1080p rather than 4K; phones rarely need more.', 'Use H.264 in an MP4 container for the best compatibility.', 'Trim silence and unneeded footage at the start and end.', 'A video editor\'s "web" or "social" export preset usually gives a sensible file size.'),
    ],
    faqs: [
      { q: 'What size should a Pinterest video be?', a: 'Pinterest accepts aspect ratios between 1:2 and 1.91:1 and recommends square, 2:3, 4:5 or 9:16 vertical video.' },
      { q: 'How long can a Pinterest video pin be?', a: 'Between 4 seconds and 15 minutes.' },
      { q: 'What file types does Pinterest accept?', a: 'MP4, MOV and M4V, encoded with H.264 or H.265, up to 2 GB.' },
      { q: 'What is the biggest video I can schedule in GoPinKaro?', a: `${FACTS.videoMaxMb} MB currently, which is about a minute of 1080p video.` },
    ],
    related: ['pinterest-video-pin-scheduler', 'guides/pinterest-image-size-and-specs', 'pinterest-carousel-pin-scheduler', 'use-cases/food-bloggers'],
    sources: [SRC.pinterestVideoSpecs, SRC.pinterestPinSpecs],
  },

  // ───────────────────────────────────────── AI content
  {
    path: 'guides/pinterest-ai-generated-content-rules',
    kind: 'guide',
    label: 'Pinterest AI-generated content rules',
    title: 'Pinterest and AI-generated content: labels and what to do',
    description: 'Pinterest now labels AI-modified images and lets people see fewer of them. How the labels work, what it means for creators, and a safe way to use AI in your pins.',
    h1: 'Pinterest and AI-generated content: labels, controls and what to do',
    intro: 'Pinterest labels images it detects as AI-generated or AI-modified with an "AI modified" tag and lets people choose to see fewer AI pins. That does not ban AI, but it means a feed made entirely of AI images carries a visibility risk. A safer approach is to use your own photos and use AI for the words.',
    updated: CHECKED,
    published: CHECKED,
    cta: { label: 'Design pins from your own photos', redirect: '/dashboard/design' },
    blocks: [
      h2('what', 'What Pinterest announced'),
      ul(
        'Image pins detected as generated or altered with AI show an "AI modified" label in the bottom left corner of the close-up view.',
        'Pinterest says its classifiers look at metadata and at visual cues, so labels can apply even when the file carries no AI marker.',
        'There is an appeals process for creators who believe a label is wrong.',
        'People can choose to see fewer generative AI pins, through the three-dot menu on a pin, starting with categories such as beauty and art and expected to widen over time.',
      ),
      p('These changes followed widespread complaints about low-quality AI images flooding feeds. They were announced in 2025; check Pinterest\'s own pages for how they work today.'),
      h2('meaning', 'What this means for creators'),
      ul(
        '**It is not a ban.** Labelled pins can still be published and found.',
        '**There is a trade-off.** If people can ask to see less AI content, an all-AI feed may reach fewer of them.',
        '**Originality helps.** Your own photos, product images and designs carry no such label and show people something real.',
      ),
      h2('safe', 'A sensible way to use AI'),
      table(['Use AI for', 'Prefer your own work for'], [
        ['Drafting titles, descriptions and alt text that you edit', 'Product and lifestyle photography'],
        ['Brainstorming keywords and topics', 'Recipes, projects and results you have actually made'],
        ['A background image behind a headline, where a stock-style picture is enough', 'Anything where authenticity is the point'],
      ]),
      h2('gopinkaro', 'How GoPinKaro handles it'),
      ul(
        'The automatic page-to-pin design uses the photos from your own pages on template layouts. It does not generate images.',
        `AI is used for titles, descriptions and alt text, and, only if you ask, an optional AI background in the [pin designer](/pinterest-pin-maker) (${FACTS.aiImages.free} a month on Free, ${FACTS.aiImages.starter} on Starter, ${FACTS.aiImages.pro} on Pro, ${FACTS.aiImages.business} on Business). The designer warns that Pinterest labels AI-modified images.`,
        'Nothing is scheduled until you review it.',
      ),
      callout('We cannot predict how Pinterest will label or rank any individual pin. If you use AI images, check how those pins perform in your own analytics and adjust.', 'No guarantees'),
    ],
    faqs: [
      { q: 'Does Pinterest ban AI-generated images?', a: 'No. It labels images detected as AI-generated or AI-modified and lets people see fewer of them.' },
      { q: 'How does Pinterest detect AI images?', a: 'It says its classifiers analyse metadata and visual cues, so a pin can be labelled even without an explicit AI marker. Creators can appeal a label.' },
      { q: 'Should I use AI images on Pinterest?', a: 'Use them sparingly and where a generic picture is enough. Your own photos avoid the label and show people something real.' },
      { q: 'Does GoPinKaro generate images with AI?', a: 'Only if you ask: the pin designer can create an optional AI background. The automatic page design uses your own photos.' },
    ],
    related: ['pinterest-pin-generator', 'pinterest-pin-maker', 'pinboostr-alternative', 'guides/is-pinterest-scheduling-safe'],
    sources: [SRC.pinterestAiLabels],
  },

  // ───────────────────────────────────────── is scheduling safe
  {
    path: 'guides/is-pinterest-scheduling-safe',
    kind: 'guide',
    label: 'Is Pinterest scheduling safe?',
    title: 'Is Pinterest scheduling safe? What is allowed',
    description: 'Is scheduling Pinterest pins against the rules? What Pinterest allows, what it treats as spam, common myths, and what to do if your impressions drop.',
    h1: 'Is scheduling Pinterest pins safe? What Pinterest allows and what to avoid',
    intro: 'Scheduling pins is not against Pinterest\'s rules: Pinterest runs an official API so approved tools can publish for you. What causes trouble is spammy behaviour, such as repeating the same pins or mass-saving, and tools that log in as you. Here is what is known, what is folklore, and what to check if reach drops.',
    updated: CHECKED,
    published: CHECKED,
    cta: { label: 'See how GoPinKaro connects', redirect: '/dashboard/accounts' },
    blocks: [
      h2('allowed', 'What is allowed'),
      p('Publishing on a schedule through Pinterest\'s official API is allowed, and Pinterest even offers its own scheduler. What matters is how a tool gets access: through Pinterest\'s own authorisation page (OAuth), not by asking for your password. See our checklist for [choosing a safe scheduler](/safest-pinterest-scheduler).'),
      h2('spam', 'What Pinterest treats as spam'),
      ul(
        'Creating the same or similar pins and sharing them repeatedly.',
        'Mass-saving, automated following and scripted engagement.',
        'Operating an account through tools that log in as you rather than the official API.',
        'Linking to spammy or redirecting destinations.',
      ),
      p('Pinterest does not publish a daily pin limit. Community guidance repeated across tool help pages is roughly 5 to 15 new pins a day for most accounts, and spacing identical images several days apart across boards. Treat those as cautious rules of thumb, not official numbers.'),
      h2('myths', 'Common myths'),
      table(['Claim', 'What we can say'], [
        ['"Schedulers get you banned."', 'Not scheduling itself. Risky behaviour and unofficial tools do.'],
        ['"Only Pinterest\'s own scheduler is safe."', 'Pinterest provides an API precisely so partners can publish. Tools using it with OAuth follow its model.'],
        ['"There is a secret safe number of pins."', 'No official figure exists. Steady, varied pinning is the safer pattern.'],
        ['"Shadowbans are always caused by tools."', 'Reach drops have many causes: seasonality, content changes, link problems, or repeated pins.'],
      ]),
      h2('drop', 'If your impressions suddenly drop'),
      ol(
        'Check the date range and season first: many niches have natural dips.',
        'Look at which content changed: new formats, new boards, or a new batch of similar pins.',
        'Check that your destination links still work and are not flagged by your host or security tools.',
        'Look for repeated images or near-identical pins in the last few weeks and stop repeating them.',
        'Slow the pace for a couple of weeks and publish fresh, original pins at a steady rate.',
        'If you used a tool that asked for your password, disconnect it and change your Pinterest password.',
      ),
      h2('gopinkaro', 'Safeguards built into GoPinKaro'),
      ul(
        'Official API with Pinterest\'s own sign-in. No password is ever shared.',
        `A pacing check after you schedule: a day above ${FACTS.dailySoftMax} pins and an image reused within 7 days are flagged.`,
        'Duplicate warnings when you import a page you already pinned.',
        'No following, saving or commenting features.',
      ),
      callout('Pinterest decides what counts as spam, and no tool can promise that an account will never be limited. Original, varied pins at a steady pace are the best protection.', 'Be realistic'),
    ],
    faqs: [
      { q: 'Is it against Pinterest rules to schedule pins?', a: 'No. Pinterest provides an official API and its own scheduler. The risk is in spammy behaviour and in tools that log in as you.' },
      { q: 'Can scheduling pins cause a shadowban?', a: 'Scheduling alone does not. Repeating the same pins, an unnatural pace and unofficial automation are the common causes people cite.' },
      { q: 'How many pins a day is safe?', a: 'Pinterest gives no official number. Commonly repeated guidance is about 5 to 15 new pins a day.' },
      { q: 'What should I check if my reach drops?', a: 'Season, recent content changes, broken links, repeated images and pace. Slow down and publish fresh pins for a couple of weeks.' },
    ],
    related: ['safest-pinterest-scheduler', 'guides/how-often-to-pin-on-pinterest', 'guides/pinterest-ai-generated-content-rules', 'pinterest-automation-tool'],
    sources: [SRC.automationGuide, SRC.boardBooster, SRC.nativeLimits],
  },

  // ───────────────────────────────────────── titles and descriptions
  {
    path: 'guides/pinterest-title-and-description-examples',
    kind: 'guide',
    label: 'Pinterest title and description examples',
    title: 'Pinterest title and description examples that work',
    description: 'Examples of strong Pinterest titles and descriptions for recipes, home, travel and products, with character limits, keyword placement and a simple formula to reuse.',
    h1: 'Pinterest title and description examples (with a formula)',
    intro: `Pinterest titles can be up to ${FACTS.titleMax} characters and descriptions up to ${FACTS.descriptionMax}. The best ones put the main search phrase first, say plainly what the pin shows, and read like a person wrote them. Below are before-and-after examples and a formula you can reuse.`,
    updated: CHECKED,
    published: CHECKED,
    cta: { label: 'Draft titles with the AI writer', redirect: '/dashboard/ai-writer' },
    blocks: [
      h2('limits', 'The limits'),
      table(['Field', 'Limit', 'Note'], [
        ['Title', `${FACTS.titleMax} characters`, 'Only the first part shows in some views, so lead with the phrase.'],
        ['Description', `${FACTS.descriptionMax} characters`, 'Pinterest help cites 500 in the pin builder; the API accepts 800.'],
        ['Alt text', '500 characters', 'Describe the image for screen readers and search.'],
        ['Destination link', '2,048 characters', 'Link to the specific page, not your home page.'],
      ], 'Limits as enforced by GoPinKaro, following Pinterest\'s API.'),
      h2('formula', 'A title formula'),
      p('**Main search phrase + the benefit or detail that makes it specific.** Keep it natural: it should read like something a person would click, not a list of keywords.'),
      h2('titles', 'Title examples'),
      table(['Weak', 'Stronger', 'Why it works'], [
        ['Mum\'s Tuesday special', 'Easy weeknight chicken pasta ready in 20 minutes', 'Starts with what people search for, adds a concrete benefit'],
        ['My new reading corner', 'Cozy reading nook ideas on a small budget', 'Names the idea and the audience\'s constraint'],
        ['Weekend away', 'Weekend coast trip guide: where to stay and eat', 'Says what the pin contains'],
        ['Handmade mug', 'Handmade ceramic coffee mug in speckled blue glaze', 'Product, material and style in one line'],
      ], 'Illustrative examples only. Use your own content.'),
      h2('descriptions', 'A description formula'),
      ol(
        'One sentence on what the pin shows or teaches, using the main phrase.',
        'One sentence on who it is for or when to use it, with a related phrase.',
        'A soft call to action: save for later, read the full guide, shop the range.',
        'Optionally two or three relevant hashtags at the end.',
      ),
      h3('Example'),
      p('"Small kitchen storage ideas that make the most of every inch: floating shelves, hanging rails and slim rolling carts. A good starting point for renters and tiny flats. Save this for your next organising weekend and read the full guide on the blog."'),
      h2('alt', 'Alt text examples'),
      ul('Weak: "image1.jpg".', 'Better: "White kitchen with open shelves holding glass jars and a hanging rail with copper utensils."'),
      h2('mistakes', 'Common mistakes'),
      ul(
        'Stuffing the description with a list of keywords.',
        'Using the same title and description on every pin for one page; write a different angle each time.',
        'Writing in all capitals or with heavy emoji.',
        'Leaving alt text empty.',
      ),
      h2('tool', 'Let the AI writer draft, then edit'),
      p('GoPinKaro\'s AI writer returns three title options and a description for a topic or an imported page, and checks the character limits for you. Always read and edit the result so it sounds like you, and so the facts are right. See [how to find Pinterest keywords](/guides/how-to-find-pinterest-keywords) for choosing the phrase.'),
    ],
    faqs: [
      { q: 'How long can a Pinterest title be?', a: `Up to ${FACTS.titleMax} characters.` },
      { q: 'How long can a Pinterest description be?', a: `Up to ${FACTS.descriptionMax} characters through the API; Pinterest help cites 500 in the pin builder.` },
      { q: 'Should the keyword go first in the title?', a: 'Usually, yes, as long as it reads naturally. Lead with the phrase people would search, then add the detail.' },
      { q: 'Do I need alt text?', a: 'It is optional but recommended: it helps people using screen readers and gives Pinterest more context about the image.' },
    ],
    related: ['guides/how-to-find-pinterest-keywords', 'guides/pinterest-seo-basics', 'pinterest-pin-generator', 'use-cases/food-bloggers'],
    sources: [SRC.charLimits, SRC.keywordResearch],
  },

  // ───────────────────────────────────────── analytics
  {
    path: 'guides/pinterest-analytics-metrics-explained',
    kind: 'guide',
    label: 'Pinterest analytics metrics explained',
    title: 'Pinterest analytics metrics explained',
    description: 'What impressions, saves, pin clicks, outbound clicks and engagement mean on Pinterest, how to read them together, and which numbers to act on first.',
    h1: 'Pinterest analytics metrics explained: what to look at',
    intro: 'Pinterest reports impressions, saves, pin clicks, outbound clicks and engagement. Impressions say how often your pins were shown; saves, clicks and outbound clicks say what people did about it. Read them as rates, not raw counts, and act on outbound clicks first if your goal is traffic.',
    updated: CHECKED,
    published: CHECKED,
    cta: { label: 'Open your analytics', redirect: '/dashboard/analytics' },
    blocks: [
      h2('metrics', 'The five metrics'),
      table(['Metric', 'What it generally means', 'Why it matters'], [
        ['Impressions', 'How many times your pins appeared on screen', 'Reach: whether Pinterest is showing your content'],
        ['Saves', 'How many times people saved your pins to a board', 'Interest: saved pins keep being shown over time'],
        ['Pin clicks', 'Clicks to open a pin\'s close-up view', 'Curiosity: the image and title earned attention'],
        ['Outbound clicks', 'Clicks through to your destination page', 'Traffic: people leaving Pinterest for your site or shop'],
        ['Engagement', 'The combined total of actions on your pins', 'A summary of how much people interacted'],
      ], 'General definitions. Pinterest\'s own help pages give the exact wording for each metric.'),
      h2('rates', 'Read them as rates'),
      ul(
        '**Saves per impression** shows how appealing the pin is to the people who saw it.',
        '**Outbound clicks per impression** shows how well it sends traffic.',
        '**Compare pins published around the same time.** Older pins have simply had longer to gather views.',
      ),
      h2('patterns', 'What the patterns suggest'),
      table(['Pattern', 'Likely meaning', 'What to try'], [
        ['High impressions, low saves and clicks', 'Shown widely but not compelling', 'Stronger image, clearer title, a better fit with the search phrase'],
        ['High saves, low outbound clicks', 'People like it but see no reason to click', 'A clearer promise of what is on the page; a call to action'],
        ['Low impressions across the board', 'Reach problem', 'Keywords, consistency, fresh images, and check for repeated pins'],
        ['One pin far ahead of the rest', 'A format or topic that works', 'Make more in that style, with fresh images'],
      ]),
      h2('gopinkaro', 'Analytics in GoPinKaro'),
      p(`Each connected account has its own analytics: daily totals for impressions, saves, pin clicks, outbound clicks and engagement, plus your top pins. History is 7 days on Free, 30 on Starter and 90 on Pro and Business, synced from Pinterest about every six hours, and you can refresh an account's numbers on demand. Pinterest only reports daily totals, which is why [best-time slots](/guides/best-time-to-post-on-pinterest) are learned cautiously and only after enough pins have results.`),
      callout('Numbers vary a lot from pin to pin. Look at trends over weeks, not single days.', 'Keep perspective'),
    ],
    faqs: [
      { q: 'What is the most important Pinterest metric?', a: 'It depends on your goal. For traffic, outbound clicks. For reach, impressions. Saves show lasting interest.' },
      { q: 'What is a good Pinterest engagement rate?', a: 'There is no universal benchmark, because it varies by niche and content type. Compare your own pins over time.' },
      { q: 'How far back does GoPinKaro keep analytics?', a: '7 days on Free, 30 on Starter, and 90 on Pro and Business.' },
      { q: 'Why do older pins have more impressions?', a: 'Pins stay discoverable and keep gathering views, so older pins have had longer. Compare pins of similar age.' },
    ],
    related: ['guides/best-time-to-post-on-pinterest', 'guides/pinterest-seo-basics', 'manage-multiple-pinterest-accounts', 'pinterest-scheduler'],
    sources: [SRC.bestTimeTailwind],
  },

  // ───────────────────────────────────────── multi-account guide
  {
    path: 'guides/how-to-manage-multiple-pinterest-accounts',
    kind: 'guide',
    label: 'How to manage multiple Pinterest accounts',
    title: 'How to manage multiple Pinterest accounts',
    description: 'How to run more than one Pinterest account: Pinterest\'s own account rules, keeping content distinct, a weekly routine, and which tools help without breaking the rules.',
    h1: 'How to manage multiple Pinterest accounts without the chaos',
    intro: 'Running several Pinterest accounts is common for agencies, multi-niche bloggers and shops with separate brands. The keys are knowing Pinterest\'s own rules about accounts, keeping each account\'s content distinct, working to a routine, and using a tool that publishes through the official API and keeps each account\'s queue separate.',
    updated: CHECKED,
    published: CHECKED,
    cta: { label: 'Connect your accounts', redirect: '/dashboard/accounts' },
    blocks: [
      h2('rules', 'Pinterest\'s own rules about accounts'),
      p('As reported in Pinterest help and third-party guides, one email address can hold one personal and one business account, and extra business accounts need their own email addresses. Pinterest has also offered linking several business accounts under one login, and reports say linked business accounts are being phased out. Rules change, so read Pinterest Help before creating accounts, and only create accounts for genuinely separate brands or websites.'),
      h2('distinct', 'Keep each account distinct'),
      ul(
        'Give each account its own niche, boards and audience.',
        'Do not post the same pins to several accounts of your own; Pinterest discourages repeated content.',
        'Use different images and different wording per account, even for similar products.',
        'Link each account to its own website or section.',
      ),
      h2('routine', 'A weekly routine that scales'),
      ol(
        'Monday: check which accounts need attention (expired connections, failed pins).',
        'Fill each account\'s queue for the coming one or two weeks, in batches, one account at a time.',
        'Review analytics per account and note what earned saves and clicks.',
        'Plan the next batch of content per account from what worked.',
      ),
      h2('tools', 'What to look for in a tool'),
      table(['Need', 'Why'], [
        ['Official API sign-in', 'No shared passwords, and access can be revoked per account.'],
        ['Separate queue, calendar and analytics per account', 'So content never mixes between accounts.'],
        ['A clear active-account indicator', 'So you never schedule to the wrong account.'],
        ['A needs-attention view', 'To spot expired connections and failures fast.'],
        ['Pricing that does not multiply per account', 'Costs can add up quickly at ten or more accounts.'],
      ]),
      h2('gopinkaro', 'How GoPinKaro supports this'),
      p(`One login manages up to ${FACTS.accounts.business} accounts, with a searchable switcher, an Accounts page that flags accounts needing attention, and per-account boards, queues, calendars and analytics. The monthly pin allowance is shared across accounts. See [managing multiple accounts](/manage-multiple-pinterest-accounts) and [the agency guide](/use-cases/agencies).`),
      callout('Only connect Pinterest accounts you own or are authorised to manage.', 'Permission first'),
    ],
    faqs: [
      { q: 'Can you have multiple Pinterest accounts?', a: 'Yes, within Pinterest\'s rules. As reported, one email can hold one personal and one business account, and more business accounts need separate emails. Check Pinterest Help for the current rules.' },
      { q: 'How do I manage several Pinterest accounts at once?', a: 'Use a scheduler that supports multiple accounts through the official API, keep content distinct per account, and follow a weekly routine.' },
      { q: 'Is it safe to post the same pin to several accounts?', a: 'Pinterest discourages repeated content. Use different images and wording per account.' },
      { q: 'How many accounts does GoPinKaro support?', a: `${FACTS.accounts.free} on Free, ${FACTS.accounts.starter} on Starter, ${FACTS.accounts.pro} on Pro and ${FACTS.accounts.business} on Business.` },
    ],
    related: ['manage-multiple-pinterest-accounts', 'use-cases/agencies', 'cheapest-pinterest-scheduler', 'safest-pinterest-scheduler'],
    sources: [SRC.pinterestAccountsHelp, SRC.metricoolMulti],
  },
]
