import { FACTS, CHECKED, SRC } from './facts'
import { callout, h2, ol, p, steps, table, ul, type SeoPage } from './types'

const { free } = FACTS

export const guidePages: SeoPage[] = [
  {
    path: 'guides/how-to-schedule-pinterest-pins',
    kind: 'guide',
    label: 'How to schedule Pinterest pins',
    title: "How to schedule Pinterest pins (2 methods)",
    description: "Step-by-step guide to scheduling Pinterest pins: with Pinterest's built-in scheduler, and in bulk with GoPinKaro. Includes limits, timing and common mistakes.",
    h1: 'How to schedule Pinterest pins',
    intro: "You can schedule Pinterest pins in two ways: with Pinterest's built-in scheduler, which is free but limited to one pin at a time, up to 30 days ahead, or with a scheduler tool that connects through the Pinterest API and can queue many pins at once. This guide covers both.",
    updated: CHECKED,
    blocks: [
      h2('native', "Method 1: Pinterest's built-in scheduler"),
      p("Best for a few pins a week. Menu names can change, so follow what you see on screen."),
      steps(
        ['Start a new pin', 'Open Pinterest on desktop, choose Create, then Create Pin.'],
        ['Upload your image and fill in the details', 'Add a title, description, destination link and board. Use a vertical image.'],
        ['Choose to publish later', 'Pick the option to publish at a later date, then set the date and time.'],
        ['Publish', 'Confirm. The pin joins your scheduled pins and goes out at the time you chose.'],
      ),
      p("Limits to know: according to the sources below, you can schedule up to 30 days ahead, one pin at a time, with up to 10 pins scheduled at once, and you cannot edit the image once it is scheduled."),
      h2('bulk', 'Method 2: bulk schedule with GoPinKaro'),
      steps(
        ['Connect your Pinterest account', 'Click Continue with Pinterest and approve the permissions. That creates your GoPinKaro account.'],
        ['Add pins', 'Use New pin for one pin, Bulk schedule for images or a CSV, or From website to turn a page into pins.'],
        ['Write titles and descriptions', 'Edit the drafted text, or ask the AI writer for three options. Put the main keyword first in the title.'],
        ['Choose a board and a pace', 'Pick a fixed interval (for example every 6 hours) or best-time slots (paid plans), then schedule.'],
        ['Watch the queue', 'The Pins page and calendar update live. Edit, move or delete any scheduled pin, and retry failures in one click.'],
      ),
      h2('when-to-post', 'When should you schedule pins?'),
      p('There is no universal best time. Evenings and afternoons in your audience\'s timezone are sensible starting points. GoPinKaro\'s best-time slots use those hours in your timezone with natural minute offsets. After a few weeks, check your analytics and adjust.'),
      h2('mistakes', 'Common mistakes'),
      ul(
        '**Scheduling everything at once.** Spread pins over days. Bursts followed by silence are harder to maintain.',
        '**Repeating the same image.** Create several different images for a page and vary titles.',
        '**Skipping alt text and keywords.** Describe the image and use the words people search for.',
        '**Forgetting the destination link.** A pin without a link cannot send traffic.',
        '**Ignoring failures.** Check for failed pins weekly. A common cause is a disconnected Pinterest account.',
      ),
      h2('compare', 'Which method should you use?'),
      table(['If you', 'Use'], [
        ['Post a few pins a week by hand', "Pinterest's built-in scheduler"],
        ['Want to schedule more than a month ahead', 'A scheduler tool such as GoPinKaro'],
        ['Have many images or a CSV of products', 'Bulk scheduling'],
        ['Want pins created from blog posts', 'A website-to-pins importer'],
      ]),
      callout(`GoPinKaro's free plan includes ${free.pins} pins a month, so you can try the bulk workflow before paying.`),
    ],
    faqs: [
      { q: 'How far ahead can you schedule Pinterest pins?', a: `Pinterest's built-in scheduler allows up to 30 days ahead. GoPinKaro allows up to ${FACTS.scheduleAheadDays} days ahead.` },
      { q: 'Can you schedule Pinterest pins for free?', a: `Yes. Pinterest's own scheduler is free, and GoPinKaro's free plan includes ${free.pins} pins a month.` },
      { q: 'Can I schedule pins from my phone?', a: 'Pinterest says its scheduler works on desktop and mobile. GoPinKaro is a web app that works on phone browsers as well as desktop.' },
      { q: 'What is the best time to post on Pinterest?', a: 'There is no single best time. Start with afternoons and evenings in your audience\'s timezone, then use your own analytics to adjust.' },
    ],
    related: ['pinterest-scheduler', 'guides/pinterest-native-scheduler-limits', 'guides/how-often-to-pin-on-pinterest', 'pinterest-bulk-scheduler'],
    sources: [SRC.nativeLimits, SRC.pinterestCommunity],
  },
  {
    path: 'guides/pinterest-native-scheduler-limits',
    kind: 'guide',
    label: "Pinterest's built-in scheduler: limits",
    title: "Pinterest's built-in scheduler: limits",
    description: "What Pinterest's own scheduler can and cannot do: a 30-day window, one pin at a time, a queue of up to 10, and when a scheduler tool is worth it.",
    h1: "Pinterest's built-in scheduler: what it can and can't do",
    intro: "Pinterest lets you schedule pins natively, free of charge. According to the sources below it has a 30-day scheduling window, schedules one pin at a time, holds up to 10 scheduled pins and does not let you change the image after scheduling. For many accounts that is plenty. This guide helps you decide when it is not.",
    updated: CHECKED,
    blocks: [
      h2('limits', 'The limits, in one table'),
      table(['Limit', 'What it means'], [
        ['30 days ahead', 'You cannot schedule further out than about a month.'],
        ['One pin at a time', 'There is no bulk upload or CSV import in the built-in scheduler.'],
        ['Up to 10 scheduled pins', 'Your queue can hold only a handful of pins at once.'],
        ['No editing media after scheduling', 'To change the image you need to delete and recreate the pin.'],
        ['No suggested posting times', 'You choose every date and time yourself.'],
      ], 'As reported in the sources below, October 2026. Pinterest may change these limits at any time.'),
      h2('good-for', 'Who it is perfect for'),
      ul('Accounts that publish a few pins a week.', 'People who create each pin by hand in the pin builder.', 'Anyone who wants a free starting point.'),
      h2('outgrow', 'Signs you have outgrown it'),
      ul(
        'You regularly want more than 10 pins queued.',
        'You want to plan more than 30 days ahead, for example around a season.',
        'You are copying the same details into the pin builder over and over.',
        'You want pins created from your blog or product pages.',
        'You want to change a pin without rebuilding it.',
      ),
      h2('next', 'What to do next'),
      p(`A scheduler tool that uses the official Pinterest API removes those limits. GoPinKaro's free plan allows ${free.pins} pins a month, up to ${FACTS.scheduleAheadDays} days ahead, with bulk adding. See the free scheduler comparison for the details.`),
    ],
    faqs: [
      { q: "Does Pinterest have its own scheduler?", a: 'Yes. You can schedule a pin from the pin builder by choosing to publish at a later date.' },
      { q: 'How many pins can I schedule on Pinterest?', a: "According to the sources below, up to 10 scheduled pins at a time, scheduled one at a time, up to 30 days ahead." },
      { q: 'Can I bulk upload pins to Pinterest?', a: "Not with the built-in scheduler as described in the sources below. Third-party schedulers that use the Pinterest API can queue many pins at once." },
    ],
    related: ['free-pinterest-scheduler', 'pinterest-scheduler', 'guides/how-to-schedule-pinterest-pins', 'pinterest-bulk-scheduler'],
    sources: [SRC.nativeLimits, SRC.pinterestCommunity],
  },
  {
    path: 'guides/pinterest-image-size-and-specs',
    kind: 'guide',
    label: 'Pinterest image size and pin specs',
    title: "Pinterest image size and pin specs",
    description: 'Recommended Pinterest pin size (1000 x 1500, 2:3), file types, file size, title and description lengths, and how to write for what the feed actually shows.',
    h1: 'Pinterest image size and pin specs',
    intro: 'The standard Pinterest pin is a vertical image at a 2:3 ratio, with 1000 by 1500 pixels as the commonly recommended size. Titles are limited to 100 characters, and only the start of a title or description is visible in the feed, so lead with your keyword.',
    updated: CHECKED,
    blocks: [
      h2('quick', 'Quick reference'),
      table(['Spec', 'Recommendation'], [
        ['Image size', '1000 x 1500 pixels'],
        ['Aspect ratio', '2:3 (vertical)'],
        ['File types in GoPinKaro', 'JPG, PNG, WEBP, GIF'],
        ['Maximum file size in GoPinKaro', `${FACTS.imageMaxMb} MB`],
        ['Title', 'Up to 100 characters; only roughly the first 40 are visible in the feed'],
        ['Description', "Pinterest's pin builder allows around 500 characters; roughly the first 50 to 60 are visible in the feed"],
        ['Alt text', 'One plain sentence describing the image'],
      ], 'Sizes and visible-length figures are as commonly reported (see sources). Pinterest may adjust them.'),
      h2('why-vertical', 'Why vertical images'),
      p('Pinterest is browsed on tall mobile screens. Pins that fall outside the common 2:3 ratio can be cropped or take up less space in the feed, so a vertical image gives you the most room.'),
      h2('writing', 'Write for the visible part'),
      ul(
        '**Titles:** put the main keyword first, then the benefit. Keep the whole title under 100 characters.',
        '**Descriptions:** make the first sentence carry the keyword and the point. Put hashtags last, if you use them.',
        '**Alt text:** describe what is in the image. Do not stuff keywords.',
      ),
      h2('in-app', 'In GoPinKaro'),
      p(`GoPinKaro accepts JPG, PNG, WEBP and GIF files up to ${FACTS.imageMaxMb} MB, trims titles to ${FACTS.titleMax} characters, and shows a character counter as you type. Images are checked when you upload them.`),
    ],
    faqs: [
      { q: 'What is the best Pinterest pin size?', a: 'The commonly recommended size is 1000 x 1500 pixels at a 2:3 aspect ratio.' },
      { q: 'How long can a Pinterest title be?', a: 'Up to 100 characters. Only the first part is visible in the feed, so put the main keyword first.' },
      { q: 'How long can a Pinterest description be?', a: "Pinterest's pin builder allows around 500 characters. Only the first 50 to 60 or so are visible in the feed, according to the sources below." },
    ],
    related: ['pinterest-bulk-scheduler', 'guides/pinterest-seo-basics', 'guides/how-to-schedule-pinterest-pins', 'pinterest-keyword-tool'],
    sources: [SRC.imageSizeTailwind, SRC.imageSizePubler, SRC.charLimits],
  },
  {
    path: 'guides/how-often-to-pin-on-pinterest',
    kind: 'guide',
    label: 'How often to pin on Pinterest',
    title: "How often should you pin on Pinterest?",
    description: 'No official number exists. A practical way to choose how many pins to publish per day, how to space them, and how to adjust using your own analytics.',
    h1: 'How often should you pin on Pinterest?',
    intro: 'There is no official number that Pinterest requires. Our recommendation is one to five fresh pins a day, spread across the day, rather than large bursts. This guide explains how to choose a number you can sustain and how to adjust it with your own data.',
    updated: CHECKED,
    blocks: [
      h2('principle', 'The principle: sustainable beats maximal'),
      p('A pace you can keep up for months beats a high pace that you abandon. Pick a number you can feed with good content, and keep it going.'),
      h2('starting-points', 'Starting points'),
      table(['Situation', 'Starting pace'], [
        ['New account or small blog', '1 pin a day'],
        ['Active blog or small shop', '2 to 3 pins a day'],
        ['Large catalog and plenty of images', '3 to 5 pins a day, with varied images'],
      ], 'These are our recommendations, not Pinterest rules.'),
      h2('quality', 'Quality and freshness matter more than the count'),
      ul(
        'Use different images and headlines for the same page rather than repeating one pin.',
        'Link every pin to a page that delivers what the pin promises.',
        'Avoid publishing near-duplicates. GoPinKaro warns you when a new pin is very similar to a recent one.',
      ),
      h2('spacing', 'Spacing'),
      p('Spread pins across the day instead of publishing them together. GoPinKaro\'s best-time slots do this for you: choose pins per day and it places them in afternoon and evening slots in your timezone with small minute offsets.'),
      h2('adjust', 'Adjust with your own data'),
      ol('Run your chosen pace for three to four weeks.', 'Open Analytics and look at impressions, saves and outbound clicks.', 'If results are growing and content quality is steady, add a pin a day. If you are running out of good images, reduce the pace.'),
      h2('limits', 'Planning your monthly volume'),
      p(`Pins are counted against your monthly plan when they are scheduled to publish. At 3 pins a day you need about 90 pins a month; the free plan includes ${free.pins} pins a month, and paid plans start at ${FACTS.starter.pins}.`),
    ],
    faqs: [
      { q: 'How many times a day should I pin?', a: 'There is no official number. One to five fresh pins a day is a sensible range for most accounts; choose the pace you can sustain with good content.' },
      { q: 'Is it bad to pin too much?', a: 'Pinning large batches of low-quality or repeated content can look like spam. Keep pins varied, relevant and spread across the day.' },
      { q: 'Should I pin every day?', a: 'A steady rhythm matters more than the exact count. A scheduler makes it easy to stay consistent, even on days you are busy.' },
    ],
    related: ['pinterest-scheduler', 'guides/how-to-schedule-pinterest-pins', 'pinterest-automation-tool', 'free-pinterest-scheduler'],
  },
  {
    path: 'guides/pinterest-seo-basics',
    kind: 'guide',
    label: 'Pinterest SEO basics',
    title: "Pinterest SEO basics for pins and boards",
    description: 'Pinterest works like a visual search engine. Learn where keywords matter (titles, descriptions, boards, alt text), how to find them and how to avoid stuffing.',
    h1: 'Pinterest SEO basics',
    intro: 'Pinterest is a visual search engine: people type a phrase and Pinterest shows pins that match it. Pinterest SEO means making sure the words attached to your pins, boards and profile match what people search for.',
    updated: CHECKED,
    blocks: [
      h2('where', 'Where keywords go'),
      table(['Place', 'What to do'], [
        ['Pin title', 'Main keyword first, under 100 characters.'],
        ['Pin description', 'Two natural sentences that include related phrases and say what the pin is about.'],
        ['Alt text', 'Describe the image plainly.'],
        ['Board name and description', 'Name boards with the phrase people would search for.'],
        ['Destination page', 'The page the pin links to should deliver on the keyword.'],
      ]),
      h2('finding', 'Finding keywords'),
      ul(
        '**Pinterest search suggestions:** type a topic into Pinterest search and note the suggested phrases.',
        '**Pinterest Trends:** shows what is rising. GoPinKaro\'s keyword tool shows the same trend data with weekly, monthly and yearly growth.',
        '**Your own analytics:** see which pins already get impressions and build on those topics.',
      ),
      h2('writing', 'Write for people first'),
      p('Keyword stuffing makes pins read badly and does not help. Use the main phrase once or twice, and write the rest like a sentence you would say to a person. The AI writer in GoPinKaro is instructed to write natural copy, but you should always read and edit it.'),
      h2('boards', 'Organize boards around searches'),
      p('Boards are searchable and group your pins by topic. Prefer a focused board such as "Small kitchen storage ideas" to a vague one such as "Home".'),
      h2('consistency', 'Be consistent'),
      p('Fresh pins that point to useful pages, published steadily, give Pinterest more to work with than occasional bursts. A scheduler helps you keep that rhythm.'),
    ],
    faqs: [
      { q: 'What is Pinterest SEO?', a: 'Optimizing pins, boards and pages with the words people search for on Pinterest so your pins appear in results.' },
      { q: 'Where should I put keywords on Pinterest?', a: 'In pin titles, descriptions, alt text, board names and board descriptions, and make sure the destination page matches.' },
      { q: 'How do I find the best keywords for Pinterest?', a: 'Use Pinterest search suggestions, Pinterest Trends and your own analytics to find phrases your audience uses, then write them naturally.' },
    ],
    related: ['pinterest-keyword-tool', 'guides/pinterest-image-size-and-specs', 'use-cases/bloggers', 'pinterest-scheduler'],
    sources: [SRC.charLimits],
  },
]
