import { FACTS, CHECKED, SRC } from './facts'
import { callout, h2, p, plansTable, steps, table, ul, type SeoPage } from './types'

const { free, starter } = FACTS
const acct = `${FACTS.accounts.free} on Free, ${FACTS.accounts.starter} on Starter, ${FACTS.accounts.pro} on Pro and ${FACTS.accounts.business} on Business`

export const productPages2: SeoPage[] = [
  // ───────────────────────────────────────── video
  {
    path: 'pinterest-video-pin-scheduler',
    kind: 'product',
    label: 'Pinterest video pin scheduler',
    title: 'Pinterest video pin scheduler',
    description: `Schedule Pinterest video pins: MP4 or MOV, 4 seconds to 15 minutes, with a cover image, processing handled for you and retries. Included on every GoPinKaro plan.`,
    h1: 'Schedule Pinterest video pins in advance',
    intro: `GoPinKaro schedules video pins as easily as images. Upload an MP4 or MOV (4 seconds to 15 minutes, up to ${FACTS.videoMaxMb} MB), pick a cover or let it use a frame from the video, set the title, board and time, and it is uploaded to Pinterest and published when due. Video is included on every plan, including Free.`,
    updated: CHECKED,
    published: CHECKED,
    cta: { label: 'Schedule your first video pin', redirect: '/dashboard/schedule' },
    blocks: [
      h2('how', 'How it works'),
      steps(
        ['Choose Video', 'On the New pin page switch the media tab to Video and add your file. The page checks the format, size, length and shape before anything uploads.'],
        ['Pick a cover', 'A frame from the video is used by default, or choose your own image. The cover is what people see before the video plays.'],
        ['Add the details', 'Write the title and description (the AI writer can draft options), add a destination link and alt text, then choose a board.'],
        ['Choose the time', 'Pick an exact time, or let best-time slots choose on paid plans. Video pins schedule up to a year ahead.'],
        ['GoPinKaro does the rest', 'When the pin is due, the video is uploaded to Pinterest, which processes it. The pin is created once processing finishes.'],
      ),
      h2('specs', 'What your video needs'),
      table(['', 'Pinterest allows', 'GoPinKaro accepts'], [
        ['File type', 'MP4, MOV or M4V', 'MP4, MOV or M4V'],
        ['Length', '4 seconds to 15 minutes', '4 seconds to 15 minutes'],
        ['Shape', 'Between 1:2 and 1.91:1 (width to height)', 'The same; 9:16, 2:3, 4:5 or square recommended'],
        ['File size', 'Up to 2 GB', `Up to ${FACTS.videoMaxMb} MB`],
        ['Encoding', 'H.264 or H.265', 'Checked by Pinterest during processing'],
      ], 'Pinterest limits are from its help pages. GoPinKaro\'s size limit is lower because videos are stored before upload; see our [video pin specs guide](/guides/pinterest-video-pin-specs).'),
      h2('processing', 'What happens when Pinterest is slow'),
      p('Pinterest processes every uploaded video before it can become a pin. If processing is not finished when GoPinKaro checks, the pin goes back in the queue and is tried again about every 90 seconds, without uploading the file a second time. If Pinterest rejects the video, the pin is marked failed with the reason, so you can fix the file and retry in one click.'),
      h2('limits', 'Honest limits'),
      ul(
        `Files above ${FACTS.videoMaxMb} MB are not accepted yet, which is roughly a minute of 1080p video.`,
        'Video pins are created from the New pin page. Bulk upload, CSV import and the assistant handle image pins.',
        'Pinterest decides how video is shown and promoted; scheduling does not change that.',
      ),
      h2('plans', 'Plans'),
      plansTable(),
    ],
    faqs: [
      { q: 'Can I schedule Pinterest video pins?', a: 'Yes. GoPinKaro uploads your MP4 or MOV to Pinterest at the scheduled time and publishes the pin once Pinterest has processed it.' },
      { q: 'What video formats and lengths work?', a: 'MP4, MOV or M4V, between 4 seconds and 15 minutes, with a width-to-height ratio between 1:2 and 1.91:1. Vertical 9:16, 2:3, 4:5 or square videos are recommended by Pinterest.' },
      { q: 'What is the maximum video size?', a: `Pinterest allows up to 2 GB; GoPinKaro currently accepts files up to ${FACTS.videoMaxMb} MB.` },
      { q: 'Is video included in the free plan?', a: `Yes. Video and carousel pins count towards the same monthly pin allowance as images (${free.pins} a month on Free).` },
      { q: 'What if Pinterest does not process my video?', a: 'The pin is retried while Pinterest is still processing. If Pinterest rejects the file, the pin shows the reason and can be retried after you fix the video.' },
    ],
    related: ['guides/pinterest-video-pin-specs', 'pinterest-carousel-pin-scheduler', 'pinterest-scheduler', 'use-cases/food-bloggers'],
    sources: [SRC.pinterestVideoSpecs, SRC.pinterestPinSpecs],
  },

  // ───────────────────────────────────────── carousel
  {
    path: 'pinterest-carousel-pin-scheduler',
    kind: 'product',
    label: 'Pinterest carousel pin scheduler',
    title: 'Pinterest carousel pin scheduler',
    description: 'Schedule Pinterest carousel pins of 2 to 5 images: reorder slides, set the cover, and publish at the right time. Included on every GoPinKaro plan, including Free.',
    h1: 'Schedule Pinterest carousel pins',
    intro: 'A carousel pin lets people swipe through 2 to 5 images in one pin. GoPinKaro lets you pick the images, reorder them, and schedule the carousel like any other pin. The first image is the cover and the thumbnail you see in your queue.',
    updated: CHECKED,
    published: CHECKED,
    cta: { label: 'Schedule a carousel', redirect: '/dashboard/schedule' },
    blocks: [
      h2('how', 'How to schedule a carousel'),
      steps(
        ['Choose Carousel', 'On the New pin page, switch the media tab to Carousel.'],
        ['Add 2 to 5 images', 'Drop in your images. Move any of them earlier or later; the first is the cover.'],
        ['Write the details', 'One title, description and destination link apply to the whole pin, with alt text and a board.'],
        ['Schedule it', 'Pick a time or a best-time slot. The carousel publishes as a single pin.'],
      ),
      h2('when', 'When a carousel is a good choice'),
      ul(
        'Step-by-step content: a recipe in stages, a room makeover before and after, a how-to.',
        'Product ranges: several colours or angles of one listing.',
        'Listicles where each slide is one item.',
        'Comparisons that need more than one image to explain.',
      ),
      h2('tips', 'Tips for better carousels'),
      ul(
        'Use images of the same size and shape so slides do not jump. Vertical 2:3 (1000 x 1500) is the usual choice for standard pins.',
        'Make the first image work on its own: it is what people see in the feed.',
        'Keep the title keyword-first and specific, as you would for a single image. See [how to find Pinterest keywords](/guides/how-to-find-pinterest-keywords).',
        `Design slides with the [pin designer](/pinterest-pin-maker) (${FACTS.designer.templates} layouts, ${FACTS.designer.palettes} color sets) if you do not have artwork yet.`,
      ),
      h2('limits', 'Limits'),
      ul(
        'Carousels must have between 2 and 5 images.',
        'Each image can be up to 20 MB (JPG, PNG, WEBP or GIF).',
        'Carousels are created from the New pin page; bulk upload and the assistant handle single-image pins.',
        'Pinterest decides how carousels are displayed.',
      ),
      h2('plans', 'Plans'),
      plansTable(),
    ],
    faqs: [
      { q: 'How many images can a Pinterest carousel have?', a: 'Between 2 and 5 images. GoPinKaro enforces that range.' },
      { q: 'Can I reorder the slides?', a: 'Yes. Move any image earlier or later before scheduling; the first image becomes the cover.' },
      { q: 'Do carousel pins use more of my monthly allowance?', a: 'No. A carousel counts as one pin, however many images it contains.' },
      { q: 'Can I schedule carousels in bulk?', a: 'Not yet. Carousels are created one at a time from the New pin page; bulk scheduling covers single-image pins.' },
    ],
    related: ['pinterest-video-pin-scheduler', 'pinterest-pin-maker', 'pinterest-scheduler', 'guides/pinterest-title-and-description-examples'],
    sources: [SRC.pinterestPinSpecs, SRC.imageSizeTailwind],
  },

  // ───────────────────────────────────────── multiple accounts
  {
    path: 'manage-multiple-pinterest-accounts',
    kind: 'product',
    label: 'Manage multiple Pinterest accounts',
    title: 'Manage multiple Pinterest accounts in one dashboard',
    description: `Run up to ${FACTS.accounts.business} Pinterest accounts from one GoPinKaro login: switch accounts, keep separate queues and analytics, and see which accounts need attention.`,
    h1: 'Manage multiple Pinterest accounts from one dashboard',
    intro: `One GoPinKaro login manages ${acct}. Each Pinterest account keeps its own boards, queue, calendar and analytics; you switch between them from the sidebar, and an Accounts page shows every account with its queue numbers and flags the ones that need attention. The monthly pin allowance is shared across accounts.`,
    updated: CHECKED,
    published: CHECKED,
    cta: { label: 'Connect your accounts', redirect: '/dashboard/accounts' },
    blocks: [
      h2('what', 'What you get'),
      ul(
        '**A searchable account switcher** in the sidebar and mobile header, built to stay usable with dozens of accounts.',
        '**An Accounts page** with totals across accounts, search, a "needs attention" filter, and one-click actions to rename, check, reconnect or remove an account.',
        '**Separate everything per account:** boards, scheduled pins, calendar, analytics, keyword results, duplicate checks and best posting times.',
        '**Pooled pricing:** the monthly pin allowance is shared by all accounts on your plan, so you pay for volume rather than per account.',
        '**An assistant that works on the selected account**, and says which one it is acting on.',
      ),
      h2('limits', 'Accounts by plan'),
      plansTable(),
      h2('adding', 'Adding an account'),
      steps(
        ['Sign in to the right Pinterest account', 'Pinterest connects whichever account you are signed in to on pinterest.com, so sign in to the account you want to add first (a private window works well).'],
        ['Choose Add account', 'On the Accounts page, press Add account and approve access on Pinterest\'s own page. GoPinKaro never sees the password.'],
        ['Name it', 'Give the account a short name, such as a client or niche, so it is easy to tell apart in the switcher.'],
      ),
      h2('safety', 'How sign-in and access work'),
      p('Signing in to GoPinKaro is decided only by the Pinterest account that created the login. Adding a client\'s account to your workspace does not let that client sign in to your workspace, and the same Pinterest account can be a secondary account in more than one login. You can remove an account at any time; its queue, history and analytics are deleted from GoPinKaro, and nothing is deleted on Pinterest.'),
      callout('Only connect accounts you own or are authorised to manage, and get a client\'s agreement before connecting their account.', 'Permission first'),
      h2('pinterest-rules', 'What Pinterest itself allows'),
      p('Pinterest has its own rules about how many accounts one person can hold and how they relate. As reported in Pinterest help, one email address can hold one personal and one business account, extra business accounts need separate emails, and linked business accounts are being phased out. Check Pinterest Help for the current position before creating accounts.'),
      h2('compare', 'How it compares on cost'),
      p(`Several tools charge per Pinterest account: Tailwind prices each account separately, and Buffer and Publer charge roughly $5 per account a month. At ten accounts that is about $50 a month, against $${FACTS.pro.price} for GoPinKaro Pro. See the [cost comparison](/cheapest-pinterest-scheduler) and the [guide for agencies](/use-cases/agencies).`),
    ],
    faqs: [
      { q: 'How many Pinterest accounts can I manage?', a: `${acct}. All from one login and one dashboard.` },
      { q: 'Is the pin allowance per account?', a: `No. The monthly allowance (Starter ${starter.pins}, Pro ${FACTS.pro.pins}, Business ${FACTS.business.pins}) is shared by all accounts on the login.` },
      { q: 'Can I schedule the same pin to several accounts?', a: 'Each account has its own boards, so you schedule per account. Switch accounts and schedule; the pacing check then looks at each account separately.' },
      { q: 'What happens if I downgrade and have too many accounts?', a: 'You will see a notice and cannot add more, but existing accounts keep publishing until you remove some or upgrade.' },
      { q: 'Does removing an account delete my pins on Pinterest?', a: 'No. It removes the account\'s queue, history and analytics from GoPinKaro. Pins already on Pinterest stay there.' },
    ],
    related: ['use-cases/agencies', 'guides/how-to-manage-multiple-pinterest-accounts', 'cheapest-pinterest-scheduler', 'buffer-alternative-for-pinterest'],
    sources: [SRC.pinterestAccountsHelp, SRC.metricoolMulti, SRC.tailwindPricing, SRC.bufferPricing],
  },

  // ───────────────────────────────────────── pin generator (from a URL)
  {
    path: 'pinterest-pin-generator',
    kind: 'product',
    label: 'Pinterest pin generator',
    title: 'Pinterest pin generator from a blog post or product page',
    description: 'Turn a blog post, product page or whole sitemap into drafted Pinterest pins: images found, titles and descriptions written, pin designs made, all reviewed by you.',
    h1: 'A Pinterest pin generator that starts from your website',
    intro: `Paste a page (or a whole sitemap on Pro and above) and GoPinKaro finds its images, drafts three title options, a description and alt text, and can design each pin from the page photo and title. You review everything, then schedule. The Free plan includes ${free.imports} page imports a month.`,
    updated: CHECKED,
    published: CHECKED,
    cta: { label: 'Turn a page into pins', redirect: '/dashboard/import' },
    blocks: [
      h2('flow', 'From URL to scheduled pins'),
      steps(
        ['Paste the address', 'A single page, or a sitemap to pick many pages from (Pro and above; up to 25 pages at a time).'],
        ['Review what it found', 'The page\'s images appear as choices. Pick the ones worth pinning.'],
        ['Edit the copy', 'Choose from three drafted titles, then edit the description and alt text. Limits of 100 and 800 characters are checked for you.'],
        ['Optionally design the pins', `Tick "Design each pin automatically" to turn each photo into a finished 1000 x 1500 pin with the page title on it, using ${FACTS.designer.templates} template layouts and ${FACTS.designer.palettes} color sets. This is a template layout, not AI.`],
        ['Choose a board and pace', 'Pick a board, then a fixed interval or best-time slots, and schedule the batch.'],
      ),
      h2('quality', 'What keeps it from producing junk'),
      ul(
        '**You review first.** Nothing is scheduled until you confirm.',
        '**Duplicate warnings.** You are told if you already have pins linking to the page, and near-duplicate titles are flagged.',
        `**Pacing check.** After scheduling, a crowded day (over ${FACTS.dailySoftMax} pins) or a repeated image is flagged.`,
        '**Original images.** Pins use the images from your own pages, so they match your content.',
      ),
      h2('ai', 'Where AI is and is not used'),
      p(`AI writes titles, descriptions and alt text, and can create an optional background picture in the pin designer (${FACTS.aiImages.free} on Free, ${FACTS.aiImages.starter} on Starter, ${FACTS.aiImages.pro} on Pro, ${FACTS.aiImages.business} on Business each month). Pinterest labels AI-modified images and lets people see fewer of them, so the automatic page design uses your own photos rather than generated images. See [Pinterest and AI-generated content](/guides/pinterest-ai-generated-content-rules).`),
      h2('limits', 'Limits to know'),
      ul(
        `Page imports are metered: ${free.imports} on Free, ${starter.imports} on Starter, ${FACTS.pro.imports} on Pro and ${FACTS.business.imports} on Business. A failed import is not counted.`,
        'Pages that load their images with JavaScript or hide them behind logins may show few images.',
        'The designer is template-based, so it suits text-led pins; use a design tool for custom artwork.',
      ),
      h2('plans', 'Plans'),
      plansTable(),
    ],
    faqs: [
      { q: 'Can I generate Pinterest pins from a blog post URL?', a: 'Yes. Paste the page address and GoPinKaro finds its images, drafts titles, a description and alt text, and can design each pin. You review and edit before scheduling.' },
      { q: 'Does it use AI to make the pin images?', a: 'Not for the automatic page design, which uses your own photos on a template layout. You can optionally create an AI background in the pin designer.' },
      { q: 'Can I import a whole website?', a: 'On Pro and above you can read a sitemap and import up to 25 pages at a time.' },
      { q: 'Will it create duplicate pins?', a: 'It warns you if you already have pins linking to the same page and flags near-duplicate titles, and it checks pacing and repeated images after you schedule.' },
    ],
    related: ['website-to-pinterest-pins', 'pinterest-pin-maker', 'pin-generator-alternative', 'pinboostr-alternative'],
    sources: [SRC.pinterestAiLabels],
  },
]
