import { FACTS, CHECKED, SRC } from './facts'
import { callout, h2, h3, p, plansTable, steps, table, ul, type SeoPage } from './types'

const { free, starter } = FACTS

export const productPages: SeoPage[] = [
  // ───────────────────────────────────────────────── /pinterest-scheduler
  {
    path: 'pinterest-scheduler',
    kind: 'product',
    label: 'Pinterest scheduler',
    title: "Pinterest scheduler: bulk schedule pins",
    description: `Schedule Pinterest pins in bulk, import pages from your website and publish at best-time slots. Free plan with ${free.pins} pins a month, paid plans from $${starter.price}.`,
    h1: 'A Pinterest scheduler built for bulk scheduling and automation',
    intro: `GoPinKaro is a Pinterest scheduler that publishes through the official Pinterest API. Upload images, import a CSV or paste a page from your site, review the pins, and GoPinKaro publishes them over the coming days at the pace you choose. The free plan includes ${free.pins} pins a month with no card, and paid plans start at $${starter.price} a month.`,
    updated: CHECKED,
    blocks: [
      h2('what-it-does', 'What a Pinterest scheduler does'),
      p('A Pinterest scheduler lets you prepare pins ahead of time and publish them automatically on dates you choose. Pinterest rewards steady, regular pinning, and a scheduler turns a weekly batch of work into a feed that keeps publishing while you do other things.'),
      p('Pinterest has a built-in scheduler, and it is a good starting point. A third-party scheduler becomes worth it when you need to queue more than a handful of pins, schedule more than a month ahead, or create many pins at once.'),
      h2('features', 'What GoPinKaro includes'),
      ul(
        `**Bulk scheduling.** Add up to ${FACTS.bulkMax} images at once, or import a CSV with the columns image_url, title, description and link. Review every pin on one screen, pick a board and a spacing, then schedule the whole batch with one click.`,
        '**Website to pins.** Paste a blog post, product page or, on Pro and above, a whole sitemap. GoPinKaro finds the images on the page and drafts titles, descriptions and alt text that you edit before anything is scheduled.',
        '**Best-time slots.** Choose how many pins a day you want and GoPinKaro spreads them over afternoon and evening hours in your own timezone, with natural minute offsets instead of posting exactly on the hour.',
        '**A live queue.** Pin statuses (scheduled, publishing, published, failed) update the moment they change, with no page refresh. A calendar shows the month at a glance.',
        '**Automatic retries.** Temporary Pinterest errors are retried with increasing delays. If a pin still fails, you see the reason and can fix and retry it in one click.',
        '**AI assistant.** Describe what you want in chat, for example "turn this blog post into five pins and schedule them at three a day". It plans the work and asks you to confirm before anything is created or changed.',
        '**Duplicate warnings.** GoPinKaro compares a new pin with your recent pins and warns you when it is nearly identical, so you do not repost the same content by accident.',
      ),
      h2('how-it-works', 'How to schedule your first batch'),
      steps(
        ['Connect Pinterest', 'Sign in with your Pinterest account. Your Pinterest login is your GoPinKaro login, so there is no password to manage.'],
        ['Add your pins', 'Upload images, import a CSV, or paste a page URL. Write or edit titles and descriptions. The AI writer can suggest three options for any topic.'],
        ['Pick a board and a pace', `Choose a board, then either a fixed interval (for example one pin every 6 hours) or best-time slots (1 to 10 pins a day on paid plans).`],
        ['Schedule', `Confirm and the pins are queued. You can schedule up to ${FACTS.scheduleAheadDays} days ahead. Edit, move or delete any pin until it publishes.`],
      ),
      h2('best-times', 'How best-time scheduling works'),
      p('Best-time slots are generated from your timezone, which GoPinKaro detects on your first visit and you can change in Settings. For one pin a day it picks an evening slot; as you raise the number of pins per day it adds more afternoon, morning and later-evening slots. Each slot gets a small minute offset so pins do not all appear on the hour.'),
      callout('These slots are sensible defaults for the usual daily rhythm of an audience, not a prediction from your own analytics. Check the Analytics page after a few weeks and adjust the pace to what your pins actually do.', 'Be realistic about "best time"'),
      h2('limits', 'Plans and limits'),
      p('Limits are enforced when you schedule, so you always know what is left. Pins are counted in the month they are scheduled to publish.'),
      plansTable(),
      h2('native-vs-us', "Pinterest's built-in scheduler compared"),
      table(
        ['', "Pinterest's scheduler", 'GoPinKaro'],
        [
          ['Cost', 'Free with a Pinterest business account', `Free plan, then from $${starter.price} a month`],
          ['Scheduling horizon', 'Up to 30 days ahead', `Up to ${FACTS.scheduleAheadDays} days ahead`],
          ['Queue size', 'Up to 10 scheduled pins at a time, one pin at a time', `${FACTS.freeBatchMax} pins per request on Free, up to ${FACTS.bulkMax} on paid plans, with CSV import`],
          ['Create pins from a web page', 'No', 'Yes, single page or sitemap'],
          ['Suggested posting times', 'No', 'Yes, on paid plans'],
          ['Design tools', 'Pin builder', 'None. Bring your images, for example from Canva'],
        ],
        'Pinterest scheduler limits as reported in the sources below, October 2026. Pinterest can change them.'
      ),
      h2('who-for', 'Who it is for, and who it is not'),
      p('GoPinKaro suits bloggers, online shops and creators who publish new pages or products regularly and want pins to follow automatically. It is a good fit if you want to turn a content library into a steady pin queue.'),
      p(`It is not the right tool if you want to publish to Instagram, Facebook or other networks (GoPinKaro is Pinterest only), if you need more than ${FACTS.accounts.business} Pinterest accounts, or if you want a full design studio (it has a template-based pin designer).`),
    ],
    faqs: [
      { q: 'What is the best Pinterest scheduler?', a: `It depends on your workflow. Pinterest's built-in scheduler is free and enough for a few pins a week. If you want to bulk schedule, import pages from your website, or queue pins more than a month ahead, a dedicated scheduler such as GoPinKaro is a better fit. GoPinKaro starts free with ${free.pins} pins a month.` },
      { q: 'How are best times chosen?', a: `From general Pinterest patterns at first: evening and afternoon hours in your own timezone, with small minute offsets so pins do not land on the hour. Once an account has about ${FACTS.personalTimingPins} published pins with results, GoPinKaro starts ranking hours from that account's own results, cautiously, because the hour matters far less than the pin itself. Pick exact times or a fixed interval whenever you know better.` },
      { q: 'Is GoPinKaro free?', a: `Yes. The Free plan includes ${free.pins} pins a month, ${free.imports} website page imports and ${free.ai} AI writing generations. No card is needed. Paid plans start at $${starter.price} a month.` },
      { q: 'Does GoPinKaro use the official Pinterest API?', a: 'Yes. You connect with Pinterest sign-in and approve the permissions. GoPinKaro publishes the pins you schedule through the official API. Access tokens are stored encrypted.' },
      { q: 'Can I schedule pins for next month?', a: `Yes, up to ${FACTS.scheduleAheadDays} days ahead. Pinterest's own scheduler is limited to 30 days ahead.` },
      { q: 'What happens if a pin fails to publish?', a: 'Temporary errors such as Pinterest being briefly unavailable are retried automatically with increasing delays. If a pin still fails you see the exact reason in your Pins list and can fix it and retry in one click.' },
      { q: 'Can I connect more than one Pinterest account?', a: `Yes. One login can manage ${FACTS.accounts.free} account on Free, ${FACTS.accounts.starter} on Starter, ${FACTS.accounts.pro} on Pro and ${FACTS.accounts.business} on Business. Each account keeps its own boards, queue, calendar and analytics, you switch between them in the sidebar, and the monthly pin allowance is shared across them.` },
    ],
    related: ['pinterest-bulk-scheduler', 'free-pinterest-scheduler', 'best-pinterest-tools', 'guides/how-to-schedule-pinterest-pins'],
    sources: [SRC.nativeLimits, SRC.pinterestCommunity],
  },

  // ───────────────────────────────────────────────── /pinterest-automation-tool
  {
    path: 'pinterest-automation-tool',
    kind: 'product',
    label: 'Pinterest automation tool',
    title: "Pinterest automation tool: website to pins",
    description: 'Automate Pinterest pin creation and scheduling: import a page or sitemap, review AI-written titles and descriptions, and let GoPinKaro publish on a steady schedule.',
    h1: 'Pinterest automation that keeps you in control',
    intro: 'A Pinterest automation tool should remove repetitive work without publishing things you have not seen. GoPinKaro automates the slow parts (finding images, drafting titles and descriptions, spreading pins over days, retrying failures) and leaves approval to you.',
    updated: CHECKED,
    blocks: [
      h2('what-to-automate', 'What is worth automating on Pinterest'),
      p('Pinterest work falls into repeatable chores and judgment calls. Automate the chores: collecting images from a page, writing a first draft of each title and description, choosing publish times, and re-trying a publish that failed. Keep the judgment calls with a person: which pages deserve pins, whether the image is good, and whether the wording sounds right.'),
      h2('workflow', 'The GoPinKaro automation workflow'),
      steps(
        ['Import', `Paste a page URL, or a sitemap on Pro and above. Up to ${FACTS.importBatchMax} pages can be imported in one batch. GoPinKaro reads the page, pulls the usable images and writes three title options, a description and alt text.`],
        ['Review', 'Every pin appears in an editor. Pick the title you like, rewrite anything, remove images you do not want. Nothing is scheduled yet.'],
        ['Schedule', 'Pick a board and either a fixed interval or best-time slots. The whole batch is queued in one step.'],
        ['Publish and retry', 'Pins publish at their scheduled time. Temporary Pinterest errors are retried automatically, and a pin that cannot be published is flagged with the reason.'],
      ),
      h2('assistant', 'Automate by chatting'),
      p('The built-in assistant can do the same work from a chat message. Ask it to import a page, schedule pins at a pace, move pins to evenings, retry everything that failed, create a board, or report how your pins are doing. It can read your queue, boards and analytics on its own.'),
      callout('Anything that changes your account (scheduling, editing, deleting, creating a board, changing a setting) is shown as a confirmation card first. Nothing happens until you press Confirm, and each confirmation can only be used once.', 'Confirm before it acts'),
      h2('safe-automation', 'Automation without getting spammy'),
      ul(
        '**Review before you schedule.** Pins are drafts until you confirm them.',
        '**Duplicate warnings.** If a new pin is nearly identical to a recent one, GoPinKaro warns you.',
        '**Steady pace.** Spread pins over days instead of publishing a big batch at once. One to five pins a day is a sensible range for most accounts.',
        '**Official API only.** GoPinKaro publishes through the Pinterest API using the permissions you approve. It does not log in as you or use browser tricks.',
      ),
      p('You remain responsible for following Pinterest community guidelines and for the content you publish.'),
      h2('free-automation', 'Is there a free Pinterest automation tool?'),
      p(`GoPinKaro has a free plan with ${free.pins} pins a month, ${free.imports} website imports and ${free.ai} AI generations. Automatic best-time scheduling, bulk import and sitemap import are on paid plans. Pinterest's built-in scheduler is also free if you only need a small queue.`),
    ],
    faqs: [
      { q: 'What is the best Pinterest automation tool?', a: 'The best tool depends on how much you want to automate. For turning a website into a steady stream of pins with human review, GoPinKaro is built for that workflow. GoPinKaro includes a template-based pin designer; for design-heavy workflows, pair a scheduler with a design tool such as Canva.' },
      { q: 'Can a Pinterest automation tool create pins from my blog?', a: 'Yes. GoPinKaro reads a page, finds its images and drafts titles, descriptions and alt text. You review and edit before scheduling.' },
      { q: 'Will Pinterest ban me for using automation?', a: 'GoPinKaro only uses the official Pinterest API and schedules the pins you approve. Pinterest can restrict accounts that post spam or repetitive low-quality content, so keep a steady pace, vary your pins and follow the community guidelines.' },
      { q: 'Does it post without my approval?', a: 'No. Pins are only scheduled after you review them. The assistant also asks you to confirm before it changes anything.' },
      { q: 'Are there free Pinterest automation tools?', a: `Yes. GoPinKaro's free plan includes ${free.pins} pins a month, and Pinterest's own scheduler is free. Free plans are limited, so check whether the limits fit your volume.` },
    ],
    related: ['website-to-pinterest-pins', 'pinterest-bulk-scheduler', 'pinterest-scheduler', 'guides/how-often-to-pin-on-pinterest'],
  },

  // ───────────────────────────────────────────────── /pinterest-bulk-scheduler
  {
    path: 'pinterest-bulk-scheduler',
    kind: 'product',
    label: 'Pinterest bulk scheduler',
    title: "Pinterest bulk scheduler: CSV and images",
    description: `Bulk schedule Pinterest pins: add up to ${FACTS.bulkMax} images or a CSV, edit every pin on one screen, and space them with a fixed interval or best-time slots.`,
    h1: 'Bulk schedule Pinterest pins from images or a CSV',
    intro: `Pinterest's own scheduler schedules one pin at a time. GoPinKaro's bulk scheduler lets you add up to ${FACTS.bulkMax} pins in one go, from image uploads or a CSV file, review them all on one screen, and schedule the entire batch with a single spacing rule.`,
    updated: CHECKED,
    blocks: [
      h2('two-ways', 'Two ways to bulk add pins'),
      h3('Upload images'),
      p(`Select up to ${FACTS.bulkMax} image files (JPG, PNG, WEBP or GIF, each up to ${FACTS.imageMaxMb} MB). Each image becomes a draft pin with a title taken from the file name that you can rewrite. Images are uploaded to your own folder in GoPinKaro storage and served from a public link, because Pinterest has to be able to fetch each image.`),
      h3('Import a CSV'),
      p('If your images are already online, import a CSV with these columns. Image links must start with https.'),
      table(['Column', 'Required', 'What it is'], [
        ['image_url', 'Yes', 'A public https link to the image'],
        ['title', 'No', `The pin title, up to ${FACTS.titleMax} characters`],
        ['description', 'No', `The pin description, up to ${FACTS.descriptionMax} characters`],
        ['link', 'No', 'The destination URL the pin points to'],
      ]),
      p('A template file is available on the Bulk schedule page.'),
      h2('spacing', 'Choose how the batch is spaced'),
      table(['Option', 'How it works', 'Plan'], [
        ['Fixed interval', 'Pick a first publish time and a gap (for example one pin every 6 hours).', 'All plans'],
        ['Best times', 'Pick 1 to 10 pins a day. Pins are placed in afternoon and evening slots in your timezone, starting after your last scheduled pin.', 'Paid plans'],
      ]),
      callout(`On the Free plan you can add up to ${FACTS.freeBatchMax} pins per request. Paid plans can schedule up to ${FACTS.bulkMax} pins at a time.`, 'Batch size'),
      h2('review', 'Review before you commit'),
      p('Every pin shows its image, title, description and link in an editable row. Remove a pin, fix a title, or paste in a destination URL. The page shows when the last pin in the batch will go out, so you know how many days of content you are scheduling.'),
      h2('checks', 'Checks that protect your account'),
      ul(
        `**Monthly limit, enforced atomically.** A batch is accepted completely or not at all, so you never end up with half a batch scheduled.`,
        '**Duplicate warnings.** New pins are compared with your recent pins to catch near-identical content.',
        '**Retries.** If Pinterest has a temporary problem, affected pins are retried automatically instead of being dropped.',
      ),
      h2('plans', 'Bulk scheduling by plan'),
      plansTable(),
    ],
    faqs: [
      { q: 'How many pins can I bulk schedule at once?', a: `Up to ${FACTS.bulkMax} pins per batch on paid plans, and up to ${FACTS.freeBatchMax} per request on the Free plan. Your monthly pin limit also applies.` },
      { q: 'Can I bulk schedule from a spreadsheet?', a: 'Yes. Export a CSV with the columns image_url, title, description and link and import it on the Bulk schedule page.' },
      { q: 'Does Pinterest allow bulk scheduling?', a: "Pinterest's built-in scheduler works one pin at a time. Third-party schedulers that use the official Pinterest API can queue many pins, which is what GoPinKaro does." },
      { q: 'Can I put every pin on a different board?', a: 'In the bulk editor you choose one board for the batch. You can change the board of individual pins afterwards from your Pins list, or ask the assistant to move several pins to another board.' },
      { q: 'What image formats can I upload?', a: `JPG, PNG, WEBP and GIF, up to ${FACTS.imageMaxMb} MB each. Vertical images with a 2:3 ratio, such as 1000 by 1500 pixels, are recommended.` },
    ],
    related: ['pinterest-scheduler', 'guides/pinterest-image-size-and-specs', 'website-to-pinterest-pins', 'free-pinterest-scheduler'],
  },

  // ───────────────────────────────────────────────── /free-pinterest-scheduler
  {
    path: 'free-pinterest-scheduler',
    kind: 'product',
    label: 'Free Pinterest scheduler',
    title: "Free Pinterest scheduler: what you get",
    description: `A plain comparison of free ways to schedule Pinterest pins: Pinterest's built-in scheduler and GoPinKaro's free plan with ${free.pins} pins a month.`,
    h1: 'The best free Pinterest scheduler for your situation',
    intro: `There are two good free options. Pinterest's built-in scheduler costs nothing and suits a few pins a week. GoPinKaro's free plan gives you ${free.pins} pins a month, ${free.imports} website imports and an AI writer with no card required. Here is how to choose.`,
    updated: CHECKED,
    blocks: [
      h2('options', 'Free options compared'),
      table(['', "Pinterest's built-in scheduler", 'GoPinKaro Free plan'], [
        ['Price', 'Free', 'Free, no card'],
        ['How far ahead', 'Up to 30 days', `Up to ${FACTS.scheduleAheadDays} days`],
        ['Queue limit', 'Up to 10 scheduled pins at a time', `${free.pins} pins a month`],
        ['Add several pins at once', 'No, one at a time', `Up to ${FACTS.freeBatchMax} per request`],
        ['Create pins from a web page', 'No', `${free.imports} imports a month`],
        ['AI writing help', 'No', `${free.ai} generations a month`],
        ['Best-time slots', 'No', 'Paid plans'],
        ['Analytics', 'Pinterest analytics', 'Account totals for the last 7 days'],
      ], 'Pinterest scheduler limits as reported in the sources below, October 2026.'),
      h2('choose-native', "When Pinterest's built-in scheduler is enough"),
      p('If you publish a few new pins a week and are happy to create each one in the pin builder, you do not need another tool. It is free, built in and requires no connection to anything else.'),
      h2('choose-free-plan', 'When GoPinKaro Free is a better fit'),
      ul(
        'You want to turn blog posts or product pages into pins without writing every title by hand.',
        `You want to schedule more than a month ahead (up to ${FACTS.scheduleAheadDays} days).`,
        `You want to add several pins at once (up to ${FACTS.freeBatchMax} per request) and see them all in one queue and calendar.`,
        'You want a second opinion on titles and descriptions from the AI writer.',
      ),
      h2('when-to-pay', 'When a paid plan makes sense'),
      p(`Move up when ${free.pins} pins a month is not enough, when you want bulk and CSV scheduling, best-time slots, or sitemap import. Starter is $${starter.price} a month ($${starter.yearly} a year) for ${starter.pins} pins a month.`),
      plansTable(),
      h2('other-free', 'Other free tools worth knowing'),
      ul(
        '**Pinterest Trends** is free and shows what people are searching for, which helps you choose topics and keywords.',
        '**Canva** has a free tier for designing vertical pin images.',
        '**Free tiers of other schedulers** exist, usually with tight pin limits. Check their current limits before relying on them.',
      ),
    ],
    faqs: [
      { q: 'Is there a completely free Pinterest scheduler?', a: "Yes. Pinterest's built-in scheduler is free, and GoPinKaro has a free plan with no card required. Both have limits." },
      { q: 'What are the limits of the free Pinterest scheduler?', a: "Pinterest's built-in scheduler lets you schedule one pin at a time, up to 30 days ahead, with up to 10 pins scheduled at once, according to the sources below. Pinterest can change these limits." },
      { q: 'What is the best Pinterest tool for free?', a: `For scheduling, use Pinterest's built-in scheduler for a small queue, or GoPinKaro's free plan (${free.pins} pins a month) if you want website import and AI help. For design, Canva has a free tier. For research, Pinterest Trends is free.` },
      { q: 'Do I need a business account?', a: "Pinterest's scheduler is described as available with business accounts. GoPinKaro connects through Pinterest sign-in; check Pinterest's help center for account requirements that apply to you." },
    ],
    related: ['pinterest-scheduler', 'guides/pinterest-native-scheduler-limits', 'best-pinterest-tools', 'pinterest-keyword-tool'],
    sources: [SRC.nativeLimits, SRC.pinterestCommunity],
  },

  // ───────────────────────────────────────────────── /pinterest-keyword-tool
  {
    path: 'pinterest-keyword-tool',
    kind: 'product',
    label: 'Pinterest keyword tool',
    title: "Pinterest keyword tool: trending keywords",
    description: 'See what is trending on Pinterest. Find rising keywords by region with weekly, monthly and yearly growth from Pinterest Trends, then write pins around them.',
    h1: 'Find trending Pinterest keywords for your pins',
    intro: 'Pinterest works like a visual search engine, so the words in your titles, descriptions and board names decide whether people find your pins. GoPinKaro includes a keyword tool that shows trending Pinterest searches with their growth, so you can write titles around what people are looking for.',
    updated: CHECKED,
    blocks: [
      h2('how-it-works', 'How the keyword tool works'),
      p('The tool reads Pinterest Trends data through the Pinterest API. For a region you choose, it lists keywords that are trending on Pinterest, with how much their search volume has grown compared with the previous week, month and year. You can filter the list by a word, for example "kitchen", to see trends in your niche. Results are cached for six hours.'),
      table(['Column', 'Meaning'], [
        ['Keyword', 'A search phrase people are using on Pinterest'],
        ['Week', 'Growth in search volume compared with the previous week'],
        ['Month', 'Growth compared with the previous month'],
        ['Year', 'Growth compared with the same period a year ago'],
      ]),
      callout('The tool shows trend direction, not absolute search volume. Use it to pick up rising topics early and to check whether a topic is growing or fading.', 'What it does not do'),
      h2('where-to-use', 'Where to use keywords on Pinterest'),
      ul(
        '**Pin titles.** Put the main keyword first. Only the start of a long title is visible in the feed.',
        '**Pin descriptions.** Use two or three related phrases naturally, written as a sentence a person would read.',
        '**Board names and descriptions.** Boards are searchable too, so name them with the phrase your audience would type.',
        '**Alt text.** Describe the image plainly. It helps accessibility and gives Pinterest more context.',
      ),
      h2('with-ai', 'From keyword to finished pin'),
      p('Pick a rising keyword, then give it to the AI writer or the assistant. It drafts three title and description options built around the topic, and you edit them before scheduling. The writer is designed to produce natural wording, not keyword stuffing.'),
      h2('regions', 'Regions available'),
      p('You can check trends for the United States, Canada, United Kingdom, Australia, Germany, France, Brazil and Mexico, among others offered in the tool. Keyword trends differ by country, so check the region your audience is in.'),
      h2('free', 'Is it free?'),
      p(`The keyword tool is available on every plan, including Free. It needs your Pinterest account to be connected because the data comes from the Pinterest API.`),
    ],
    faqs: [
      { q: 'What is the best Pinterest keyword tool?', a: 'Pinterest Trends itself is the most direct source and is free. GoPinKaro shows Pinterest Trends data inside your scheduling workflow. Dedicated research tools such as PinClicks and Pin Inspector go further, with search volume estimates and competitor research, and are paid.' },
      { q: 'Is there a free Pinterest keyword tool?', a: 'Yes. Pinterest Trends is free, and GoPinKaro includes a trending keywords tool on its free plan.' },
      { q: 'What are the best keywords for Pinterest?', a: 'The best keywords are the phrases your audience actually searches for and that match what your pin is about. Start from rising trends in your niche, write them naturally into titles, descriptions and board names, and avoid repeating the same phrase over and over.' },
      { q: 'Does it show search volume?', a: 'It shows growth compared with the previous week, month and year rather than absolute volume.' },
    ],
    related: ['guides/pinterest-seo-basics', 'pinterest-scheduler', 'best-pinterest-tools', 'free-pinterest-scheduler'],
  },

  // ───────────────────────────────────────────────── /website-to-pinterest-pins
  {
    path: 'website-to-pinterest-pins',
    kind: 'product',
    label: 'Website to Pinterest pins',
    title: "Turn blog posts into Pinterest pins",
    description: 'Paste a page or a sitemap and GoPinKaro finds the images and drafts Pinterest titles, descriptions and alt text. Review, then schedule the pins over days or weeks.',
    h1: 'Turn your website into Pinterest pins',
    intro: 'Pinterest sends traffic to pages that have pins. GoPinKaro reads a page of your site, finds its images and drafts the titles, description and alt text for each pin, so a blog post or product page becomes a set of scheduled pins in a few minutes instead of an afternoon.',
    updated: CHECKED,
    blocks: [
      h2('single-page', 'Import a single page'),
      steps(
        ['Paste the URL', 'Use any public blog post, product page or landing page. GoPinKaro fetches the page, reads its title and description, and collects the usable images.'],
        ['Pick the images', 'Small icons, logos and tracking images are filtered out. Check the images you want to pin. The page title and description become the starting point for the copy.'],
        ['Choose a title', 'Three title options and a description are written for you. Pick one or rewrite it. An alt text is drafted too.'],
        ['Review and schedule', 'Every selected image becomes a pin that links back to the page. Pick a board and a pace and schedule the batch.'],
      ),
      h2('sitemap', 'Import a whole sitemap'),
      p(`On the Pro plan and above, paste your website address and GoPinKaro reads your sitemap and lists the pages it finds. Select up to ${FACTS.importBatchMax} pages at a time, import them, and review all the pins in one editor. This is how a library of old posts becomes weeks of scheduled pins.`),
      h2('quality', 'What makes the drafts good'),
      ul(
        'Titles put the main keyword first and stay within the length Pinterest displays.',
        'Descriptions read as natural sentences with a soft call to action and a few hashtags.',
        'Alt text describes the image rather than repeating keywords.',
        'Page text is treated as data only, so instructions hidden in a page cannot change how GoPinKaro behaves.',
      ),
      callout('Pinterest favors pins that are fresh and useful. Create more than one image per page where you can, with different layouts or headlines, instead of repeating the same image.', 'Tip'),
      h2('limits', 'Limits'),
      table(['Plan', 'Page imports per month', 'Sitemap import'], [
        ['Free', String(free.imports), 'No'],
        ['Starter', '100', 'No'],
        ['Pro', '600', 'Yes'],
        ['Business', '3,000', 'Yes'],
      ]),
      p('GoPinKaro only reads public pages. Pages behind a login, private addresses and local network addresses are blocked.'),
    ],
    faqs: [
      { q: 'Can I create Pinterest pins from a URL?', a: 'Yes. Paste a public page URL into GoPinKaro and it finds the images and drafts titles, descriptions and alt text for you to edit and schedule.' },
      { q: 'Does it work with Shopify, Etsy, WordPress and other platforms?', a: 'It works with any public web page, including WordPress posts and product pages, as long as the page has images the importer can read. Results depend on how the page is built.' },
      { q: 'Does it create the pin images?', a: `Not automatically. Website import uses the images that already exist on your page. To make a new vertical pin, use the pin designer (${FACTS.designer.templates} templates) or a design tool such as Canva, then upload it.` },
      { q: 'Can it import my whole blog?', a: 'On Pro and above you can read your sitemap, choose up to 25 pages at a time and import them, then schedule the pins over days or weeks.' },
      { q: 'Will it write the same description for every pin?', a: 'Each imported page gets its own drafted copy. For several images from one page, the pins share the page-level title and description unless you edit them, so vary the wording where you can.' },
    ],
    related: ['pinterest-automation-tool', 'pinterest-bulk-scheduler', 'use-cases/bloggers', 'use-cases/shopify-stores'],
  },

  // ───────────────────────────────────────────────── /pinterest-pin-maker
  {
    path: 'pinterest-pin-maker',
    kind: 'product',
    label: 'Pinterest pin maker',
    title: 'Free Pinterest pin maker with templates',
    description: `Make a Pinterest pin from a template in under a minute: ${FACTS.designer.templates} layouts, ${FACTS.designer.palettes} color sets, your own photo, saved at ${FACTS.designer.width} x ${FACTS.designer.height}. Included on every GoPinKaro plan, including free.`,
    h1: 'A free Pinterest pin maker that goes straight to your schedule',
    intro: `GoPinKaro's pin designer turns a headline into a ${FACTS.designer.width} x ${FACTS.designer.height} pin image, the 2:3 size Pinterest recommends. Choose one of ${FACTS.designer.templates} layouts and ${FACTS.designer.palettes} color sets, add your own photo if you like, then download the image or schedule it in one click. It is included on every plan, free or paid; you sign in with Pinterest to use it.`,
    updated: CHECKED,
    blocks: [
      h2('how', 'How it works'),
      steps(
        ['Pick a layout', 'Bold headline, photo card, photo with a text panel, or a big number for list pins.'],
        ['Write the headline', `Up to ${90} characters. Short and specific reads best on a pin, and the text resizes itself to fit.`],
        ['Add a photo and colors', 'Optional. Upload your own photo for the photo layouts, and choose a color set.'],
        ['Download or schedule', `Download the ${FACTS.designer.width} x ${FACTS.designer.height} image, or send it to the new-pin form with your headline already filled in as the title and alt text.`],
      ),
      h2('layouts', 'The layouts'),
      table(['Layout', 'Best for', 'Needs a photo'], [
        ['Bold headline', 'Tips, quotes and listicle titles on a solid color', 'No'],
        ['Photo card', 'Recipes, decor and products, with the title on a card over your photo', 'Optional'],
        ['Photo + panel', 'A tall photo with the title below it', 'Optional'],
        ['Big number', 'Pins such as "12 indoor plants" where the number is the hook', 'No'],
      ]),
      h2('specs', 'Size and format'),
      p(`Designs are ${FACTS.designer.width} x ${FACTS.designer.height} pixels, a 2:3 vertical ratio that Pinterest guides recommend for standard pins. Flat designs are saved as PNG and designs with a photo as JPG, both well under the ${FACTS.imageMaxMb} MB upload limit.`),
      h2('not', 'What it does not do'),
      ul(
        'It is not a full design studio: there are no custom fonts, stock photo library, layers or multi-page designs. For custom artwork, design in Canva and upload the image.',
        'It does not use AI to generate images. Your text is placed as you type it, which also avoids the "AI modified" labels Pinterest now applies to generated images.',
        'It makes one pin at a time. To schedule many images at once, use the bulk scheduler.',
      ),
      h2('then', 'After the design'),
      p('The new-pin form opens with your image attached, your headline as the title and alt text, and the AI writer on hand for a description. Pick a board, a time (or best-time slots on paid plans), and the pin joins your queue. After you schedule, GoPinKaro flags a crowded day or a repeated image.'),
      plansTable(),
    ],
    faqs: [
      { q: 'Is the GoPinKaro pin maker free?', a: 'Yes. The pin designer is available on every plan, including Free. You need to sign in with your Pinterest account.' },
      { q: 'What size is the pin it makes?', a: `${FACTS.designer.width} x ${FACTS.designer.height} pixels, a 2:3 vertical ratio that Pinterest guides recommend for standard pins.` },
      { q: 'Can I use my own photos?', a: 'Yes. The photo card and photo with panel layouts accept your own JPG, PNG or WEBP image. The photo stays in your browser until you choose to schedule the pin.' },
      { q: 'Does the pin maker use AI?', a: 'No. It is a template layout tool, and the headline is exactly what you type. GoPinKaro has a separate AI writer for titles and descriptions.' },
      { q: 'Can I download the pin and use it elsewhere?', a: 'Yes. Download saves the image to your device as a PNG or JPG.' },
    ],
    related: ['pinterest-scheduler', 'guides/pinterest-image-size-and-specs', 'pinterest-bulk-scheduler', 'best-pinterest-tools'],
    sources: [SRC.imageSizeTailwind, SRC.imageSizePubler],
  },
]
