import { FACTS, CHECKED, SRC } from './facts'
import { callout, h2, ol, p, plansTable, table, ul, type SeoPage } from './types'

const { free, starter } = FACTS

export const usPages: SeoPage[] = [
  // ───────────────────────────────────────── best schedulers
  {
    path: 'best-pinterest-schedulers',
    kind: 'comparison',
    label: 'Best Pinterest schedulers',
    title: 'Best Pinterest schedulers in 2026 (by need)',
    description: 'The best Pinterest schedulers for 2026, picked by need: free, AI pin creation, multi-network, visual planning, reporting, many accounts and enterprise, with prices.',
    h1: 'The best Pinterest schedulers in 2026, by what you need',
    intro: 'There is no single best Pinterest scheduler, only the best one for your situation. Below are the tools worth considering, grouped by need, with US-dollar prices from each vendor\'s own pages. We make GoPinKaro, so we say plainly where another tool fits better.',
    updated: CHECKED,
    published: CHECKED,
    cta: { label: 'Try GoPinKaro on the Free plan', redirect: '/dashboard' },
    blocks: [
      h2('how', 'How we picked'),
      ul(
        '**It publishes through Pinterest\'s official API.** Tools that ask for your password are excluded. See our [safety checklist](/safest-pinterest-scheduler).',
        '**Prices are from the vendors\' own pages** where we could read them, dated October 2026. Verify before buying.',
        '**Disclosure:** GoPinKaro is our product. We list it where it fits and name better options elsewhere.',
      ),
      h2('picks', 'Best by need'),
      table(['Need', 'Pick', 'From', 'Why'], [
        ['Free, light use', 'Pinterest\'s built-in scheduler or GoPinKaro Free', 'Free', `Built-in is one pin at a time, 10 queued; GoPinKaro Free gives ${free.pins} pins a month with bulk import`],
        ['Most established Pinterest tool', 'Tailwind', '$17.99 a month billed yearly', 'Pinterest-focused suite with scheduling, design and SEO add-ons; credits and per-account pricing'],
        ['Pins created for you from your site', 'BlogToPin or PinBoostr', '$25 / $19.99 a month', 'Generate pins automatically; weigh the AI-image trade-off'],
        ['Several networks, lowest cost', 'Buffer or Publer', '$5 per channel / about $4 to $5 per account', 'Simple and cheap for one or two accounts'],
        ['Visual feed planning', 'Later or Planoly', '$18.75 / $14', 'Calendar and grid planning, Instagram-first'],
        ['Reporting and competitor analytics', 'Metricool', 'Free, then about $20 to $36', 'Cross-network analytics; free plan with 1 brand'],
        ['Bulk scheduling and many Pinterest accounts', 'GoPinKaro', `$${starter.price} a month`, `${starter.pins} to ${FACTS.business.pins} pins a month across up to ${FACTS.accounts.business} accounts on flat plans`],
        ['Enterprise teams and approvals', 'Hootsuite (or Metricool Advanced)', '$99 a month billed yearly', 'Approval workflows, inbox, listening; costly for Pinterest alone'],
      ], 'Prices from vendor pages, October 2026; Publer from roundups. Confirm current prices before buying.'),
      h2('details', 'The detail behind each pick'),
      p('**Tailwind** is the long-standing Pinterest specialist, with scheduling, design tools and optional SEO and engagement add-ons. Its plans include a monthly credit allowance shared by AI and creation features and are priced per Pinterest account. See our [Tailwind alternative](/tailwind-alternative) page.'),
      p('**BlogToPin and PinBoostr** generate pins from your website, which saves the most time on large sites. Both rely on AI-generated or templated images, and Pinterest labels AI-modified images, so check how those pins perform. See [BlogToPin](/blogtopin-alternative) and [PinBoostr](/pinboostr-alternative).'),
      p('**Buffer and Publer** are inexpensive multi-network schedulers. They are cheapest for a single Pinterest account, and per-account pricing adds up at scale. See [Buffer](/buffer-alternative-for-pinterest) and [Publer](/publer-alternative-for-pinterest).'),
      p('**Later and Planoly** suit people planning Instagram and Pinterest together, with visual calendars. See [Later](/later-alternative-for-pinterest) and [Planoly](/planoly-alternative-for-pinterest).'),
      p('**Metricool** pairs scheduling with analytics and competitor tracking. See [Metricool](/metricool-alternative-for-pinterest).'),
      p(`**GoPinKaro** is Pinterest-only and built for volume: bulk and CSV scheduling, page and sitemap import, video and carousel pins, a pacing check, and up to ${FACTS.accounts.business} accounts. It has no team seats or approvals today.`),
      p('**Hootsuite** is an enterprise suite for teams that need approvals and listening. See [Hootsuite](/hootsuite-alternative-for-pinterest).'),
      h2('choose', 'A quick way to decide'),
      ol(
        'How many Pinterest accounts do you run? One: almost any tool works. Three or more: compare flat plans against per-account pricing in our [cost guide](/cheapest-pinterest-scheduler).',
        'Do you create your own images? If not, weigh automatic pin creation against the AI-image trade-off.',
        'Is Pinterest your main channel? If yes, a Pinterest-specific tool is usually better value than a general one.',
        'Do you need a team with approvals? Then look at Hootsuite or Metricool Advanced.',
      ),
      h2('plans', 'GoPinKaro plans'),
      plansTable(),
    ],
    faqs: [
      { q: 'What is the best Pinterest scheduler?', a: 'It depends on your needs: Tailwind is the established Pinterest specialist, Buffer or Publer are cheapest for one account, BlogToPin or PinBoostr create pins for you, Metricool is strongest for analytics, and GoPinKaro suits bulk scheduling across many accounts.' },
      { q: 'What is the best free Pinterest scheduler?', a: `Pinterest's built-in scheduler is free but limited to one pin at a time. GoPinKaro's free plan gives ${free.pins} pins a month with bulk import, and Metricool and Buffer also have free plans.` },
      { q: 'Which Pinterest scheduler is cheapest?', a: 'For one account, Buffer or Publer at about $5 a month. For three or more accounts, a flat plan such as GoPinKaro Starter ($9) costs less.' },
      { q: 'Are Pinterest schedulers safe?', a: 'Yes, when they connect through Pinterest\'s official sign-in and API and you keep a steady, varied pace. Avoid tools that ask for your password.' },
    ],
    related: ['cheapest-pinterest-scheduler', 'safest-pinterest-scheduler', 'pinterest-scheduler-pricing', 'best-pinterest-tools'],
    sources: [SRC.tailwindPricing, SRC.blogtopinPricing, SRC.pinboostrPricing, SRC.bufferPricing, SRC.laterPricing, SRC.planolyPricing, SRC.metricoolPricing, SRC.hootsuitePlans, SRC.publerRoundup, SRC.nativeLimits],
  },

  // ───────────────────────────────────────── seasonal calendar (US)
  {
    path: 'guides/pinterest-seasonal-content-calendar-us',
    kind: 'guide',
    label: 'Pinterest seasonal content calendar (US)',
    title: 'Pinterest seasonal content calendar for US holidays',
    description: 'When to start pinning for US holidays: a 2026 to 2027 calendar for Valentine\'s Day through Christmas, with how early Pinterest users plan and how to schedule ahead.',
    h1: 'Pinterest seasonal content calendar for US holidays (2026 to 2027)',
    intro: 'Pinterest users plan well ahead: guidance from Pinterest\'s own business community and marketing guides points to publishing Christmas content in October, Thanksgiving in September and Mother\'s Day from February. The calendar below gives US holiday dates and a suggested start window for each, so you can schedule seasonal pins weeks before people search.',
    updated: CHECKED,
    published: CHECKED,
    cta: { label: 'Schedule seasonal pins ahead', redirect: '/dashboard/bulk' },
    blocks: [
      h2('why', 'Why seasonal pins start early'),
      p('Pinterest is a planning platform: people look for ideas weeks before they need them, and a pin takes time to gain traction. Sources consistently recommend publishing seasonal pins at least two weeks before the event, and many suggest a lead time of 45 to 90 days for major holidays. The windows below use roughly 60 to 90 days as a starting point. They are planning suggestions, not Pinterest rules, so check your own analytics.'),
      h2('calendar', 'US holiday calendar and suggested start'),
      table(['Occasion', 'Date', 'Suggested start publishing'], [
        ['New Year, organization and goals', 'Jan 1', 'Early to mid November'],
        ['Valentine\'s Day', 'Feb 14', 'Late November to December'],
        ['St. Patrick\'s Day', 'Mar 17', 'Early to mid December'],
        ['Easter', 'Apr 5, 2026; Mar 28, 2027', 'January'],
        ['Mother\'s Day', 'May 10, 2026; May 9, 2027', 'February (sources suggest February to May)'],
        ['Father\'s Day', 'Jun 21, 2026; Jun 20, 2027', 'March'],
        ['Fourth of July', 'Jul 4', 'Late March to April'],
        ['Back to school', 'Late July to early September', 'May to June'],
        ['Labor Day', 'Sep 7, 2026; Sep 6, 2027', 'June'],
        ['Halloween', 'Oct 31', 'August'],
        ['Thanksgiving', 'Nov 26, 2026; Nov 25, 2027', 'September'],
        ['Black Friday and Cyber Monday', 'Nov 27 and Nov 30, 2026', 'September to October'],
        ['Christmas and Hanukkah', 'Dec 25; Hanukkah dates vary', 'October'],
      ], 'Dates are the standard US dates. Start windows combine the guidance in the sources below with a 60 to 90 day lead; adjust for your niche.'),
      h2('plan', 'How to plan a season'),
      ol(
        'Pick the 4 to 6 occasions that matter for your niche, not all of them.',
        `Check which related searches are rising in the [keyword tool](/pinterest-keyword-tool) a few months before.`,
        'Create 5 to 10 fresh pins per occasion with different images and angles, rather than repeating one pin.',
        `Schedule them across the whole window with the [bulk scheduler](/pinterest-bulk-scheduler). You can schedule up to ${FACTS.scheduleAheadDays} days ahead, so a full year can be loaded early.`,
        'Link each pin to a specific page: a recipe, a collection or a gift guide.',
        'After the date, review analytics and note what to start earlier next year.',
      ),
      h2('pace', 'Keep the pace sensible'),
      p(`Do not cram a season into a few days. Spread seasonal pins across weeks at a steady pace, and keep fresh evergreen pins going alongside. GoPinKaro warns when a day goes above ${FACTS.dailySoftMax} pins or an image repeats within 7 days. See [how often to pin](/guides/how-often-to-pin-on-pinterest).`),
      callout('Timing guidance varies by source and niche. Use these windows as a starting point and let your own results decide.', 'A note on the evidence'),
    ],
    faqs: [
      { q: 'When should I start pinning Christmas content?', a: 'Sources suggest publishing Christmas content in October, and roughly 60 to 90 days ahead is a common planning window.' },
      { q: 'When should I post Thanksgiving pins?', a: 'Many guides suggest September for Thanksgiving, which falls on the fourth Thursday of November (November 26 in 2026).' },
      { q: 'How early do Pinterest users plan?', a: 'Guidance from Pinterest\'s business community and marketing guides suggests users plan 30 to 45 days ahead, and often longer for major holidays.' },
      { q: 'Can I schedule seasonal pins a year ahead?', a: `Yes. GoPinKaro schedules up to ${FACTS.scheduleAheadDays} days ahead, so you can load a season in the quiet months.` },
    ],
    related: ['guides/best-time-to-post-on-pinterest', 'pinterest-bulk-scheduler', 'guides/how-to-find-pinterest-keywords', 'use-cases/print-on-demand'],
    sources: [SRC.seasonalCommunity, SRC.seasonalGuide, SRC.contentCalendar],
  },

  // ───────────────────────────────────────── statistics
  {
    path: 'guides/pinterest-statistics',
    kind: 'guide',
    label: 'Pinterest statistics',
    title: 'Pinterest statistics for 2026: users, US audience, trends',
    description: 'Pinterest user and audience numbers for 2026 with sources: monthly users worldwide and in the US, demographics, revenue, and what they mean for scheduling.',
    h1: 'Pinterest statistics for 2026: users, US audience and what they mean',
    intro: 'Pinterest reported 631 million monthly active users worldwide in Q1 2026, with the US and Canada at 106 million. Roundups put the US at about 90 million monthly users. Here are the numbers, where they come from, and what they imply if you publish pins for a US audience.',
    updated: CHECKED,
    published: CHECKED,
    cta: { label: 'Start scheduling for a US audience', redirect: '/dashboard' },
    blocks: [
      h2('numbers', 'The headline numbers'),
      table(['Metric', 'Figure', 'Note'], [
        ['Monthly active users, worldwide', '631 million (Q1 2026)', 'Record high; about 11% growth year over year, as reported'],
        ['US and Canada monthly users', '106 million (Q1 2026)', 'About 4% growth year over year, as reported'],
        ['US monthly users (estimate)', 'About 90 million', 'Industry estimate; projected to approach 100 million by the end of 2026'],
        ['Share of users who are women', 'About 72% (global)', 'Roundup figure'],
        ['Share of users who are Gen Z', 'Over 50%', 'Reported as Pinterest\'s largest and fastest-growing group'],
        ['Full-year 2025 revenue', 'Over $4.2 billion', 'Up about 16% year over year, as reported'],
        ['Q1 2026 revenue', 'About $1.008 billion', 'Up about 18% year over year, as reported'],
      ], 'Figures as reported by the roundups below, which summarize Pinterest\'s quarterly results. Check Pinterest\'s investor pages for the exact current numbers.'),
      h2('us', 'What this means for a US audience'),
      ul(
        '**The audience is large and still growing.** Even a small share of 90 million US users is a big pool for blogs, shops and services.',
        '**Planning behavior matters.** People search ahead of events, so a US seasonal calendar pays off. See the [US holiday calendar](/guides/pinterest-seasonal-content-calendar-us).',
        '**Visual search favors specific phrases.** Long, specific searches suit niche content. See [how to find Pinterest keywords](/guides/how-to-find-pinterest-keywords).',
        '**The audience skews younger and female** according to the roundups, which can guide topics and tone, though your own analytics matter more.',
      ),
      h2('limits', 'How to treat statistics'),
      p('User numbers say how big the platform is, not how well your pins will do. Results depend on your niche, your images and your consistency. Demographic splits come from third-party roundups and vary by source. Use them for context, not for forecasting.'),
      h2('gopinkaro', 'Using this with GoPinKaro'),
      p(`Pick a US timezone in settings so best-time slots land in your audience's evenings and afternoons, set the keyword tool to the United States, and use the [pacing and analytics tools](/guides/pinterest-analytics-metrics-explained) to learn what works for your own audience. Plans are priced in US dollars, starting free (${free.pins} pins a month) and from $${starter.price} a month.`),
    ],
    faqs: [
      { q: 'How many people use Pinterest?', a: 'Pinterest reported 631 million monthly active users worldwide in Q1 2026.' },
      { q: 'How many Pinterest users are in the US?', a: 'Pinterest reported 106 million monthly users in the US and Canada in Q1 2026, and roundups estimate about 90 million in the US alone.' },
      { q: 'Who uses Pinterest?', a: 'Roundups report that about 72% of users are women and that Gen Z is the largest and fastest-growing group.' },
      { q: 'Are these numbers official?', a: 'They summarize Pinterest\'s quarterly results as reported by third-party roundups. For exact figures, check Pinterest\'s investor relations pages.' },
    ],
    related: ['guides/pinterest-seasonal-content-calendar-us', 'guides/best-time-to-post-on-pinterest', 'best-pinterest-schedulers', 'guides/pinterest-analytics-metrics-explained'],
    sources: [SRC.statsSocialChamp, SRC.statsSocialPilot],
  },
]
