import { FACTS, CHECKED, SRC } from './facts'
import { callout, h2, h3, p, plansTable, steps, table, ul, type SeoPage } from './types'

const { starter } = FACTS

export const useCasePages2: SeoPage[] = [
  // ───────────────────────────────────────── agencies
  {
    path: 'use-cases/agencies',
    kind: 'use-case',
    label: 'Pinterest scheduler for agencies',
    title: 'Pinterest scheduler for agencies and freelancers',
    description: `Run client Pinterest accounts from one dashboard: up to ${FACTS.accounts.business} accounts, per-account queues and analytics, and one flat price instead of per-account fees.`,
    h1: 'Pinterest scheduling for agencies and freelancers',
    intro: `If you manage Pinterest for several clients, per-account pricing adds up quickly: ten accounts on a per-channel tool is about $50 a month. GoPinKaro Pro covers ${FACTS.accounts.pro} accounts for $${FACTS.pro.price} and Business covers ${FACTS.accounts.business} for $${FACTS.business.price}, with a separate queue, calendar and analytics for each client.`,
    updated: CHECKED,
    published: CHECKED,
    cta: { label: 'Connect your first client account', redirect: '/dashboard/accounts' },
    blocks: [
      h2('workflow', 'A workflow that scales to many clients'),
      steps(
        ['Connect each client account', 'With the client\'s permission, sign in to their Pinterest account and use Add account. Name it after the client so it is easy to find in the switcher.'],
        ['Build the queue per client', 'Switch to the account, then use bulk upload, a CSV or a page import to fill its calendar. Each account keeps its own boards and schedule.'],
        ['Watch the Accounts page', 'It shows every account with scheduled, failed and published counts, and flags the ones that need attention first, such as an expired connection.'],
        ['Report from the analytics', 'Each account has its own analytics view with impressions, saves and clicks, with history up to 90 days on paid plans.'],
      ),
      h2('why', 'Why the pricing model matters for agencies'),
      table(['Accounts', 'Per-account tools (about $5 each)', 'GoPinKaro'], [
        ['3', 'About $15 a month', `$${starter.price} a month (Starter)`],
        ['10', 'About $50 a month', `$${FACTS.pro.price} a month (Pro)`],
        ['25', 'About $125 a month', `$${FACTS.business.price} a month (Business)`],
        ['100', 'About $500 a month', `$${FACTS.business.price} a month (Business)`],
      ], 'Per-account figures use Buffer\'s $5 per channel as the reference. Plans cap pins per month, shared across accounts: Starter 300, Pro 1,500, Business 6,000, so check your total volume.'),
      p('Pins are pooled, not per account: with Business, 6,000 pins a month across 100 accounts is about 60 each. A smaller roster gets a larger share per client.'),
      h2('safety', 'Keeping clients\' accounts safe'),
      ul(
        'Sign-in uses Pinterest\'s official OAuth, so you never handle client passwords.',
        'Access tokens are stored encrypted. A client can revoke GoPinKaro\'s access at any time in their Pinterest settings.',
        `A pacing check flags a day above ${FACTS.dailySoftMax} pins and repeated images for each account separately.`,
        'Adding a client\'s account to your workspace never lets that client sign in to yours.',
      ),
      h2('limits', 'What it does not do (yet)'),
      callout('GoPinKaro has no team seats, roles or client approval workflow today, and it does not produce white-label reports. If you need those, look at Hootsuite\'s Advanced plan or Metricool\'s Advanced and Custom plans, or use them for reporting while GoPinKaro does the publishing.', 'Honest limits'),
      h2('plans', 'Plans'),
      plansTable(),
    ],
    faqs: [
      { q: 'Can I manage client Pinterest accounts with GoPinKaro?', a: `Yes, with each client's permission. One login manages up to ${FACTS.accounts.business} Pinterest accounts on Business, ${FACTS.accounts.pro} on Pro and ${FACTS.accounts.starter} on Starter.` },
      { q: 'Do I need each client\'s password?', a: 'No. You sign in to the client\'s Pinterest account in your browser (with their permission) and approve access on Pinterest\'s page. GoPinKaro never sees the password.' },
      { q: 'Can my team share one login?', a: 'There are no team seats or roles yet, so people would share one login. If you need separate permissions or approvals, consider Hootsuite or Metricool for that part of the work.' },
      { q: 'How is the pin allowance shared?', a: 'The monthly pin allowance of your plan is pooled across all accounts, not per account.' },
    ],
    related: ['manage-multiple-pinterest-accounts', 'guides/how-to-manage-multiple-pinterest-accounts', 'metricool-alternative-for-pinterest', 'hootsuite-alternative-for-pinterest'],
    sources: [SRC.bufferPricing, SRC.hootsuitePlans, SRC.metricoolPricing],
  },

  // ───────────────────────────────────────── print on demand
  {
    path: 'use-cases/print-on-demand',
    kind: 'use-case',
    label: 'Pinterest scheduler for print-on-demand',
    title: 'Pinterest scheduler for print-on-demand shops',
    description: 'Schedule pins for print-on-demand products in bulk from a CSV: many designs and colors, one steady pace, with duplicate and repeated-image warnings built in.',
    h1: 'Pinterest scheduling for print-on-demand shops',
    intro: 'Print-on-demand shops have many designs and variants and little time to pin each one by hand. A spreadsheet-driven workflow lets you schedule hundreds of pins in one sitting, pace them across weeks, and avoid the main trap: posting the same image again and again.',
    updated: CHECKED,
    published: CHECKED,
    cta: { label: 'Upload a CSV of pins', redirect: '/dashboard/bulk' },
    blocks: [
      h2('csv', 'One row per pin'),
      p(`Create a spreadsheet with four columns: the public image address, a title, a description and the listing link. Save it as CSV and import it on the bulk scheduling page, up to ${FACTS.bulkMax} pins at a time on paid plans. Review each row, pick a board and choose the pace.`),
      table(['Column', 'What to put in it', 'Example'], [
        ['image_url', 'A public https image address', 'https://yourshop.com/images/mug-blue.jpg'],
        ['title', 'Keyword first, up to 100 characters', 'Funny coffee mug for teachers, ceramic 11 oz'],
        ['description', 'What it is, who it is for, a soft call to action; up to 800 characters', 'A ceramic teacher mug with a funny quote. A gift idea for the end of term.'],
        ['link', 'The product or listing page', 'https://yourshop.com/products/teacher-mug'],
      ], 'Illustrative example only. Use your own products.'),
      h2('variants', 'Handling many variants'),
      ul(
        '**Different angles, not the same image.** Mockups on different products, rooms or models give each pin a different image. Repeating the exact image is the pattern Pinterest discourages.',
        `**Space them out.** GoPinKaro warns when an image repeats within 7 days and when a day goes above ${FACTS.dailySoftMax} pins.`,
        '**Group by board.** Put designs for one niche on one board and write board names with the keywords buyers use.',
        '**Use a carousel for color variants** so one pin shows several options instead of five near-identical pins. See [carousel pins](/pinterest-carousel-pin-scheduler).',
      ),
      h2('plan-ahead', 'Plan seasons early'),
      p(`You can schedule up to ${FACTS.scheduleAheadDays} days ahead, so gift-season pins can be loaded in the quiet months and spread across the weeks before the rush. Use the [keyword tool](/pinterest-keyword-tool) to see which gift and seasonal searches are rising before you write titles.`),
      h2('design', 'Making text pins without a designer'),
      p(`Quote and slogan products often need a simple text pin as well as the mockup. The [pin designer](/pinterest-pin-maker) has ${FACTS.designer.templates} layouts and ${FACTS.designer.palettes} color sets and saves 1000 x 1500 images you can schedule straight away.`),
      h2('plans', 'Plans'),
      plansTable(),
    ],
    faqs: [
      { q: 'Can I schedule print-on-demand pins in bulk?', a: `Yes. Import a CSV with image, title, description and link columns, up to ${FACTS.bulkMax} pins at a time on paid plans, then choose a board and a pace.` },
      { q: 'How many pins a day should a shop post?', a: 'Pinterest has no official number. Commonly repeated guidance is a handful to about 15 new pins a day, with fresh images rather than repeats. GoPinKaro warns above 15 a day.' },
      { q: 'Will Pinterest penalise repeated mockups?', a: 'Pinterest discourages repeating the same pin. Use different images and spread similar pins several days apart; GoPinKaro flags an image reused within 7 days.' },
      { q: 'Does it work with Etsy or Shopify?', a: 'Pins link to any product page. You can import product pages by address or sitemap, or upload a CSV exported from your store.' },
    ],
    related: ['use-cases/etsy-sellers', 'use-cases/shopify-stores', 'pinterest-bulk-scheduler', 'guides/how-often-to-pin-on-pinterest'],
    sources: [SRC.automationGuide, SRC.pinterestPinSpecs],
  },

  // ───────────────────────────────────────── food bloggers
  {
    path: 'use-cases/food-bloggers',
    kind: 'use-case',
    label: 'Pinterest scheduler for food bloggers',
    title: 'Pinterest scheduler for food bloggers',
    description: 'Keep recipe pins flowing: import posts from your sitemap, write keyword-first titles, schedule video and carousel pins, and plan seasonal recipes months ahead.',
    h1: 'Pinterest scheduling for food bloggers',
    intro: 'Recipe content suits Pinterest: people search for ideas, save them and come back to cook. The challenge is keeping a steady stream of pins as the archive grows. GoPinKaro turns recipe posts into drafted pins, schedules them at a sensible pace, and handles video and step-by-step carousels.',
    updated: CHECKED,
    published: CHECKED,
    cta: { label: 'Import your recipe posts', redirect: '/dashboard/import' },
    blocks: [
      h2('archive', 'Put your archive to work'),
      steps(
        ['Import recipes from your sitemap', `On Pro and above, read your sitemap and pick up to 25 recipe posts at a time. Each post's images appear for you to choose from.`],
        ['Write keyword-first titles', 'Start with what people search for: "Easy weeknight chicken pasta", not "Mom\'s Tuesday special". Choose from three drafted options and edit.'],
        ['Add a description and alt text', 'Name the dish, key ingredients and a time or occasion. Alt text describes the photo and helps search.'],
        ['Schedule a steady pace', 'A few pins a day beats a burst. Best-time slots spread them across the hours Pinterest is typically busy.'],
      ),
      h2('formats', 'Use the formats recipes suit'),
      h3('Video pins'),
      p('A short clip of the final dish or a key technique makes a good video pin. Upload an MP4 or MOV (4 seconds to 15 minutes), choose a cover, and schedule it. See [video pin scheduling](/pinterest-video-pin-scheduler).'),
      h3('Carousel pins'),
      p('A carousel of 2 to 5 images works for step-by-step recipes or before-and-after shots. See [carousel pins](/pinterest-carousel-pin-scheduler).'),
      h3('Text-led pins'),
      p(`Roundups such as "15 weeknight dinners" suit a bold headline or a big number. The [pin designer](/pinterest-pin-maker) has a layout for each.`),
      h2('seasons', 'Plan seasonal recipes early'),
      p(`Schedule up to ${FACTS.scheduleAheadDays} days ahead, so holiday recipes can be queued well before the season and released over several weeks. Check which seasonal searches are rising in the [keyword tool](/pinterest-keyword-tool) first.`),
      h2('tips', 'Tips specific to recipe pins'),
      ul(
        'Use vertical images (2:3, for example 1000 x 1500) with the dish clearly visible.',
        'Put the recipe name and the main search phrase near the start of the title.',
        'Link every pin to the specific recipe post, not your home page.',
        'Pin each recipe more than once over time with different images instead of repeating one.',
      ),
      h2('plans', 'Plans'),
      plansTable(),
    ],
    faqs: [
      { q: 'Can I schedule recipe pins from my food blog?', a: 'Yes. Import a recipe post (or pick posts from your sitemap on Pro and above), choose images, edit the drafted titles and descriptions, and schedule.' },
      { q: 'How often should a food blogger pin?', a: 'Steadily rather than in bursts. Many guides suggest a few new pins a day. GoPinKaro\'s pacing check warns if a day goes above 15.' },
      { q: 'Does it support recipe videos?', a: 'Yes. Upload an MP4 or MOV between 4 seconds and 15 minutes and choose a cover; GoPinKaro uploads it to Pinterest when the pin is due.' },
      { q: 'Can I schedule holiday recipes months ahead?', a: `Yes, up to ${FACTS.scheduleAheadDays} days ahead.` },
    ],
    related: ['use-cases/bloggers', 'website-to-pinterest-pins', 'guides/how-to-find-pinterest-keywords', 'guides/pinterest-title-and-description-examples'],
    sources: [SRC.keywordResearch, SRC.pinterestVideoSpecs],
  },
]
